### ISSUE TITLE
Very unclear message when missing use statements and annotation loader

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14199]
I was struggling to debug why I got a circular reference error trying to add my controller to a new application. The controller below with the config in routing.yml should be able to reproduce this. I found out that the error is triggered by a missing use statement: `use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;` as I used `@Template()`. I get the same error if the `@Route` use statement is missing.

This error is very unclear and should be able to get a better message.

```
FileLoaderImportCircularReferenceException in FileLoader.php line 97:
Circular reference detected in "/home/ivanderberg/projects/login/www/app/config/routing.yml" ("/home/ivanderberg/projects/login/www/app/config/routing.yml" > "/home/ivanderberg/projects/login/www/src/App/Controller" > "/home/ivanderberg/projects/login/www/app/config/routing.yml").
```

```
// routing.yml
app:
    resource: "@App/Controller"
    type:     annotation
    prefix:   /
```

```php
<?php
namespace App\Controller\Auth;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * @Route(service="app.controller.auth.login")
 */
class LoginController
{
    /**
     * @Route("/", name="app.auth.login")
     * @Template()
     */
    public function loginAction()
    {
        return [];
    }
}

```

**Comment by javiereguiluz** [comment]
Related to #14073?

**Comment by WouterJ** [comment]
Looks related to https://github.com/symfony/symfony/issues/14073

**Comment by WouterJ** [comment]
Oh, haha. Now I'm almost sure it is related :smile:

**Comment by fabpot** [comment]
Now that #14073 has been fixed, can we close this one as well?

**Comment by iltar** [comment]
@fabpot is https://github.com/symfony/symfony/pull/14192/files supposed to fix this? If so I will try this tomorrow and close this issue if it indeed fixes it.

**Comment by fabpot** [comment]
@iltar Indeed

**Comment by nicolas-grekas** [comment]
#14073 fixes error reporting and makes this error understandable. Still, it does not fix the root of this very issue, which is:
- the routes are loaded but this fails with an exception because the route definition has an issue
- this exception is handled by the HttpKernel and re-injected for rendering to the exception controller route
- but this also fails because for the same reason, the routes can not be loaded.

The root issue is that the router is not able to partially load the routes that are required for displaying the exception page.

**Comment by iltar** [comment]
Closed in favor of #14342
