### ISSUE TITLE
Symfony console requires database access

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony#16587]
cache:clear, debug:router etc for some bizarre reason fail if the configured database is not accessible; for instance when on a host/vm situation and running these from the host instead of the vm. Looks to me like a DB connection is stablished for no reason whatsoever.

This is also making our lives too difficult when setting up CI - we've had to hack around a little so that symfony reverts to sqlite when run on our jenkins boxes.

You absolutely shouldn't need to stablish a db connection unless you're actually going to use it.

**Comment by nicolas-grekas** [comment]
Can you please check if this applies and fixes the issue?
http://blog.insight.sensiolabs.com/2014/12/22/making-symfony-bootable-with-dbal-2-5.html

**Comment by luispabon** [comment]
Thank you Nicolas, I'm having a look, will report back :+1:

**Comment by luispabon** [comment]
That worked fine :+1: thank you @nicolas-grekas 

Might be a good idea perhaps to add this to the default config/parameters.yml with some explanation?

**Comment by rvanlaak** [comment]
For me this happens during a `composer install`, where it isn't possible to pass the right environment. 
```
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
```
The command fails because `dev` is the default environment, and the testing server isn't able to connect to that. The fix @nicolas-grekas proposed also didn't work. Should it also be configured on the `orm` level?

**Comment by apfelbox** [comment]
@rvanlaak you should set the environment via an environment variable:

```
SYMFONY_ENV='prod' composer install
```

See the docs: http://symfony.com/doc/current/cookbook/configuration/environments.html#selecting-the-environment-for-console-commands

**Comment by rvanlaak** [comment]
That does indeed do the trick for Composer, the link you gave only is related to the Symfony console. :+1:

**Comment by javiereguiluz** [comment]
If you ask me, this is a pretty awful Doctrine change that should be "fixed" or changed in Doctrine. Until recently we didn't need this ... and we were happy and everything worked perfectly.

This reminds me of the *"is_granted() problem in error pages"*. We spent years teaching our users about this "problem", until one day @lyrixx [changed five lines of code](https://github.com/symfony/symfony/pull/15953/files) and the "problem" was gone forever.

**Comment by apfelbox** [comment]
@rvanlaak actually, I was searching for it in the docs, but I somehow can't find it. :wink: 
@stof mentioned it multiple times in the issue trackers, but I never found the official docs page for it.

**Comment by fabpot** [comment]
I agree with @javiereguiluz, this should be fixed in Doctrine and unfortunately, there is nothing we can do in Symfony.

**Comment by luispabon** [comment]
There is though, at least a warning the docs or perhaps a commented out config option for the DB version with an explanation wouldn't hurt and would require no boilerplate code on symfony to work around it.

**Comment by jrobeson** [comment]
Has anybody from the symfony core team bugged the doctrine folks about solving this?

**Comment by tristanbes** [comment]
Still happening, has to put down version in 

```
doctrine:
    dbal: 
        server_version: 10.0
```

But I don't know if I have to put 10.0 because I use MariaDB, or put 5.6, because it's based on a 5.6 mysql engine...

**Comment by tristanbes** [comment]
I've found the issue : https://github.com/doctrine/dbal/issues/990
Opened in 2014 by @stof

**Comment by Glideh** [comment]
@javiereguiluz's [hint](http://blog.insight.sensiolabs.com/2014/12/22/making-symfony-bootable-with-dbal-2-5.html) fixed the issue for me (docker image build containing a `cache:clear`)
I had to specify the `server_version` in the configured dbs (`doctrine.yaml`):

Example:
```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:MY_DB_URL)%'
                server_version: mariadb-10.2.9
//...
```
