### ISSUE TITLE
GroupBy feature for Many-To-Many relations

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#17093]
```php
->add('recipientContacts', EntityType::class, [
    'mapped' => false,
    'required' => false,
    'multiple' => true,
    'expanded' => false,
    'class' => Contact::class,
    'query_builder' => function (EntityRepository $repository) {
        return $repository->createQueryBuilder('contact')
            ->where('contact.enabled = true')
            ->orderBy('contact.name', 'ASC');
    },
    'group_by' => 'groups.name',
])
```

Important is this line:
```php
 'group_by' => 'groups.name',
```

**I am not sure about the following statement. This is just an assumption.**

This is not working because there is a Many-to-Many relation between ``Contact`` and ``ContactGroup``.

If a ``Contact`` would only have 1 group it should work. **Am I right with this?**

I think this is right because I get the following error:
```
Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "Doctrine\ORM\PersistentCollection".
```
(Yes: ``ContactGroup`` contains ``getName()``)

**Comment by ProPheT777** [comment]
This is not related to symfony, you should ask to doctrine https://github.com/doctrine/doctrine2

**Comment by Hanmac** [comment]
i think its more a general problem because how do you search after a groups name if the Contact can have many of them?

what you can do is group by is after the count of groups, or if possible join the group names into a single string and use group_by on that, but i don't know if that is what you want

**Comment by JHGitty** [comment]
I would prefer to have a list where the users are duplicated if there are in multiple groups. This could be filtered out later again. But yes, I understand your issue.

There should be a warning (exception) in this case to let the user understand that this is currently not possible. Or there should be just a fix for this.

**Comment by Hanmac** [comment]
i  investigate a bit, i think the change does need to be done for [DefaultChoiceListFactory::addChoiceViewGroupedBy](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L191)
that it does allow that an array is returned and the choice entries can be duplicated.

but i does not suspect such a change happen in <= 3.0 maybe 3.1 or 4.0

**Comment by JHGitty** [comment]
A change for >= 3.1 would be ok, hopefully it will just be fixed. :smile:

**Comment by Hanmac** [comment]
i for my self would not count that as bug that should be fixed, but more like a feature that would be nice to be implemented.

**Comment by Tobion** [comment]
In some ticket (that I cannot find) I suggest to be able to have `group_by` callable be able to return an array of groups. Then the choice could be put into multiple groups. This should indeed solve this use-case.

But the description of the ticket with `'group_by' => 'groups.name',` makes no sense as `groups` returns a traversable that does not have a `name` property. This cannot work obviously.

**Comment by stof** [comment]
@Tobion As of Symfony 2.7 (i.e. the new ChoiceType system), passing a callable to ``group_by`` is already supported (property paths are converted to callables using the property accessor).

So you can already to whatever you want for the grouping.

I'm closing this issue, as the code behaves as expected. The error message tells you that ``getName`` is missing in ``Doctrine\ORM\PersistentCollection``, not in ``ContactGroup``, because this is what the ``groups`` property path returns.
And handling collections of a single element as if they were this element directly won't happen. Making ``$a`` and ``array($a)`` equivalent would be a major WTF for users facing this behavior.

**Comment by Tobion** [comment]
@stof yes you can use callable. But what this issue is about is that the `callable` should be able to return an ARRAY instead of a single group label to support many-to-many-relationships. So IMO this should be reopened.

**Comment by stof** [comment]
Well, you should return a string representing what the grouping is. An array would still not work, as it cannot be casted to string to create the group.
what you could do is using ``implode(', ', $groupNames)`` as grouping identifier for instance

**Comment by JHGitty** [comment]
I just need a generic solution to do something like this. I don't think that I am the only person who needs it.

I have ``Contact`` which is a real person (Name, Street, City, ..). I also have ``ContactGroup``. There is a many-to-many relationship between ``Contact`` and ``ContactGroup``.

I like to have a page where I have all ``Contact`` but grouped by ``ContactGroup``. Every ``Contact`` should have a checkbox to select it. The groups are only for better usability.

It would be the best way if contacts would be duplicated if they are in multiple groups. Reason: I like to add a checkbox to each group to allow to select all contacts in their. This could easily be done with Javascript.

1. Could you provide me an easy solution?

2. I think we should add it to the symfony documentation. Do you think the same?

**Comment by Tobion** [comment]
@stof the idea is to duplicate the choice into each group name of the array.

```
'group_by' => function (Contact $choice) {
    return array_map(function (ContactGroup $group) {
        return $group->getName();
    }, iterator_to_array($choice->getGroups))
}
```
And if array element is string castable, you could even just do `'group_by' => 'groups'`.

**Comment by Tobion** [comment]
Again, `group_by` only supports MANY-TO-ONE currently. But not MANY-TO-MANY.

**Comment by stof** [comment]
@Tobion well, choices cannot be duplicated by the ``group_by`` option. It would be weird to me to create new choices in a grouping feature. Duplicating choices involves creating several subtypes, and so does not impact only the view.

**Comment by Tobion** [comment]
group_by only influences the view. So to me it's senible that a `ChoiceView` could be added to several `ChoiceGroupView`s.

**Comment by JHGitty** [comment]
@stof What would you do to do the thing I've described?
