### ISSUE TITLE
hasReference() does not work with aliases.

### ISSUE THREAD

**Issue by murnieza** [symfony/symfony#17110]
`hasReference()` uses [`getDefinition()`](https://github.com/symfony/symfony/blob/e93ef5d2b8649802ee573659b8240c2b7a915a79/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1152) which does not resolve aliases and throws exception when alias is provided.

IMHO `findDefinition()` should be used. Opinions?

**Comment by stof** [comment]
Aliases are already resolved to definitions by a compiler pass. Are you trying to dump a non-compiled container ?

**Comment by murnieza** [comment]
In dependency injection extension I add method call with reference to alias. My alias is created by custom compiler pass.

**Comment by stof** [comment]
is your compiler pass registered as a late one, running after optimizers ? This might be an issue (but it would also mean that it would detect the reference as broken when validating the container)

**Comment by murnieza** [comment]
[This is part](https://github.com/ongr-io/FilterManagerBundle/blob/6921be1c07816bac486fd230dc740cd5d76292bf/DependencyInjection/ONGRFilterManagerExtension.php#L147) where I create reference. And [this is](https://github.com/ongr-io/FilterManagerBundle/blob/6921be1c07816bac486fd230dc740cd5d76292bf/DependencyInjection/Compiler/FilterPass.php#L49) where I create alias. [This](https://github.com/ongr-io/FilterManagerBundle/blob/6921be1c07816bac486fd230dc740cd5d76292bf/ONGRFilterManagerBundle.php#L54) is how I add my compiler pass.

**Comment by murnieza** [comment]
I've done some more investigations. Problem is that my aliased service is public and it does not get past the check in [`ReplaceAliasByActualDefinitionPass`](https://github.com/kriswallsmith/symfony-scoped-container/blob/ba17fd9502df264dfa20df7638dd232ca554669a/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php#L32) and is not resolved to service.

After changing my aliased service to `public: false` alias is resolved correctly and dumping succeeds. Is this intended behaviour?

**Comment by jakzal** [comment]
@murnieza if a definition is public, we cannot replace the alias as the service could be accessed by its id. 

What are you trying to achieve as I don't fully understand what's the issue?

**Comment by xabbuh** [comment]
@murnieza Maybe it's best if you can fork the Symfony Standard Edition and make the smallest amount of changes that is needed to reproduce the behaviour you experience if you think this behaviour is a bug.

**Comment by javiereguiluz** [comment]
Let's close this old issue because there is no more feedback and it looks like a workaround was found for this problem. @murnieza if you don't agree, please reopen it. Thanks!
