### ISSUE TITLE
[Process] currently not suitable for running processes with large output

### ISSUE THREAD

**Issue by avindra** [symfony/symfony#17390]
By default, [PHP uses a memory_limit of 128M](http://php.net/manual/en/ini.core.php#ini.sect.resource-limits). 

Since Symfony/Process stores all output in ```private $stdout;``` and ```private $stderr;```, this means that as soon as the output hits 128MB, your PHP script using Symfony/Process will fatally error out with:

```
[15-Jan-2016 06:31:02 America/New_York] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 131862121 bytes) in /app/myapp/vendor/symfony/process/Process.php on line 815
```

You can test this pretty quickly by just doing this (assuming you have GNU Coreutils installed):

```php
require("vendor/autoload.php");
use Symfony\Component\Process\Process;

$process = new Process('yes "Hello"');
$process->setTimeout(172800);
$process->run(function ($type, $buffer) {
        // do nothing
});
```

Unfortunately, we assumed that Symfony/Process was already using a temporary buffer for closures, and saw this issue in production. To mitigate the issue for now, we bumped up our ```memory_limit```, but ideally this should be fixed in Symfony itself.

Since the upper limit on a PHP string itself is 2GB, this also means that Symfony/Process will currently die when the buffer reaches 2GB, no matter what. Here's a sample of that error

```
[15-Jan-2016 10:16:05 America/New_York] PHP Fatal error:  String size overflow in /app/myapp/vendor/symfony/process/Process.php on line 799
```

In my opinion, registering closure to ```run``` should mean that the entire buffer should not be stored in memory.

Please share your thoughts.

**Comment by avindra** [comment]
Changing this function solves my issue:

```
protected function buildCallback($callback)
{
    $out = self::OUT;
    $callback = function ($type, $data) use ($callback, $out) {
        if (null !== $callback) {
            call_user_func($callback, $type, $data);
        } else {
            if ($out == $type) {
                $this->addOutput($data);
            } else {
                $this->addErrorOutput($data);
            }
        }
    };
    return $callback;
}
```

Is this valid to have in the core code?

**Comment by avindra** [comment]
Confirming that tests still pass with this change:

Before:

```
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

....S.S........................................................  63 / 147 ( 42%)
...............S............................................... 126 / 147 ( 85%)
.....................                                           147 / 147 (100%)

Time: 6.23 seconds, Memory: 35.25Mb

OK, but incomplete, skipped, or risky tests!
Tests: 147, Assertions: 271, Skipped: 3.
```

After:

```
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

....S.S........................................................  63 / 147 ( 42%)
...............S............................................... 126 / 147 ( 85%)
.....................                                           147 / 147 (100%)

Time: 6.1 seconds, Memory: 35.25Mb

OK, but incomplete, skipped, or risky tests!
Tests: 147, Assertions: 271, Skipped: 3.
```

**Comment by fabpot** [comment]
ping @romainneutron

**Comment by romainneutron** [comment]
We could think about storing this in a `SplTempFileObject` ? I'm gonna try this

**Comment by avindra** [comment]
@romainneutron : What are your thoughts on not storing any of the data if a user passes a closure? The PR I've referenced does exactly that and fixes the issue.

In my opinion, this shouldn't be considered BC because in the documentation ```->run($closure)``` and ``->run(); ->getOutput()``` are clearly defined as two separate examples.

In the case that you would consider this BC, can we get an option to not store the output in the object itself? It is simply wasteful, and causes serious issues at the edge.

**Comment by romainneutron** [comment]
Sorry, I missed your PR. Actually, this is a BC break. 

To be more precise about my proposition: `SplTempFileObject` is not that good, a temporary stream is a better idea.

**Comment by romainneutron** [comment]
This is a BC break because the previous behavior (using a callback and `Process::getOutput` at the same time) is currently possible

**Comment by avindra** [comment]
Makes sense. What about adding an option to ```Process``` to prevent storing the output data internally? Would that just make the api messier / better to wait for Symfony4 to make a change like this?

**Comment by romainneutron** [comment]
As I mentioned above, I'm currently working on a stream-based store for these data, you should not be annoyed by this limit in the future

**Comment by avindra** [comment]
Sure, thank you. For anyone else who needs a fix immediately (using the BC change where registering a closure stops the internal string variables from being populated), feel free to use this class

```php
<?php

use Symfony\Component\Process\Process;

/**
 * Temporary class to ensure that symfony processes
 * never run out of memory.
 *
 * @todo: Revert back to core Symfony if/when core Process
 * is fixed.
 */
class ProcessEnhanced extends Process
{
    protected function buildCallback($callback)
    {
        $out = self::OUT;
        $callback = function ($type, $data) use ($callback, $out) {
            if (null !== $callback) {
                call_user_func($callback, $type, $data);
            } else {
                if ($out == $type) {
                    $this->addOutput($data);
                } else {
                    $this->addErrorOutput($data);
                }
            }
        };
        return $callback;
    }
}
```

And just use ```ProcessEnhanced``` instead of ```Process```.

**Comment by romainneutron** [comment]
I just opened a PR regarding this issue

**Comment by avindra** [comment]
Btw, it seems that there really isn't any way to get around the 2GB PHP string limit, so that should probably be documented as a caveat for ```getOutput```

**Comment by romainneutron** [comment]
Now that we're near to a stream-based storage, it's easy to implement a new feature : `Process::getOutputAsStream` for example that would ease reading data when it exceeds 2GB

**Comment by romainneutron** [comment]
Moreover, we can increase performance by allowing a callback whenever output is disabled.

**Comment by romainneutron** [comment]
@avindra I pushed https://github.com/symfony/symfony/issues/17427 that would allow you to disable output and use your own callback to avoid buffering data in filesystem.

**Comment by avindra** [comment]
@romainneutron : Thanks, that looks great. Can you verify that this would be the way to use a future version of ```Process``` that won't explode from excessive memory usage?

```php
use Symfony\Component\Process\Process;

$process = new Process('yes "Hello"');
$process->setTimeout(172800);
$process->disableOutput();
$process->run(function ($type, $buffer) {
        // do nothing
});
````

**Comment by romainneutron** [comment]
I don't see any problem with the snippet you mention if my PR is merged in master. It will available in Process 3.1 and it would save lots of memory in your case

**Comment by avindra** [comment]
Thanks @romainneutron, just bumped to 3.1 and it works as expected by calling `disableOutput` and passing a callback.

**Comment by infendory** [comment]
I'm still having this issue in latest 5.0 and latest 3.4 versions. 

```
php test.php
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 98566176 bytes) in /home/xxx/consoletest/vendor/symfony/process/Pipes/UnixPipes.php on line 122
```
Here is test project:
[consoletest.zip](https://github.com/symfony/symfony/files/4521257/consoletest.zip)

**Comment by kgpanteon** [comment]
@avindra I have used symfony 2.8 in which I want to call process async without waiting for output. Output is not require. If any error comes then it will logged to the file.

Currently having issue when disabling the output and adding callback function.

`$process = new Process('ls -lsa');
$process->setWorkingDirectory($rootDirPath);
$process->disableOutput();
 $process->setTimeout(0);
$that = $this;

$process->start(function ($type, $buffer) use ($that) {
        $command = new \Bundle\Command\TriggerWebshopCommand();
        $command->setContainer($that->container);
        $input = new ArrayInput(array(          
                'event_type' => $eventType,
                'event_type_id' => $eventTypeId,
                'ignore_status' => true
        ));
        $output = new NullOutput;
        $resultCode = $command->run($input, $output);
 });`


**OR**


 $process = new Process($cmdToExecute);
$process->start();
$process->wait(function ($type, $buffer) {
    if (Process::ERR === $type) {
        echo 'ERR > '.$buffer;
    } else {
        echo 'OUT > '.$buffer;
    }
});

Both snippet getting failed.

**Comment by avindra** [comment]
@infendory that crashed at about 134MB, seems like you hit the default memory limit.

Have you tried bumping the [memory limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit)?

```ini
; php ini setting to remove memory constraints
memory_limit = -1
```

**Comment by avindra** [comment]
@kgpanteon Symfony 2.8 should be upgraded if that is possible.

if you're really stuck, you might want to use this workaround from 2016:

https://github.com/symfony/symfony/issues/17390#issuecomment-172574987
