### ISSUE TITLE
Symfony Form Deprecation Notices improvements

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony#18523]
I came across some deprecation notices (form for example, as per the screen shot), where by I am not able to make use of the stack trace. 
I think adding arguments to function calls will make debugging/removing deprecations much easier.

<img width="1056" alt="screen shot 2016-04-12 at 7 15 14 pm" src="https://cloud.githubusercontent.com/assets/1475845/14465197/1bba0e82-00e3-11e6-973c-1e4dc6160656.png">

<img width="1045" alt="screen shot 2016-04-12 at 7 18 01 pm" src="https://cloud.githubusercontent.com/assets/1475845/14465257/4ecd3ed4-00e3-11e6-9136-b44fe0d466a9.png">

**Comment by iltar** [comment]
Given the stacktraces it's really easy to trace back where it originates from: `MediaPlanConroller.php:141`. I think the problem with the deprecation message is that it doesn't know what called it, so it cannot show that. The best you can do is check how you build your form and see if anything of that uses a `ChoiceType`. Maybe I missed something, but this is how I fixed ~30 forms without problems when removing deprecation notices.

**Comment by xabbuh** [comment]
I completely agree with @iltar here. Tracing the deprecation down from the starting point in your controller usually shouldn't be that hard.

**Comment by ZCJ** [comment]
Tracing the depreciation for a simple form is easy. It becomes more time consuming when you have nested forms and the trace only shows you the parent form. It becomes even more time consuming in cases such as "setNormalizer" screen shot where it was not directly part of my form type .
@webmozart  what do you think?

**Comment by webmozart** [comment]
@iltar @xabbuh You're right that it's easy to find the controller, but with complex nested forms the stack trace becomes useless. What you want to know is that in your OrderLineType you forgot to add "choices_as_values", even if that type is nested in OrderBodyType, which may be nested in OrderType. With the current stack trace (see above), figuring something like this out becomes really tedious.

**Comment by acidjames** [comment]
Hello,

Here is another example that's harder to debug : 

![screenshot from 2017-05-24 11-20-24](https://cloud.githubusercontent.com/assets/2505667/26396490/a4435986-4073-11e7-9ed7-39078f57aeb0.png)

I suppose this has something to do with some bundles i'm using that haven't followed code changes. Or maybe not.

What happens if i search "core" in the vendor/ folder...

![screenshot from 2017-05-24 11-24-56](https://cloud.githubusercontent.com/assets/2505667/26396598/f7207bca-4073-11e7-942a-cdebd1ea953a.png)

Is is possible to know which bundle is affected ? 

:)

**Comment by iltar** [comment]
As you're using phpstorm, go to the `getName` method and `find usages`, then check the one that uses 'core' as name. I agree though, that this could be done easier.

**Comment by stof** [comment]
Well, this happens inside the `EnvironmentConfigurator` in your screenshot. And this tells me that you are using an outdated version of Symfony, as this was fixed in 2.7.19, 2.8.12, 3.1.5 and 3.2.0

**Comment by acidjames** [comment]
Thanks @iltar @stof im updating step by step from 2.8. the screens are from 3.0. ill try updating then ans checking usage in phpstorm.

**Comment by jakzal** [comment]
Is there anything left to do here?

**Comment by acidjames** [comment]
@jakzal  I guess this can be closed

**Comment by javiereguiluz** [comment]
Closing then. Thanks!
