### ISSUE TITLE
[FrameworkBundle] Command classes can't be reused in services

### ISSUE THREAD

**Issue by SenseException** [symfony/symfony#19001]
During my work on creating multiple commands with similar tasks, I encountered a problem that one Command class can't be used with 2 or more services in Symfony.
## My Code

I have created the command class `TestCommand` without using `setName` in the configure-part of the command's code:

``` php
namespace AppBundle\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('<error>'.$this->getName().'</error>');
    }
}
```

I've created 2 services using this command class:

``` yaml
services:
  app.command.service1:
    class: AppBundle\Command\TestCommand
    arguments: [ "test1" ]
    tags:
      - { name: console.command }

  app.command.service2:
    class: AppBundle\Command\TestCommand
    arguments: [ "test2" ]
    tags:
      - { name: console.command }
```

When I call the list of all commands, `test2` will be listed and is executable, but `test1` doesn't even exist.
## The Problem

After some research I found that in the CompilerPass `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass` Is using the class name to create an alias, that is used for the commands to run them. It seems like this is because of BC to the non service commands, that are read and initialized in `Symfony\Component\HttpKernel\Bundle\Bundle::registerCommands`.

In the Bundle class, all command classes in the Command directory of a bundle are searched with the Finder and the container is checked if there are service ids with the format of 

``` php
'console.command.' . $classNameOfCommands;
```

that is built with the class names of the found Command classes. If the id already exists, because of the mentioned CompilerPass, it skips to the next Command.

This id format of the Command's alias has to be kept the same in the CompilerPass to stay compatible with `Symfony\Component\HttpKernel\Bundle\Bundle::registerCommands` and prevent errors in there, but this makes it impossible to reuse Command classes.
## Possible Solution

I want to create a PR that is going to introduce something like this in `AddConsoleCommandPass`:
### Before

(Line ~36)

``` php
$class = $container->getParameterBag()->resolveValue($definition->getClass());
if (!is_subclass_of($class, 'Symfony\\Component\\Console\\Command\\Command')) {
    throw new \InvalidArgumentException(sprintf('The service "%s" tagged "console.command" must be a subclass of "Symfony\\Component\\Console\\Command\\Command".', $id));
}
$container->setAlias($serviceId = 'console.command.'.strtolower(str_replace('\\', '_', $class)), $id);
$serviceIds[] = $serviceId;
```
### After

``` php
$class = $container->getParameterBag()->resolveValue($definition->getClass());
if (!is_subclass_of($class, 'Symfony\\Component\\Console\\Command\\Command')) {
    throw new \InvalidArgumentException(sprintf('The service "%s" tagged "console.command" must be a subclass of "Symfony\\Component\\Console\\Command\\Command".', $id));
}
$serviceId = 'console.command.'.strtolower(str_replace('\\', '_', $class));
if ($container->hasAlias($serviceId)) {
    $serviceId = $serviceId . '_1'; // suffix can't be static, _1 is not the solution
}
$container->setAlias($serviceId, $id);
$serviceIds[] = $serviceId;
```
## Before I create a PR

Before I start to fix this, I want to know if this solution is okay or if there can occur some other problems or BC breaks with this solution. **The suffix also can't be static like "_1"** so we may be able to use 3, 4 or more commands with the same class. I guess there should be more checked than just the existence of the alias too, but maybe I'm thinking too complex in that matter.

What's your opinion about my PR idea?

**Comment by iltar** [comment]
Lets say this problem is solved like this, how would you solve the naming conflict? Each command has a name (debug:router for example). Both will share the same name like this.

**Comment by javiereguiluz** [comment]
> During my work on creating multiple commands with similar tasks [...]

Maybe you could create a big command to group all those tasks, or you could create a base command and extend from it to create different commands or you could use PHP traits to reuse code or create very basic commands and delegate that common work to some managers, etc.

**Comment by SenseException** [comment]
@iltar My example has 2 commands using the same command class: test1 and test2. Because the name is injectable in the constructor, there is no naming conflict. The behaviour on two services injecting the same name is still the same like two command injecting the same name in `setName` during a Command's `configure` execution.

@javiereguiluz A big command has a higher complexity and is harder to test. Maintainability is also higher and more sensitive to errors and regressions. There's no KISS in that solution.
Inheritance is my current workaround and not really a solution. Symfony is a framework, that encourages developers to use dependency injection in so many parts of its code, but treats its commands not the same way. It would be more consistent and DRY when we can reuse Commands the same way every other class can be used.

I think of Command-services more of a best practice than putting them in a "Command" directory, naming the classes with the suffix "Command" and let Symfony do some magic with this old special case solution. My planned PR would move Commands one step closer to the same level as other Symfony classes and services. This makes it also easier for newcomers.

**Comment by iltar** [comment]
@SenseException injecting commands is like injecting controllers, don't do it. Big commands? Move your code to the service layer instead. Commands should be (like controllers) thin; Contain (nearly) no logic. Extending controllers/commands is a bad practice and not the right way to share logic.

**Comment by SenseException** [comment]
@iltar I don't inject Commands, I inject the name into the Command with a service. I also inject the dependencies into the command with services to keep the Command thin like Controllers. Because I agree with you on keeping the code out of the Command, I want a Command not to be ContainerAware, but to inject only the dependencies. I also want to be able reuse Commands.

The dependencies, as the command name, will be injected with the service definitions. My Command's constructor has type hints to interfaces.

**Comment by Ener-Getick** [comment]
Indeed this is a limitation of symfony. Your workaround looks good to me and is already used to generate method names in the [``PhpDumper``](https://github.com/Ener-Getick/symfony/blob/795399a02bc68e404179c9f7ee7624715f1667b8/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1386) for example.

**Comment by SenseException** [comment]
I'll provide a PR for review soon.

**Comment by mcfedr** [comment]
I just came across this issue today, I am also injecting the `name` into the command.

When looking at the `AddConsoleCommandPass` - I dont see the need for the alias that it adds - why not just use the user given `id` of the service, it already uniquely identifies the command

**Comment by Ener-Getick** [comment]
@mcfedr the alias is used in ``Bundle`` to detect if the command has already been loaded (as they don't need to be registered as services).
