### ISSUE TITLE
[TwigBundle] The "core" extension is not enabled.

### ISSUE THREAD

**Issue by marcj** [symfony/symfony#20284]
In `\Twig_Environment::getExtension` there's a line `$environment->getExtension('core')`, but fails as `core` does not exist in `$this->extensions` of `\Twig_ExtensionSet`. I printed its array keys and there's only `Twig_Extension_Core, Twig_Extension_Escaper, Twig_Extension_Optimizer` etc, so full class names and not an alias like `core`.

Also `addExtension` of `\Twig_ExtensionSet` uses always the `get_class` result, I don't see where `core` should come from. Any Idea?

```
  [Twig_Error_Runtime]
  The "core" extension is not enabled.


Exception trace:
 () at /Users/marc/bude/jarves.io/vendor/twig/twig/lib/Twig/ExtensionSet.php:83
 Twig_ExtensionSet->getExtension() at /Users/marc/bude/jarves.io/vendor/twig/twig/lib/Twig/Environment.php:605
 Twig_Environment->getExtension() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/DependencyInjection/Configurator/EnvironmentConfigurator.php:40
 Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator->configure() at /Users/marc/bude/jarves.io/var/cache/dev/appDevDebugProjectContainer.php:4732
 appDevDebugProjectContainer->getTwigService() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Users/marc/bude/jarves.io/var/cache/dev/appDevDebugProjectContainer.php:4204
 appDevDebugProjectContainer->getTemplatingService() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Users/marc/bude/jarves.io/var/cache/dev/appDevDebugProjectContainer.php:1802
 appDevDebugProjectContainer->getJarves_Content_RenderService() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Users/marc/bude/jarves.io/vendor/jarves/jarves/JarvesBundle.php:274
 Jarves\JarvesBundle->registerContentTypes() at /Users/marc/bude/jarves.io/vendor/jarves/jarves/JarvesBundle.php:130
 Jarves\JarvesBundle->configure() at /Users/marc/bude/jarves.io/vendor/jarves/jarves/JarvesBundle.php:73
 Jarves\JarvesBundle->boot() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:121
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:68
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/marc/bude/jarves.io/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /Users/marc/bude/jarves.io/bin/console:29
```

**Comment by fabpot** [comment]
Can you give me Twig version? Can you also try the tip of 1.x with twigphp/Twig#2200 applied and tell me if that fixes your issue?

**Comment by marcj** [comment]
All installed versions:

```
marc@osx ~/bude/jarves.io (master*) $ composer show --installed
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
composer/composer                    1.0.0              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/semver                      dev-master 0bdf393 Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses               dev-master 96c6a07 SPDX licenses list and validation library.
doctrine/annotations                 dev-master f9cf507 Docblock Annotations Parser
doctrine/cache                       dev-master fe68e4f Caching library offering an object-oriented API for many cache backends
doctrine/collections                 dev-master 2dfc898 Collections Abstraction library
doctrine/common                      dev-master f74f44d Common Library for Doctrine projects
doctrine/dbal                        dev-master ec8fc16 Database Abstraction Layer
doctrine/doctrine-bundle             dev-master 99165b9 Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0              Symfony Bundle for Doctrine Cache
doctrine/inflector                   dev-master 803a2ed Common String Manipulations with regard to casing and singular/plural rules.
doctrine/lexer                       dev-master 83893c5 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
friendsofsymfony/rest-bundle         2.1.0              This Bundle provides various tools to rapidly develop RESTful API's with Symfony
icap/html-diff                       dev-master f58ddb1 A PHP5 library that diffs (compares) HTML files.
incenteev/composer-parameter-handler dev-master d7ce7f0 Composer script handling your ignored parameter file
jarves/jarves                        dev-master 6e9efd2 An open-source Content-Management-System CMS as Symfony Bundle.
jdorn/sql-formatter                  dev-master 7ef9b85 a PHP SQL highlighting library
justinrainbow/json-schema            1.6.1              A library to validate a json schema.
kadet/keylighter                     0.8.x-dev 0d2e6e4  Yet another syntax highlighter for PHP
michelf/php-markdown                 1.6.0              PHP Markdown
monolog/monolog                      1.x-dev 214b8ef    Sends your logs to files, sockets, inboxes, databases and various web services
nelmio/api-doc-bundle                dev-master 958e697 Generates documentation for your REST API from annotations
paragonie/random_compat              v2.0.3             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
propel/propel                        dev-master 58d57ad Propel2 is an open-source Object-Relational Mapping (ORM) for PHP 5.5 and up.
propel/propel-bundle                 3.0.x-dev 213b419  Integration of Propel in Symfony2
psr/log                              dev-master 4ebe3a8 Common interface for logging libraries
seld/cli-prompt                      dev-master 8cbe109 Allows you to prompt for user input on the command line, and optionally hide the characters they type
seld/jsonlint                        1.4.1              JSON Linter
seld/phar-utils                      dev-master 7009b51 PHAR file format utilities, for when PHP phars you up
sensio/distribution-bundle           dev-master 7bc47dc Base bundle for Symfony Distributions
sensio/framework-extra-bundle        3.0.x-dev 0fd0205  This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              dev-master b9be7f1 This bundle generates code for you
sensiolabs/security-checker          dev-master 116027b A security checker for your composer.lock
swiftmailer/swiftmailer              5.x-dev a6d3097    Swiftmailer, free feature-rich PHP mailer
sybio/image-workshop                 dev-master c46dcf4 Powerful PHP class using GD library to work easily with images including layer notion (like Photoshop or GIMP)
symfony/monolog-bundle               dev-master 44f3daf Symfony MonologBundle
symfony/phpunit-bridge               dev-master d80b41a Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            dev-master 0f8dc2c Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            dev-master 53ad9fa Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               dev-master 3dd0fbb Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               dev-master a42f4b6 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                dev-master ef830ce Symfony utilities for portability of PHP codes
symfony/security-acl                 dev-master 053b49b Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle           dev-master c6e5fdd Symfony SwiftmailerBundle
symfony/symfony                      v3.0.9             The Symfony PHP framework
symfony/yaml                         dev-master 3d42c56 Symfony Yaml Component
twig/extensions                      dev-master c6d9082 Common additional features for Twig that do not directly belong in core
twig/twig                            dev-master 02c0cb5 Twig, the flexible, fast, and secure template language for PHP
willdurand/jsonp-callback-validator  v1.1.0             JSONP callback validator.
willdurand/negotiation               2.x-dev 1f210db    Content Negotiation tools for PHP provided as a standalone library.
```

**Comment by fabpot** [comment]
I've just merged 2200, so can you try with the latest commit of 1.x branch, it should be fixed now.

**Comment by fabpot** [comment]
Oh, I see that you are using Symfony 3.0. It won't work unfortunately as 3.0 is not maintained anymore. You need to either upgrade to 3.1 or use Twig 1.x.

**Comment by marcj** [comment]
Ok, I'm a bit confused since I don't explicitly require twig itself. Symfony is doing it for me.

1. Is 3.0 now not compatible with twig anymore?
2. Since Symfony 3.0.9 requires `twig/twig: ~1.23|~2.0` I shouldn't get a dev-master version, should I?

I did:

```
marc@osx ~/bude/jarves.io (master*) $ composer update twig/twig
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating twig/twig dev-master (02c0cb5 => cda9a0f)
    Checking out cda9a0f7a4561dc66c8d9f1d4163327339750bbd
```

which means I got your lately merged pull-request, but get the exact same error.

To get Symfony 3.0 working with Twig again, I need to specify now always a different Twig version, or how am I supposed to fix that in the future for new projects?

**Comment by fabpot** [comment]
The "problem" is that you specifically asked for dev versions in your `composer.json` file (`"minimum-stability": "dev"`). And Symfony works with both Twig 1.x (stable) and Twig 2.0 (not yet released, so only dev versions which are a moving target still). Here, you are using Symfony 3.0, which is not maintained anymore with Twig 2.0, which is not released yet. So, 3.0 has not been updated to work with the latest changes in Twig 2.0.

**Comment by marcj** [comment]
Ok, I guess the dev-master of 2.0 branch broke in the last days/weeks with Symfony 3.0 as it worked until lately. Your changes of cda9a0f7a4561dc66c8d9f1d4163327339750bbd didn't fix the issue, I guess?

I thought `"minimum-stability": "dev"` only **allows** third party libraries to install not stable versions, not that it installs now always dev-master stuff although the external packages (like yours) specified a concrete tagged version.

I'm trying 3.1 now.

**Comment by fabpot** [comment]
You were very lucky that nothing broken before :) And indeed, nothing will fix that as Twig 2.0 drops deprecated features.

**Comment by xabbuh** [comment]
closing as Symfony 3.0 is not maintained anymore

**Comment by amici** [comment]
If you really don't want to upgrade Symfony, you can try adding the request for twig manually in your composer.json, but limit the version to 1.*, like this:
    "require": {
           ...
        "twig/twig": "<2.0",
        "symfony/symfony": "3.0.*",

**Comment by patkar** [comment]
@amici At least write `^1.0` instead of `<2.0`

**Comment by skobkin** [comment]
Same problem after upgrading Twig from 1.31.0 to 2.1.0 in Symfony 2.7 project.

**Comment by Dersoncarlos** [comment]
version php > 5

**Comment by TomasVotruba** [comment]
In case of someone comming in the future upgrading old legacy project like me :slightly_smiling_face: , this is related to new Twig syntax, that is not yet updated in TwigBundle class.

Here is the patch that you need to apply to make it work :+1: 

```diff
--- /dev/null
+++ ../src/Symfony/Bundle/TwigBundle/DependencyInjection/Configurator/EnvironmentConfigurator.php
@@ -42,12 +42,12 @@
 
     public function configure(\Twig_Environment $environment)
     {
-        $environment->getExtension('core')->setDateFormat($this->dateFormat, $this->intervalFormat);
+        $environment->getExtension(\Twig\Extension\CoreExtension::class)->setDateFormat($this->dateFormat, $this->intervalFormat);
 
         if (null !== $this->timezone) {
-            $environment->getExtension('core')->setTimezone($this->timezone);
+            $environment->getExtension(\Twig\Extension\CoreExtension::class)->setTimezone($this->timezone);
         }
 
-        $environment->getExtension('core')->setNumberFormat($this->decimals, $this->decimalPoint, $this->thousandsSeparator);
+        $environment->getExtension(\Twig\Extension\CoreExtension::class)->setNumberFormat($this->decimals, $this->decimalPoint, $this->thousandsSeparator);
     }
 }
```
