### ISSUE TITLE
[ParamConverter] Unable to guess how to get a Doctrine instance from the request information 

### ISSUE THREAD

**Issue by Belgacem-TLILI** [symfony/symfony#21563]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             | 
| Symfony version  | 3.2.3

This happen after the last update from Symfony 3.2.2 to 3.2.3 
In my action i have multiple routes like below

```php

 /**
     * @Route("/my-route", name="first_route", defaults={"type" = null})
     * @Route("/my-route/report/{objectId}/{startDate}/{endDate}", name="second_route", defaults={"type" = null})
     * @Route("/my-route/{objectId}/{startDate}/{endDate}/{type}", name="third_route", defaults={"type" = null})
     * @ParamConverter(name="object", Class="MyBundle:MyObjectClass")
     */
    public function indexAction(Request $request, $object = null, $startDate = null, $endDate = null, $type)
    {
// Logic
}

```

if i try to access to the page with the route /my-route i get the below exception

![screen shot 2017-02-08 at 10 11 18 am](https://cloud.githubusercontent.com/assets/431580/22725492/26217a08-ede7-11e6-867e-5d602ac97630.png)

**Comment by iltar** [comment]
Can you add the `startDate` and `endDate` to your defaults with `null` and see if that works?

/cc @chalasr

**Comment by chalasr** [comment]
@Belgacem-TLILI If the given solution doesn't help, we'll need more information: 
Is the code snippet exact, or is it something generic adapted for opening this issue? What is the name of the parameter that can't be converted (hidden in the screenshot)? Do you have any issue when browsing other routes defined on your action (if the answer is yes, please describe them as well)?

The best would be to create a fork of the [standard edition](https://github.com/symfony/symfony-standard) including the changes necessary to reproduce. Thanks.

**Comment by Belgacem-TLILI** [comment]
@iltar  /cc @chalasr 
The code snippet it is adapted for opening the issue,
i'm using the first route to access to my page, the name of the parameter that can't be converted is object 
i fixed the issue by adding isOptional="true" to the  ParamConverter

```php

 /**
     * @Route("/my-route", name="first_route", defaults={"type" = null})
     * @Route("/my-route/report/{objectId}/{startDate}/{endDate}", name="second_route", defaults={"type" = null})
     * @Route("/my-route/{objectId}/{startDate}/{endDate}/{type}", name="third_route", defaults={"type" = null})
     * @ParamConverter(name="object", Class="MyBundle:MyObjectClass", isOptional="true")
     */
    public function indexAction(Request $request, $object = null, $startDate = null, $endDate = null, $type)
    {
// Logic
}

```

**Comment by Belgacem-TLILI** [comment]
This was working before the update to symfony 3.2.3 and i can access to my page using the 3 routes without any issue.

**Comment by xabbuh** [comment]
Which version of SensioFrameworkExtraBundle do you have?

**Comment by xabbuh** [comment]
To add to my question: Can you check if your issue is caused by sensiolabs/SensioFrameworkExtraBundle@bd7e329d99d01acbc36876b14c916cfefdee6d26 which was fixed by sensiolabs/SensioFrameworkExtraBundle@ed86f6fb1753e76b39ff8b87f527045ca6b97169 (and is part of version 3.0.21).

**Comment by Belgacem-TLILI** [comment]
@xabbuh Yes the issue is caused by 
sensiolabs/SensioFrameworkExtraBundle@bd7e329

**Comment by Belgacem-TLILI** [comment]
@xabbuh  Thank you: We have SensioFrameworkExtraBundle  version 3.0.21 but we don't have this commit sensiolabs/SensioFrameworkExtraBundle@ed86f6f

**Comment by xabbuh** [comment]
This looks weird. Can you reinstall SensioFrameworkExtraBundle?

**Comment by Belgacem-TLILI** [comment]
@xabbuh ive reinstalled SensioFrameworkExtraBundle but i still don't have the commit

![screen shot 2017-02-09 at 2 22 53 pm](https://cloud.githubusercontent.com/assets/431580/22779283/84a6fc6e-eed3-11e6-9ff3-1523b97c1700.png)

![screen shot 2017-02-09 at 2 23 15 pm](https://cloud.githubusercontent.com/assets/431580/22779293/8aa543a0-eed3-11e6-9621-aa5a7c3e544d.png)

**Comment by xabbuh** [comment]
But the commit is there (see the `reference` attribute in the `composer.lock` file as well as the contents of the PHP file.

**Comment by Belgacem-TLILI** [comment]
@xabbuh sorry i misunderstand, the issue is coming from that commit i was think it was reverted 
if i remove the false parameter from DoctrineParamConverter it works like before the migration to 3.2.3

![screen shot 2017-02-09 at 3 32 18 pm](https://cloud.githubusercontent.com/assets/431580/22781688/0b950816-eedd-11e6-8ee0-d523e4cfb1e8.png)

**Comment by chalasr** [comment]
It seems to be a remaining side effect from the changes made in #21333 and #21379. 
Before the param converter was relying on a request attribute that was automatically created for the `$object` argument, so the param converter was calling `setOptional(true)`. Now the request attribute is not created anymore (it was causing an annoying bug on argument resolvers) so the call doesn't occur.

AFAIK fixing it would require to use reflection in order to add a `|| ($argument->isDefaultValueAvailable() && null === $argument->getDefaultValue())` to the existing check. I'll try to fix it that way on the bundle if no objection.

**Comment by iltar** [comment]
@chalasr does that include the php 7.1 nullable? Because that's pretty much his signature due to a non-optional argument as last.

**Comment by chalasr** [comment]
@iltar The previous behavior was not supporting nullable types (https://github.com/chalasr/symfony/commit/d3fa8a1859b85490356b4c559b900a5256341331#diff-90cbecfd4505e6e8af5842db11add3b5L142) but only default values including null. I think we can fix it for that so it works as expected, and add support for the nullable type in a next time (if we want to improve param converters of course :) )

**Comment by chalasr** [comment]
@Belgacem-TLILI Could you please try the following patch on your project and tell me if it fixes the issue? https://github.com/chalasr/SensioFrameworkExtraBundle/commit/71ab09640b5eda802e060eb7a4794d0f5d66eacd

**Comment by chalasr** [comment]
ping @Belgacem-TLILI

**Comment by Belgacem-TLILI** [comment]
@chalasr no that didn't fix the issue

**Comment by chalasr** [comment]
I updated the patch meantime, is it the one you tried?

**Comment by Belgacem-TLILI** [comment]
@chalasr i tested the below

<img width="987" alt="screen shot 2017-02-11 at 15 23 53" src="https://cloud.githubusercontent.com/assets/431580/22853369/2b7d35e4-f06e-11e6-89da-18b84bc3db3c.png">

**Comment by chalasr** [comment]
@Belgacem-TLILI Sorry for the fail. It would be nice if you could try this one https://github.com/chalasr/SensioFrameworkExtraBundle/commit/1068c57a27bc5053403b9925f3ae0f3bb0a1e9b8, it should be ok now.

**Comment by Belgacem-TLILI** [comment]
@chalasr chalasr/SensioFrameworkExtraBundle@1068c57 fix the issue

**Comment by chalasr** [comment]
Thank you for confirming. I opened a PR on the bundle.

**Comment by Belgacem-TLILI** [comment]
You are Welcome

**Comment by fancyweb** [comment]
@chalasr I updated a big project from 3.2.2 to 3.2.7 today and I'm still having the same problem of this issue, despite your fixes. I think it is because I don't use the "auto_convert" option. Here is my config, could you have a quick look ?

config.yml
```yaml
sensio_framework_extra:
    request:
        converters: true
        auto_convert: false
```

BrandController.php
```php
    /**
     * @Route("/brand/new", name="app_brand_create")
     * @Route("/brand/{id}-{slug}/edit", requirements={"id"="\d+", "slug"="[^/]*"}, name="app_brand_edit")
     * @ParamConverter("brand", class="ES\CoreBundle\Entity\Brand", options={"id"="id"})
     */
    public function editAction(Request $request, Brand $brand = null)
    {
    }
```

The `/brand/new` path is not working after upgrading because of the changes in this commit https://github.com/symfony/symfony/pull/21333

**Comment by chalasr** [comment]
@fancyweb this is indeed a side effect of the changes made in #21333, but your code was working by chance: an empty `brand` request attribute was created by the `@Route` annotation loader, and the DoctrineParamConverter was relying on it (reaching [this line](https://github.com/chalasr/SensioFrameworkExtraBundle/blob/3.0/Request/ParamConverter/DoctrineParamConverter.php#L49-L51)). 

To fix that, you have to make your param converter optional: `@ParamConverter("brand", ..., optional=true)`.
This is what `auto_convert` does for you based on the action signature. In your case this should have been required from the beginning, sorry about that.

**Comment by fancyweb** [comment]
@chalasr Thank you for your time. I had found the fix, but I wanted to be sure that it was not an unexpected BC.
