### ISSUE TITLE
TwigBundle's ExtensionPass does extensive filesystem lookup, and fail when project root dir is under open_basedir restrictions

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#22149]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=3.2

In Symfony\Bundle\TwigBundle\DependencyInjection\Compiler\ExtensionPass, you may see the following method:
```php
    private function getComposerRootDir($rootDir)
    {
        $dir = $rootDir;
        while (!file_exists($dir.'/composer.json')) {
            if ($dir === dirname($dir)) {
                return $rootDir;
            }

            $dir = dirname($dir);
        }

        return $dir;
    }
```

Which looks up for the composer.json, but in our environments, the project main folder is under the **open_basedir restriction**, ``file_exists()`` call will generate PHP warnings; because the extension cannot find the composer.json due to **open_basedir restriction**. Because it does not find the file, the algorithm continues down until it reaches the filesystem root. In another scenarios, we could deploy applications without the composer.json (why not).

Is there any valid reason for doing this lookup?

In our use case, due to this buggy lookup behaviour, it will register a Twig_Loader_Filesystem instance which is plugged on the filesystem root (it seems very, very wrong to me).

In most Symfony applications, this would suffice:
```php
$composerRootDir = dirname($container->getParameter('kernel.root_dir'));
```

I don't understand why this was introduced, it seems to give a more flexible way of registering templates for highly customized projects, but it's also a very dangerous thing to do.

Another way of fixing this might by introducing an optional parameter we could set ourselves to the project root, such as:
```php
if ($container->hasParameter('kernel.composer_root_dir')) {
    $composerRootDir = $container->getParameter('kernel.composer_root_dir');
} else {
    $composerRootDir = $this->getComposerRootDir($container->getParameter('kernel.root_dir'));
}
```

**Comment by pounard** [comment]
Using git bisect found the culprit to be #20428

**Comment by xabbuh** [comment]
You could just build the container and remove the `composer.json` file afterwards instead of doing the opposite.

**Comment by pounard** [comment]
@xabbuh We are not removing the composer.json that's not the point, but an example, the real problem is that with security restriction, this just does not work.

**Comment by pounard** [comment]
Another side effect is that during normal runtime (by normal I mean when caches are not rebuilt, production mode) it seems that the loaders attempt a realpath() on the found project path, which causes PHP warnings and failures.

**Comment by nicolas-grekas** [comment]
Can't this be fixed with the new `Kernel::getProjectDir()` method? Anyone who would like to give it a try?

**Comment by mvrhov** [comment]
Have not figured this one out but we are removing composer.json when generating deploy.tar.gz file. And the container gets rebuild on the server.

**Comment by pounard** [comment]
@nicolas-grekas I guess it depends on the `getProjectDir()` implementation, I hope it's not traversing the filesystem until it finds the `composer.json` file else the fail would be the exact same.

**Comment by pounard** [comment]
According to https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L317 the problem will probably still exist using the `getProjectDir()` method. Nevertheless, for consistency reasons, the TwigBundle should use it from the 3.3 version.

The good thing with `getProjectDir()` is we actually can override it, and it would be a perfectly fine solution for me.

**Comment by nicolas-grekas** [comment]
I meant: just provide the `kernel.project_dir` param to the constructor.

**Comment by pounard** [comment]
Could be it, still needs to be fixed, this is a real bug, can it be tagged as such ?

**Comment by pounard** [comment]
@nicolas-grekas I opened the #22570 PR, and I will open new ones for fixing >=3.0 to <=3.2 versions, because our productions sites are misbehaving, and people should be allowed to fix this on their live applications.
