### ISSUE TITLE
Don't throw fatal errors for unused env vars

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23520]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.x

While upgrading an app to Symfony 3.3 + Symfony Flex, I'm facing some issues. All of them look reasonable to me, except this one:

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\EnvParameterException:

Environment variables "DATABASE_URL" are never used. Please, check your
container's configuration.
```

I think it's crazy to throw a fatal error just because I'm not using a defined env var. Could we please change this behavior? Thanks!

**Comment by nicolas-grekas** [comment]
I don't think it's a crazy decision we made. Of course this can be reconsidered, but the argumentd in the original discussion should not be discarded too fast. See #19681

**Comment by javiereguiluz** [comment]
I apologize if "crazy" sounded too harsh 😞

**Comment by sstok** [comment]
https://github.com/symfony/symfony/pull/19681#issuecomment-243572493 this one?

Maybe we can add an option to white-list some env vars usage 🤔 but were to initialize this configuration. Because it's part of the Container, and we can't (shouldn't) use static.

**Comment by fabpot** [comment]
I think I agree with @javiereguiluz here. I've add this issue more than once and that's annoying. Let's talk about this :)

**Comment by nicolas-grekas** [comment]
There is the unused case and the swallowed case, which is the bad one. The current exceptions help DX by spotting otherwise silent failures. Not sure we can separate both cases, thus really not sure this is a good idea to remove the exceptions...

**Comment by nicolas-grekas** [comment]
Related to #22726 and #22561

**Comment by eXtreme** [comment]
Having info about unused envs sound reasonable but this error also happens, as explained in #22561, by just overriding some configs in test env - which is very annoying and was a BC break for me (but happened only in test env for me, but could happen if someone had envs used in dev and then overwritten configs for prod).

**Comment by javiereguiluz** [comment]
While upgrading Symfony Demo to Flex this happened to us again:

```
1) App\Tests\Command\AddUserCommandTest::testCreateUserNonInteractive with data set #0 (false)
Symfony\Component\DependencyInjection\Exception\EnvParameterException:
Environment variables "DATABASE_URL" are never used. Please, check your container's configuration.
```

Not that easy to solve because the database URL is different in the test environment and we don't have a `.env.test`.

**Comment by fefas** [comment]
@nicolas-grekas .. sorry if my message in the #22726 sounded harsh and I even didn't know if the solution I proposed on this PR would be a good one. My primary intention there was to bring this discussion up, because nobody (member or owner) answered to the issue I opened (#22561).

I'd read the original discussion (#19681) before I've even opened that issue to understand what I would be doing wrong. Actually, I didn't understand everything there because both I don't really know how Symfony works under the hood and the thread is too long. In this way, for me (as a final user), the exception thrown seems to be "crazy". I also saw the PR #22976 that is an improvement, because it helps us to understand what we did "wrong".

Anyway, our situation now is: we are trying to deliver our application using docker containers and all of the configuration is made through environments variables. That helps us both for Continuous Integration and for easy and fast Deployment. Now, we can deploy a complete new environment using only one command with a new set of env variables that are sent on containers startup. Given the context, it's completely normal that some environments variable is overridden sometimes.

With that exception, Symfony DI guarantees that every environment variable used at least once on at least one configuration file are being using on the resulted cache file. I have two concerns:
* The exception is thrown on a dumper class and, for me, that file should not handle any DI logic
* Is that really Symfony's matter? If there is something wrong in the configuration, it should be cautch

**Comment by fefas** [comment]
> Sorry.. I pressed comment before writing the end of the message

I would love to contribute and to find a fix for this issue now reported by others developers too (the PR #23773 makes the same I tried). So, I am completely open to think about the problem and recreate the PR with new changes if you give me some direction. As @fabpot said, this exception is really annoying 😝  ...

So, I'd like to ask you: why do you believe it's not a good idea to remove this exception? How exactly this helps DX? Are there more concerns?

> I'd like also to say one more thing: I totally respect the decision of the Symfony maintainers. I always learn so much by watching talks of you. You are outstanding developers and, because of that, it's really hard to say publicly that I don't agree with some part of the code you wrote.

**Comment by fefas** [comment]
We've just found (me and @xthiago) a workaround for the issue #22561:
```yml
# app/config/database.yml

doctrine:
    dba:
        connections:
            default:
                host: "%database_host%"
                dbname: "%database_dbname%"
                user: "%database_user%"
                password: "%database_password%"
```
```php
// app/AppKernel.php

protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
{
    $this->loadEnvironmentVariables($container);

    // ...
}

protected function loadEnvironmentVariables(ContainerBuilder $container)
{
    $useTestDatabase = 'test' === $this->getEnvironment();

    if ($useTestDatabase) {
        $container->setParameter('database_host', getenv('DATABASE_TEST_HOST'));
        $container->setParameter('database_dbname', getenv('DATABASE_TEST_DBNAME'));
        // ...

        return;
    }

    $container->setParameter('database_host', getenv('DATABASE_HOST'));
    $container->setParameter('database_dbname', getenv('DATABASE_DBNAME'));
    // ...
}
```

**Comment by ousmaneNdiaye** [comment]
I got the same error in my test env. All tests were broken after defining an env variables in my config (for Heroku deployment purpose).
    
    Environment variables "ENV_VAR1" are never used. Please, check your container's configuration.

Not sure if it can helps but waiting a cleaner solution, I fix it by adding dummy parameters in my parameters.yml file. 

    /parameters.yml
    app.dummy_param1: '%env(ENV_VAR1)%'

Now I can run my tests again

**Comment by nicolas-grekas** [comment]
There is at least one false-positive case for this issue that should be fixed by #23903.
Did you mean others? I'd then need a more precise description of when it still happens.

**Comment by nicolas-grekas** [comment]
If the issue still arise, please open a new issue with a more specific description - or better: a reproducer.

**Comment by garak** [comment]
I just upgraded from eeaea83d380abd190a999b3addce784ca177ca7d to 4173f1389ec935caa34396f17a1cd32b602c7af0 and got this error :disappointed: 

`Environment variables "mailer_transport" are never used`, but my config has:

```yaml
parameters:
    env(mailer_transport): smtp

swiftmailer:
    transport: '%env(mailer_transport)%'

```

**Comment by nicolas-grekas** [comment]
did got get the error before also?
is "disable_delivery" set?
can you provide a reproducer?

**Comment by garak** [comment]
If I go back to eeaea83 there's no error.
Yes, "disable_delivery" is `true` in dev environment, but I also tried `bin/console -e=prod` and got the same error.
I'll try to provide a reproducer

**Comment by garak** [comment]
If I go back to eeaea83 there's no error.
Yes, "disable_delivery" is `true` in dev environment, but I also tried `bin/console -e=prod` and got the same error.
Edit: here is a reproducer try: https://bitbucket.org/garak/symfony-standard

**Comment by nicolas-grekas** [comment]
fixed in #24009

**Comment by renatomefi** [comment]
In my case the bundle extension unsets a value depending on another one:
```
\\ Bundle Extension load
        if ($config['api']['use_proxy'] === false) {
            $container->setParameter('api_client_proxy_uri', null);
        }
```

Since the used variables comparison are checking for the same values I get the unused variables exception, and that's really inconvenient since they still have a purpose.
What's the solution in this case?

**Comment by nicolas-grekas** [comment]
call $container->resolveEnvPlaceholders() on the config array in your DI extension, this meaning you take responsibility for dealing with env vars

**Comment by renatomefi** [comment]
@nicolas-grekas what's the solution when I don't own the bundle?

**Comment by nicolas-grekas** [comment]
Not use env vars for this specific option (not all options are meant to be compatible with enb vars)
Or submit a PR on the bundle to add support for env vars if that makes sense.
