### ISSUE TITLE
[Cache] No ability to add options in framework config

### ISSUE THREAD

**Issue by Bukashk0zzz** [symfony/symfony#23962]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

I need add some options to \Memcache client. For example add specific options for elasticache connection http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.Using.html#AutoDiscovery.Using.ModifyApp.PHP

My config look like this:

```yaml
framework:
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: 'memcached://%env(MEMCACHE_HOST)%'
```

I can't find the way how I can change client parameter in cache.adapter.memcached or add to exist needed options.

Will be great if we add option parameter. Example:

```yaml
framework:
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: 'memcached://%env(MEMCACHE_HOST)%'
        options: 
            - compression: true
            - client_mode: 'dynamic'
```

**Comment by nicolas-grekas** [comment]
this is possible via the DSN: 
`memcached://%env(MEMCACHE_HOST)%?compression=1`.
That works for any `Memcached::OPT_*` constants (but I don't what `client_mode: 'dynamic'` means)

**Comment by nicolas-grekas** [comment]
Hum, looking at the code, it may not work - which is something we missed and should be fixed. Redis allows that.

**Comment by Bukashk0zzz** [comment]
Checked code. And made tests. 

`memcached://%env(MEMCACHE_HOST)%?compression=1` - not work
Main reson in RedisTrait there are parse_url in MemcachedTrait no.

So I think this issue is bug. Also what about if I need pool of memcached servers?

```yaml
framework:
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: 
            - 'memcached://%env(MEMCACHE_HOST_1)%'
            - 'memcached://%env(MEMCACHE_HOST_2)%'
```

How I understand no way to do this?

**Comment by nicolas-grekas** [comment]
Not really a bug, but an unsupported feature yes - might be improved in 3.4 if you want to work on it.
Note that compression is enabled by default so you may not want to change this option.

For advanced setups (multi hosts), and for configuring other options in 3.3, this is perfectly possible but you need to define the client as a service, eg.:
```yaml
services:
  cache.default_memcached_provider:
    class: Memcached
    arguments: ...
```

then you could remove that "default_memcached_provider" line in your config under "framework.cache", because the "cache.default_memcached_provider" service is already the default.

**Comment by Bukashk0zzz** [comment]
Thanks for answer this helps a lot. cache.default_memcached_provider thats what I needed. 
Any way I will try to make pull request for MemcachedTrait with this unsupported query parsing feature.

**Comment by JCWolf** [comment]
@Bukashk0zzz @nicolas-grekas  I have the same issues when using Symfony with AWS. Can you show us the configuration used for Memcached because I still have issues setting this up.
For example the setting `framework.cache.app` needs a cache adapter:
```yml
framework:
    cache:
        app: app.custom_memcache_adapter
```

In order to create this adapter, I need to pass it to a MemcacheAdapter class passing it an instance of my custom Memcache client:
```yml
app.memcached_client:
   class: Memcached
   factory: 'AppBundle\Services\CustomMemcachedAdapter::createConnection' #this returns an Memcached Client
   arguments: ['memcached://%memcache_ip%:%memcache_port%']

app.memcached_adapter:
   class: Symfony\Component\Cache\Adapter\MemcachedAdapter
   arguments:
      - '@app.memcached_client'
```

When I run this I get `ype error: Argument 1 passed to Symfony\\Component\\Cache\\Adapter\\MemcachedAdapter::__construct() must be an instance of Memcached, string given` 
That string is something like `hPVpOarY8I`, probably and ID or somthing. Why is this happening? The symfony docs aren't really helping on this matter.

What I am trying to do is to add some extra options to the client using ->setOption().

**Comment by nicolas-grekas** [comment]
Sorry issue is closed, please open another one if you want.
