### ISSUE TITLE
'Cannot bind closure to scope of internal class ReflectionProperty' in KernelTestCase

### ISSUE THREAD

**Issue by stefandoorn** [symfony/symfony#24178]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Error seems to pop up in all my tests that are using kernel, error occurs when tearing down. Issue is, I can only replicate it on the setup as described in this set-up. On a different set-up it seems to pass. 

I'm not sure this is a rather useful bug report in the sense that it's hard to replicate, but maybe more people run into something similar which would lead to something useful.

Error experienced:

```
1) Tests\Unit\AppBundle\Service\ProductImageThumbnailsTest::testNoProducts
Cannot bind closure to scope of internal class ReflectionProperty

/dev/shm/sylius/cache/test/appTestDebugProjectContainer.php:36007
/builds/topjaloezieen/webshop/app/TestAppKernel.php:70
/builds/topjaloezieen/webshop/app/TestAppKernel.php:39
/builds/topjaloezieen/webshop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:194
/builds/topjaloezieen/webshop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:206
```

Test file looks like:

```
<?php

namespace Tests\Unit\AppBundle\Service;

use AppBundle\Service\ProductImageThumbnails;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Class ProductImageThumbnailsTest
 * @package Tests\Unit\AppBundle\Service
 */
class ProductImageThumbnailsTest extends KernelTestCase
{

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testNoProducts()
    {
        static::bootKernel();

        $obj = new ProductImageThumbnails(
            static::$kernel->getContainer()->get('liip_imagine.cache.manager'),
            'thumbnail'
        );

        $obj->getImages();
    }
}
```

I'm using GitLab CI with docker container php:7.1 (https://github.com/docker-library/php/blob/ae9d560db8b4a8fc4408da2b158e8594015c0fcb/7.1/Dockerfile), using the PHP version and extensions below.

PHP config: 

```
++ php -v
+ echo PHP 7.1.9 '(cli)' '(built:' Sep 8 2017 '02:43:40)' '(' NTS ')' Copyright '(c)' 1997-2017 The PHP Group Zend Engine v3.1.0, Copyright '(c)' 1998-2017 Zend Technologies with Xdebug v2.5.5, Copyright '(c)' 2002-2017, by Derick Rethans

++ php --ini
+ echo Configuration File '(php.ini)' Path: /usr/local/etc/php Loaded Configuration File: '(none)' Scan for additional .ini files in: /usr/local/etc/php/conf.d Additional .ini files parsed: /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini, /usr/local/etc/php/conf.d/docker-php-ext-exif.ini, /usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-intl.ini, /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini, /usr/local/etc/php/conf.d/docker-php-ext-zip.ini, /usr/local/etc/php/conf.d/memory_limit.ini
```

**Comment by stefandoorn** [comment]
Seems unrelated (to me) to base Symfony. Got it fixed.

**Comment by manseuk** [comment]
@stefandoorn What was the fix ? we are having the same issue

**Comment by stefandoorn** [comment]
@manseuk It had something to do with some services that shouldn't have been cleaned up between tests (kernel/http_kernel). My issue got solved by updating my Sylius base installation, so I'm not 100% sure what is the exact fix in this case.

**Comment by oenie** [comment]
@manseuk did you solve your problem way back ? Probably too long ago :)
Seeing the same during a transition from Symfony 2 over Symfony 3 to Symfony 4

**Comment by manseuk** [comment]
@oenie I honestly cannot remember how we fixed the issue - but its no longer an issue for us. Let me have a dig around commits during that time and see what changes we made

**Comment by manseuk** [comment]
I think (looking at old commit messages around the issue) that we were having issues where previous test objects we're still hanging around, so adding `\Mockery::close();` in `tearDown` seemed to resolve the issue. I seem to remember running the tests in isolation didn't show the issue whereas running as part of a suite cause the issue to surface

**Comment by oenie** [comment]
OK, thanks. I'll do a quick test to see if it could be something similar. 
I might skip Symfony 3 and go straight to S4 hoping it might solve the issue too.
Thanks for the effort !

**Comment by oenie** [comment]
Apparently, in our case, it is something during AppKernel.php shutdown method.

We have some code that implements container cleanup, which is giving me the error.
Going to dig down to see what is causing it, could be some old forked project that i need to work on.

**Comment by pmishev** [comment]
@oenie Did you find the cause of your problem? It seems exactly the same as what I'm experiencing.
On **tearDown()** I'm calling this method to try and fix memory leaks and this is what seems to cause the issue for me:
```
    /**
     * Remove all container references from all loaded services
     * Taken from https://github.com/symfony/symfony/issues/11236
     *
     * @param array $exclude
     */
    protected function cleanupContainer($exclude = ['kernel'])
    {
        $container = $this->getContainer();
        $object = new \ReflectionObject($container);
        $property = $object->getProperty('services');
        $property->setAccessible(true);

        $services = $property->getValue($container) ?: [];
        foreach ($services as $id => $service) {
            if (in_array($id, $exclude, true)) {
                continue;
            }

            $serviceObject = new \ReflectionObject($service);
            foreach ($serviceObject->getProperties() as $prop) {
                $prop->setAccessible(true);

                if ($prop->isStatic()) {
                    continue;
                }

                $prop->setValue($service, null);
            }
        }

        $property->setValue($container, null);
    }
```

I get this warning triggered somewhere in the compiled KNP paginator:
```
PHP Warning:  Cannot bind closure to scope of internal class ReflectionProperty in /cache/test_functional/Container1bkb2vz/Paginator_f262b94.php on line 143
```

**Comment by k00ni** [comment]
I get the same error triggered when i try to clone a Doctrine entity using [myclabs/DeepCopy](https://github.com/myclabs/DeepCopy) running the `test` environment. 

It gets thrown by a generated class named `EntityManager_9a5be93` from `var/cache/test`. The class head looks like:

```php
class EntityManager_9a5be93 
    extends \Doctrine\ORM\EntityManager 
    implements \ProxyManager\Proxy\VirtualProxyInterface
{
    // ...
}
```

The source is in the `__get` function:

```php
public function & __get($name)
    {
        $this->initializer8ff61 && ($this->initializer8ff61->__invoke($valueHolder3f19f, $this, '__get', ['name' => $name], $this->initializer8ff61) || 1) && $this->valueHolder3f19f = $valueHolder3f19f;
        if (isset(self::$publicProperties4471d[$name])) {
            return $this->valueHolder3f19f->$name;
        }
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder3f19f;
            $backtrace = debug_backtrace(false);
            trigger_error(
                sprintf(
                    'Undefined property: %s::$%s in %s on line %s',
                    get_parent_class($this),
                    $name,
                    $backtrace[0]['file'],
                    $backtrace[0]['line']
                ),
                \E_USER_NOTICE
            );
            return $targetObject->$name;
            return;
        }
        $targetObject = $this->valueHolder3f19f;
        $accessor = function & () use ($targetObject, $name) {
            return $targetObject->$name;
        };
        $backtrace = debug_backtrace(true);
        $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();

        // TRIGGERS THE ERROR
        $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));

        $returnValue = & $accessor();
        return $returnValue;
    }
```

Does someone has this too? If so, i could make a new issue for further discussion.
