### ISSUE TITLE
[TwigBridge] FormExtension/TwigRenderer/FormRenderer BC break on 3.4

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#24533]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.x-dev 0f5e38c

I just tried upgrading one of my apps from 3.3.10 to symfony 3.4.x-dev and stumbled across this issue in combination with Sonata admin: https://github.com/sonata-project/SonataAdminBundle/issues/4652

As far as I understand the TwigRenderer was deprecated and is now actually an instance of FormRenderer?

Which breaks code like this (which is done in a similar way on Sonata admin):

```php
$twig = $this->get('twig');

$twig
    ->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')
    ->initRuntime($twig);

$twig
    ->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')
    ->renderer;
```

Or this:

```php
$twig = $this->get('twig');

$twig
    ->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')
    ->renderer;

$twig
    ->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')
    ->initRuntime($twig);
```

As this check is not true anymore https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bridge/Twig/Extension/FormExtension.php#L55

And this method `setEnvironment` does not exist on `FormRenderer`: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bridge/Twig/Extension/FormExtension.php#L122

**Comment by mricherzhagen** [comment]
I think this BC-break was *not* fixed in the released 3.4 version. I'm getting a 
```
Twig_Error_Runtime
Unable to load the "Symfony\Component\Form\FormRenderer" runtime.
```
After updating my dependencies.

Probably also the reason, why sonata-project/SonataAdminBundle#4762 has a separate BC-Layer-Fix?

Can we get a proper fix in 3.4.1?

**Comment by dmaicher** [comment]
@mricherzhagen I also have some concerns about that issue and am not 100% sure its fixed for all possible use cases out there. 

See https://github.com/symfony/symfony/pull/24535#issuecomment-344596586

If you still experience issues (not related to silex) then please open a new issue :wink:

**Comment by mricherzhagen** [comment]
I only use Silex at the moment, but i don't think this issue is related to silex, because @jordisala1991had to write a fix for the SonataAdminBundle which is Symfony and not Silex.

I think the twig cache might also play some role in why this is a little weird to debug. I had to clear it manually in order to get an effect.

**Comment by sproctor** [comment]
I am still experiencing this issue with Symfony 3.4.2, but not with 3.3. I used the documentation from https://symfony.com/doc/3.4/components/form.html to create a simple test.

https://gist.github.com/sproctor/7a5d5a322cc89b6839cf4d414822c316

**Comment by dmaicher** [comment]
@sproctor true! Unfortunately the documentation is outdated :cry: 

I will create a PR to update it accordingly.

With this it works?

```php
$twig->addRuntimeLoader(new \Twig_FactoryRuntimeLoader(array(
    \Symfony\Component\Form\FormRenderer::class => function () use ($formEngine, $csrfManager) {
        return new \Symfony\Component\Form\FormRenderer($formEngine, $csrfManager);
    },
)));

**Comment by sproctor** [comment]
@dmaicher That did it! Thank you!
