### ISSUE TITLE
[DI] Prevent an infinite loop when using env vars in service names

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#25123]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.11

Related to this thread: https://github.com/symfony/symfony/pull/24673

With this commit it's not possible anymore to use an environment parameter as name of in_memory providers. It's not really a big problem but it's a BC break when upgrading from 3.3.10 to 3.3.11. Is it wanted?

Example:

```yml
parameters:
    admin_username: '%env(ADMIN_USERNAME)%'
    admin_password: '%env(ADMIN_PASSWORD)%'

providers:
    in_memory:
        memory:
            users:
                - { name: "%admin_username%", password: "%admin_password%", roles: 'ADMIN' }
```

Lead to this exception:
```
[Symfony\Component\DependencyInjection\Exception\EnvParameterException]        
    A service name ("security.user.provider.concrete.in_memory_%env(ADMIN_USER    
    NAME)%") cannot contain dynamic values.  
```

**Comment by nicolas-grekas** [comment]
How did it work previously? A service name cannot be dynamic, so maybe it just didn't work as you expected, and you didn't notice? That's what we thought when adding the exception: this will tell ppl they did a misconfig.

**Comment by raziel057** [comment]
I can tell you it worked because I use JWT to authenticate real users (stored in my application) and a specific digest authentication to access the API documentation. I used a different ``username`` and ``password`` in the different environment we have (qa, uat, prod) and it worked as expected taking the defined ENV parameters. I think the service name is not directly used for authentication in ``in_memory`` provider. So the service name was ``security.user.provider.concrete.in_memory_%env(ADMIN_USER    
    NAME)%`` but the name was resolved at authentication level.

```yml
security:
    firewalls:
        api:
            pattern:   ^/api
            stateless: true
            entry_point: app.digest_entry_point
            http_digest:
                provider: in_memory
                realm:    "%digest_realm%"
                secret:   "%kernel.secret%"
            guard:
                provider: default
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

services:

    app.digest_entry_point:
        class: Symfony\Component\Security\Http\EntryPoint\DigestAuthenticationEntryPoint
        arguments:
            - '%digest_realm%'
            - '%kernel.secret%'
```

**Comment by stof** [comment]
Can you put the compiled container you had with Symfony 3.3.10 in a gist so that we can understand how this ever worked ? This was **never** supposed to work.

and please also give the corresponding configuration. There is no usage of `%env(ADMIN_USER NAME)%` in the code snippet you are giving above.

**Comment by raziel057** [comment]
@stof I can try to give you the compiled container tomorrow. Is it supposed to work with a parameter which is not an env? Currently it works also in Symfony 3.3.13. 

For example:

```yml
parameters:
    admin_username: 'admin'
```

The message have been cut in my terminal. The service real name is "security.user.provider.concrete.in_memory_%env(ADMIN_USERNAME)%".

**Comment by raziel057** [comment]
With Symfony 3.3.10, using env parameters for name and password, in the compiled container ``var/cache/dev/appDevDebugProjectContainer.php`` we have the following method:

```php
/**
     * Gets the private 'security.user.provider.concrete.in_memory' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider
     */
    protected function getSecurity_User_Provider_Concrete_InMemoryService()
    {
        $this->services['security.user.provider.concrete.in_memory'] = $instance = new \Symfony\Component\Security\Core\User\InMemoryUserProvider();

        $instance->createUser(new \Symfony\Component\Security\Core\User\User($this->getEnv('ADMIN_PASSWORD'), $this->getEnv('ADMIN_PASSWORD'), array(0 => 'ROLE_ROOT')));

        return $instance;
    }
```

**Comment by stof** [comment]
@raziel057 I still does not have a code snippet showing where this `%env(ADMIN_USERNAME)%` is used in a place related to the in memory provider. What I need is a way to reproduce the issue. I'm still in guessing land for now, as I still don't have the config triggering the issue.

**Comment by nicolas-grekas** [comment]
@stof in fact it does: the service has been inlined, so it's actual name doesn't matter anymore at this stage. I'm trying to find a way to deal with these situations.

**Comment by stof** [comment]
@nicolas-grekas The solution would be to avoid using the env placeholder in the generated service name here. We just want to have a different id generated for each env placeholder (to avoid reusing the service). We may use a hash of the placeholder instead of the placeholder when generating the service id.

**Comment by nicolas-grekas** [comment]
See #25146
