### ISSUE TITLE
Regression in Symfony Yaml Parser

### ISSUE THREAD

**Issue by romainneutron** [symfony/symfony#25329]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.14, 3.4.1 and 4.0.1

Hi,

Since the latest 3.3, I experiment a regression in Symfony Yaml, here's a reproducer:

```
<?php
require __DIR__.'/vendor/autoload.php';

$yaml = <<<EOYAML
root:
  - key1: "bim"
    # A comment
    key2: "boum"

EOYAML;

$parser = new Symfony\Component\Yaml\Parser();
dump($parser->parse($yaml));
```

expected outpout:
```
array:1 [
  "root" => array:1 [
    0 => array:2 [
      "key1" => "bim"
      "key2" => "boum"
    ]
  ]
]
```

actual output:
```
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 4 (near "  key2: "boum""). in /Users/neutron/Documents/workspace/symfony/src/Symfony/Component/Yaml/Parser.php:426
Stack trace:
#0 /Users/neutron/Documents/workspace/symfony/src/Symfony/Component/Yaml/Parser.php(465): Symfony\Component\Yaml\Parser->doParse('- key1: "bim"\n ...', 0)
#1 /Users/neutron/Documents/workspace/symfony/src/Symfony/Component/Yaml/Parser.php(315): Symfony\Component\Yaml\Parser->parseBlock(1, '- key1: "bim"\n ...', 0)
#2 /Users/neutron/Documents/workspace/symfony/src/Symfony/Component/Yaml/Parser.php(95): Symfony\Component\Yaml\Parser->doParse('root:\n  - key1:...', 0)
#3 /Users/neutron/Documents/workspace/symfony/test.php(15): Symfony\Component\Yaml\Parser->parse('root:\n  - key1:...')
#4 {main}
  thrown in /Users/neutron/Documents/workspace/symfony/src/Symfony/Component/Yaml/Parser.php on line 426
```

I've tested against all latest versions, only version 3.3.14, 3.4.1 and 4.0.1 are affected

**Comment by alcaeus** [comment]
Can confirm - hit the same regression in 3.4.1 this morning.

**Comment by sunpietro** [comment]
I have the same issue.

**Comment by xabbuh** [comment]
Oh no :( That's for sure caused by #25241.

**Comment by Strate** [comment]
Almost same, but a bit different:
```yaml
array:
  -
    key: value
```

parsed as string, not as array

**Comment by emodric** [comment]
Experienced this one too with the following:

```yaml
        array:
            - key:
                # comment
                value: [1, 2, 3]
```

**Comment by xabbuh** [comment]
Thanks for the examples. I am currently working on a fix. Sorry for the inconvenience.

**Comment by alcaeus** [comment]
@xabbuh not trying to rush you, but do you have a rough idea when a fix might be available?

**Comment by xabbuh** [comment]
@alcaeus You can find the current state of my fix at https://github.com/xabbuh/symfony/tree/issue-25329. I appreciate any feedback, but I still have to add some more tests and think about some edge cases. I want to be careful here to not introduce other new issues.

**Comment by alcaeus** [comment]
I’ll take a look later on, thanks!

**Comment by xabbuh** [comment]
Thanks, and of course everyone else involved in this thread: please test your applications as well.

**Comment by mcfedr** [comment]
If it helps, another example that has broken:

```yaml
root:
    app_device_profile.command.web_filter_update:
        class: App\Device\ProfileBundle\Command\WebFilterUpdateCommand
        arguments:
            -
#                - '@app_device_profile.ut_capitole_downloader'
#                - '@App\Device\ProfileBundle\WebFilter\UtCapitoleHttpDownloader'
                - '@app_device_profile.squid_blacklist_downloader'
#                - '@app_device_profile.url_blacklist_downloader'
            - '@app_device_profile.grouper_runner'
            - '@logger'
        tags:
            - { name: console.command }
```

```
Array
(
    [root] => Array
        (
            [app_device_profile.command.web_filter_update] => Array
                (
                    [class] => App\Device\ProfileBundle\Command\WebFilterUpdateCommand
                    [arguments] => Array
                        (
                            [0] => - '@app_device_profile.squid_blacklist_downloader'
                        )

                    [tags] => Array
                        (
                            [0] => Array
                                (
                                    [name] => console.command
                                )

                        )

                )

        )

)
```

**Comment by xabbuh** [comment]
@mcfedr Would that example also be fixed by the patch I referenced in https://github.com/symfony/symfony/issues/25329#issuecomment-349964566?

**Comment by mcfedr** [comment]
@xabbuh Yes its fixed.

**Comment by xabbuh** [comment]
Can everyone affected by the described issue confirm that #25389 fixes it?

**Comment by emodric** [comment]
@xabbuh Fixed it for me! :+1:

**Comment by enricog84** [comment]
@xabbuh 
I still have an issue when I have a non-indented empty line e.g. like this YAML:

```
WM\AuthBundle\Model\AbstractUser:
    properties:
        firstName:

            - Type: 
                type: string
```

**Comment by xabbuh** [comment]
@enricog84 Sorry for that. I am working on this as part of #25405.

**Comment by xabbuh** [comment]
@enricog84 Can you please test #25438?

**Comment by enricog84** [comment]
@xabbuh  Yes, with the changes it works for me. Thanks!

**Comment by xabbuh** [comment]
Thanks you for confirming.
