### ISSUE TITLE
You have requested a non-existent parameter "container.build_id".

### ISSUE THREAD

**Issue by mcnilz** [symfony/symfony#25695]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.3

since #25671 JMSSecurityExtraBundle is broken because a service is used at compile time. Other libraries could be broken too.

```
In ParameterBag.php line 102:
                                                                                
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "container.build_id".             
                                                                                
Exception trace:
 Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php:57
 Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:133
 Symfony\Component\DependencyInjection\Container->getParameter() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1243
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 [...]
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:563
 Symfony\Component\DependencyInjection\ContainerBuilder->get() at /app/vendor/jms/metadata/src/Metadata/Driver/LazyLoadingDriver.php:23
 Metadata\Driver\LazyLoadingDriver->loadMetadataForClass() at /app/vendor/jms/metadata/src/Metadata/MetadataFactory.php:103
 Metadata\MetadataFactory->getMetadataForClass() at /app/vendor/jms/security-extra-bundle/Security/Authorization/Interception/SecurityPointcut.php:84
 JMS\SecurityExtraBundle\Security\Authorization\Interception\SecurityPointcut->matchesMethod() at /app/vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:149
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() at /app/vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:65
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:634
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
 Symfony\Component\HttpKernel\Kernel->boot() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/bin/console:28
```

**Comment by nicolas-grekas** [comment]
Fixed by #25696

**Comment by nicolas-grekas** [comment]
Note that this exception can also be triggered when using `matthiasnoback/symfony-service-definition-validator`.
But this is not something that is unsupported on Symfony's side: such validation logic basically breaks the separation of runtime vs compile-time, by evaluating parameters/expressions/services (in expressions) at compile time. You should just remove them.

**Comment by pzienowicz** [comment]
Any workaround until next release?

**Comment by ajtis** [comment]
@fabpot can You please merge it into **symfony:2.4**

**Comment by xabbuh** [comment]
@ajtis that's done now

**Comment by ajtis** [comment]
Thank You @xabbuh

**Comment by JoydS** [comment]
I still have the error. 
I see a call in https://github.com/symfony/framework-bundle/blob/3.4/DependencyInjection/FrameworkExtension.php#L1632

**Comment by ajtis** [comment]
@JoydS it is not related to part of code You have pointed.

Those changes fixes bug.
https://github.com/symfony/symfony/commit/f66f9a7b377d8eca20b2ba63e42446df10174877

**Comment by blackarcanis** [comment]
@ajtis I still have the error too, this fix change nothing to me :/

**Comment by JoydS** [comment]
From my point, the problem come from the declaration of this service : cache.adapter.system
During the initialisation of this service, arguments are : 
  #arguments: array:5 [
    0 => "DRuFIO3LLC"
    1 => 0
    2 => Symfony\Component\DependencyInjection\Parameter {#2606
      -id: "container.build_id"
    }
    3 => ".../meero/app/cache/dev/pools"
    4 => Symfony\Component\DependencyInjection\Reference {#1087
      -id: "monolog.logger.cache"
      -invalidBehavior: 3
    }
  ]

**Comment by nicolas-grekas** [comment]
to anyone still having this issue, please provide a stack trace of the error (similar as above)

**Comment by JoydS** [comment]
In ParameterBag.php line 102:
                                                                                
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "container.build_id".


Exception trace:
 Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php:57
 Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:133
 Symfony\Component\DependencyInjection\Container->getParameter() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1246
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1244
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1242
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1244
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1244
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1242
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1244
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1199
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1112
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:563
 Symfony\Component\DependencyInjection\ContainerBuilder->get() at /vendor/jms/metadata/src/Metadata/Driver/LazyLoadingDriver.php:23
 Metadata\Driver\LazyLoadingDriver->loadMetadataForClass() at /vendor/jms/metadata/src/Metadata/MetadataFactory.php:103
 Metadata\MetadataFactory->getMetadataForClass() at /vendor/jms/security-extra-bundle/Security/Authorization/Interception/SecurityPointcut.php:84
 JMS\SecurityExtraBundle\Security\Authorization\Interception\SecurityPointcut->matchesMethod() at /vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:149
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() at /vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:65
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:634
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
 Symfony\Component\HttpKernel\Kernel->boot() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/console:27

**Comment by nicolas-grekas** [comment]
@JoydS thanks. This issue with `JMS\AopBundle` should have been fixed by #25696. Please provide a reproducer if not for you.

**Comment by stof** [comment]
@nicolas-grekas but this fix is not released yet, so it requires running the dev version of Symfony to test it (which most people don't do).

**Comment by dspiegel** [comment]
@stof @nicolas-grekas  So this last symfony/symfony change has broke symfony/symfony 3.4 LTS. Problem did not exist in sysmfony/symfony 3.3 (minor release). I did no other changes to my composer file other than symfony/symfony 3.3 to symfony/symfony 3.4. That is a [BC] break for a minor version. You suggest to run dev version for a LTS release seems very odd!! I had to role back to Symfony 3.3. When is the LTS symfony/symfony 3.4 going to have this change rolled back or available as stable? This should be a priority since it is [BC] break of minor version. If not, tell me what I'm missing.

Thanks, Dave

**Comment by hellostudios** [comment]
@nicolas-grekas Still getting this same issue today on a fresh install of both symfony v3.4.3. Has this fix been realised to production or just dev version?

**Comment by nicolas-grekas** [comment]
The fix will be part of the next release, by the end of the month.

**Comment by bds-viktoras** [comment]
@nicolas-grekas @stof 

Shouldn't this fix be provided as a hotfix, as this issue essentially breaks down current LTS version? As in addition to what @dspiegel said, it breaks [BC] within PATCH release, not even MINOR. 

Or am I missing something as well with versioning?

**Comment by nicolas-grekas** [comment]
all bugs fit this description @bds-viktoras , this one is no specific

**Comment by Reaper88** [comment]
mine seems to come from doctrine ORM

> 

in ParameterBag.php (line 102)
--
at ParameterBag->get('container.build_id')in EnvPlaceholderParameterBag.php (line 57)
at EnvPlaceholderParameterBag->get('container.build_id')in Container.php (line 133)
at Container->getParameter('container.build_id')in ContainerBuilder.php (line 1243)
at ContainerBuilder->doResolveServices(object(Parameter), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array('1IEmKqbe6p', 0, object(Parameter), '/home/devcmsful/etc/cache/dev/pools', object(Reference)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Definition)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)), 'cache.annotations')in ContainerBuilder.php (line 598)
at ContainerBuilder->doGet('cache.annotations', 1, array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1239)
at ContainerBuilder->doResolveServices(object(Reference), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array('/home/devcmsful/etc/cache/dev/annotations.php', object(Reference)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Definition)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(AnnotationReader), object(Definition), true), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)), 'annotation_reader')in ContainerBuilder.php (line 598)
at ContainerBuilder->doGet('annotation_reader', 1, array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1239)
at ContainerBuilder->doResolveServices(object(Reference), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Reference), array('/home/devcmsful/cmsful/Entity')), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Definition), 'CMS\\Entity'), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1571)
at ContainerBuilder->callMethod(object(MappingDriverChain), array('addDriver', array(object(Definition), 'CMS\\Entity')), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1155)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Definition)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1571)
at ContainerBuilder->callMethod(object(Configuration), array('setMetadataDriverImpl', array(object(Definition))), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1155)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1241)
at ContainerBuilder->doResolveServices(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1196)
at ContainerBuilder->doResolveServices(array(object(Connection), object(Definition)), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)))in ContainerBuilder.php (line 1109)
at ContainerBuilder->createService(object(Definition), array('doctrine.orm.default_entity_manager' => object(Generated7b15ccbe7d96537d04f3c4d9206e6931), '00000000389958090000000053c09173' => object(Configuration), '000000003899580f0000000053c09173' => object(LoggerChain), 'monolog.logger.doctrine' => object(Logger), 'debug.log_processor' => object(DebugProcessor), 'monolog.handler.main' => object(StreamHandler), 'monolog.processor.psr_log_message' => object(PsrLogMessageProcessor), 'debug.stopwatch' => object(Stopwatch), '0000000038995f920000000053c09173' => object(DbalLogger), 'doctrine.dbal.logger.profiling.default' => object(DebugStack), '000000003899580c0000000053c09173' => object(ContainerAwareEventManager), 'doctrine.orm.default_listeners.attach_entity_listeners' => object(AttachEntityListenersListener), 'doctrine.dbal.connection_factory' => object(ConnectionFactory), 'doctrine.dbal.default_connection' => object(Connection), '00000000389958020000000053c09173' => object(Configuration), 'doctrine_cache.providers.doctrine.orm.default_metadata_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_query_cache' => object(ArrayCache), 'doctrine_cache.providers.doctrine.orm.default_result_cache' => object(ArrayCache), '0000000038995fbb0000000053c09173' => object(MappingDriverChain), 'annotations.reader' => object(AnnotationReader), '000000003899488c0000000053c09173' => object(AnnotationRegistry)), 'doctrine.orm.default_entity_manager', false)in ContainerBuilder.php (line 1095)
at ContainerBuilder->Symfony\Component\DependencyInjection\{closure}()
at call_user_func(object(Closure))in RuntimeInstantiator.php (line 54)
at RuntimeInstantiator->Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\{closure}(null, object(Generated7b15ccbe7d96537d04f3c4d9206e6931), 'getConnection', array(), object(Closure))in EvaluatingGeneratorStrategy.php(68) : eval()'d code (line 30)
at Closure->__invoke(null, object(Generated7b15ccbe7d96537d04f3c4d9206e6931), 'getConnection', array(), object(Closure))in EvaluatingGeneratorStrategy.php(68) : eval()'d code (line 30)
at Generated7b15ccbe7d96537d04f3c4d9206e6931->getConnection()in ConfigPass.php (line 23)
at ConfigPass->process(object(ContainerBuilder))in Compiler.php (line 141)
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php (line 753)
at ContainerBuilder->compile()in Kernel.php (line 634)
at Kernel->initializeContainer()in Kernel.php (line 137)
at Kernel->boot()in Kernel.php (line 197)
at Kernel->handle(object(Request))in app_dev.php (line 30)

**Comment by imajim** [comment]
yop !

for me i have removed "jms security" in AppKernel.php, i don't use  it yet : 
` new JMS\AopBundle\JMSAopBundle(),
   new JMS\SecurityExtraBundle\JMSSecurityExtraBundle(),
    new JMS\DiExtraBundle\JMSDiExtraBundle($this),`

And i've no more errors

**Comment by blackarcanis** [comment]
Version 3.4.4 => https://symfony.com/blog/symfony-3-4-4-released
Fixed the issue, good for me !

**Comment by imajim** [comment]
@matteomoretti Maybe a conflict with another library. Take a look my post on top

**Comment by videni** [comment]
I also have this issue today, please check [non-existent parameter "container.build_id" ](https://github.com/rollerworks/PasswordStrengthBundle/issues/98),  at first,  I thought 
 `matthiasnoback/symfony-service-definition-validator ` is confict with overblog/GraphQLBundle, howver they are not.
