### ISSUE TITLE
Debug toolbar JS error: `tbody.rows.count is not a function`

### ISSUE THREAD

**Issue by simshaun** [symfony/symfony#26364]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.5

Getting JS errors in console in both Firefox and Chrome, caused by https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L125

Error:

```
TypeError: tbody.rows.count is not a function
```

**Comment by Ousret** [comment]
[WebProfilerBundle] add a way to limit ajax request #25557 

It does break all my apps when I try integrate ajax addons that require to listen to requests.

```sh
TypeError: tbody.rows.count is not a function. (In 'tbody.rows.count()', 'tbody.rows.count' is undefined)
in startAjaxRequest
 ```

**Comment by dmaicher** [comment]
Ping @simperfit

**Comment by xkobal** [comment]
it works with `var nbOfAjaxRequest = tbody.rows.length;`

**Comment by sgehrig** [comment]
@nicolas-grekas Will there be a quick 3.4.6 release with this fix?

**Comment by nicolas-grekas** [comment]
We don't do quick fixes usually...

**Comment by sgehrig** [comment]
No problem with that. Just asked because if there'll be no quick release we'll have to generally disable the dev toolbar until there'll be a release.

**Comment by althaus** [comment]
Just updated and felt into this trap. Don't need a quick update. A soon update'd be enough. ❤️

**Comment by Simperfit** [comment]
Sorry for this, I feel bad about it since I tested it, maybe I've changed it at some point...

**Comment by silentiumtempus** [comment]
What's the workaround to get the toolbar working?
Is there any downgrade solution ?

**Comment by sgehrig** [comment]
@silentiumtempus You can always downgrade to 3.4.4. We just disabled the developer toolbar in our `config_dev.yml`

```
web_profiler:
    toolbar: false
```

This removes just the toolbar but keeps the profiler itself working.

**Comment by stof** [comment]
@nicolas-grekas having the debug toolbar broken during one month is not a good DX though.

**Comment by Ousret** [comment]
Just, guys, update your vendors manually for now. One line has to be changed, won't hurt. ^^

**Comment by silentiumtempus** [comment]
@sgehrig Downgrade to 3.4.4 doesn't help with Flex.

Looks like the "vendor" edit is the only way.

**Comment by nicolas-grekas** [comment]
> Downgrade to 3.4.4 doesn't help with Flex.

What do you mean? With Flex, just require symfony/web-server-bundle 3.4.4 (or 4.0.4 depending on your major version)

**Comment by stof** [comment]
@Ousret updating the vendors manually does not work if you don't commit them.

**Comment by Ousret** [comment]
I know, but this is about dev and not prod. This would work for standalone developper @stof

**Comment by silentiumtempus** [comment]
@nicolas-grekas I replaced "^3.4" with "=3.4.4" for all symfony/* entries on my composer.json file and it's still installing bugged profiler version.

**Comment by nicolas-grekas** [comment]
@silentiumtempus you don't need to change any entry. Just add a new one in require-dev: "symfony/web-server-bundle": "3.4.4"

**Comment by nicolas-grekas** [comment]
Actually if you use `symfony/profiler-pack`, you may need to remove it, and "unpack" it (ie explicitly list its entries in your own composer.jsonà

**Comment by silentiumtempus** [comment]
@nicolas-grekas Thanks for the advice, this solves the problem for Symfony 3.4:

1) composer unpack profiler
2) replace symfony/web-profiler-bundle version with "=3.4.4"
3) remove vendor/* contents
4) composer install

This way I kept other symfony components updated to 3.4.5.

**Comment by imiroslavov** [comment]
Here is a quick and dirty workaround for those who are too impatient or not willing to downgrade (tested on 4.0.5).

1. Unzip the following file in Your project's root directory: [profiler.patch.zip](https://github.com/symfony/symfony/files/1775007/profiler.patch.zip)
2. Add the following code to `composer.json`
 `"post-install-cmd": [ "patch -p0 -N < profiler.patch" ],`

**Comment by tristanbes** [comment]
> It does break all my apps with ajax addons that require to listen to requests.

Yeah, it seems to be the most annoying thing happening to me too. Downgraded in order to wait for a new release

**Comment by pyatnitsev** [comment]
@nicolas-grekas, thanks you! Downgrate for 3.4.4 works for me

**Comment by yura3d** [comment]
I've resolved this issue on my site by editing **vendor/symfony/web-profiler-bundle/Resources/views/Profiler/base_js.html.twig** file, in which this line:
`var nbOfAjaxRequest = tbody.rows.count();`
has been changed to:
`var nbOfAjaxRequest = tbody.rows.length;`
After that the web-profiler and AJAX queries resumed working. I think the fix update is coming soon, and small editing for now is much better than downgrade to previous versions.

**Comment by phpeek** [comment]
I can see this issue is fixed. Any ETA on release ?

My CI is doing `composer validate --strict` and doesn't like me if I use strict version in `composer.json` to keep `Symfony`@`3.4.4` :(

**Comment by StevioStudio** [comment]
I changed manually `var nbOfAjaxRequest = tbody.rows.count();` to `var nbOfAjaxRequest = tbody.rows.length` like the rest of the dev team and it's working. Any ETA on release?

**Comment by emodric** [comment]
@phpeek Add a conflict to `symfony/symfony` v3.4.5, that should take care of `composer validate --strict` :)

**Comment by PapsOu** [comment]
If you cannot wait for the release of SF 3.4.6, you can still set the wdt configuration as that :
```yaml
# app/config/config_dev.yml

web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths: '.*' # <= This disable the ajax logging
```

**Comment by alexandre-le-borgne** [comment]
Problem still present for symfony 4.0.5.
In my case, the problem only occurs when the page is loaded into an iframe.

**Comment by yura3d** [comment]
@alexandre-le-borgne, 4.0.6 is already available with fix: http://symfony.com/blog/symfony-4-0-6-released

**Comment by TerjeBr** [comment]
This is now fixed in new symfony release:
http://symfony.com/blog/symfony-3-4-6-released
