### ISSUE TITLE
Esi cache broken ? (started session / private response)

### ISSUE THREAD

**Issue by EmmanuelVella** [symfony/symfony#26769]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.4.6

Hello,

I just finished upgrading from Symfony 2.8 to 3.4.6, and my http cache is broken when using `AppCache` (without debug).

It seems that since [this PR](https://github.com/symfony/symfony/pull/25583), when the session is started, the response cache is set to private, which is fine.

But now when I go to a page where session is started and where I do `render_esi(controller('MyBundle:Controller:action'))`, http cache is not working as before, because subrequests responses are made private even if I don't start / use the session.

**Comment by stokjes** [comment]
Correct me if i'm wrong but it seems the problem relies to the `AbstractSessionListener:: onKernelResponse`. My first thought was why are we setting default cache-control headers and overwriting ones set on every master request? The thing that confuses me the most is that it seems obvious to me that every master request is already started here and available.

**Comment by EmmanuelVella** [comment]
@stokjes Yes, before symfony 4 this code was in ``SaveSessionListener`` class, then it was moved to `AbstractSessionListener` (see https://github.com/symfony/http-kernel/commit/6622fe25afe6a2c594189cd72ab83c49014b57df#diff-db3c5d9b0dc8cbb67671806266bef598)

I understand why the response is not cached if the session is started (which is the case if you use the firewall) ; however I don't know how to disable the firewall on the esi actions, as they have not route (they are called like this : `render_esi(controller('MyBundle:Controller:action'))`)

**Comment by stokjes** [comment]
What if you use the firewall on the whole domain like: `^/`, but not every response is user specific. Our varnish caching stopped working after the upgrade to Symfony 3.4. Even when explicitly 
setting caching headers on the response, those are overwritten by the listener.

For you shouldn't the `controller()` specific call in the Twig template initiate a sub-request which the listener should ignore because it isn't a master request?

**Comment by nicolas-grekas** [comment]
Fixed by #27467 (please report back if not.)

**Comment by nicolas-grekas** [comment]
Can you provide a simple reproducer, ie a repo we could clone to experience the issue?

**Comment by EmmanuelVella** [comment]
I did it in a previous comment ;) Let me repeat it here : 

https://github.com/EmmanuelVella/symfony

You can use docker to bootstrap it :
docker build . -t symfony
docker run --rm -v "$PWD":/var/www/html -p 8000:8000 -d --name symfony symfony
docker exec symfony composer install

Then go to http://localhost:8000/app.php

**Comment by EmmanuelVella** [comment]
@nicolas-grekas FYI, still not working with latest sf 3.4 update !

**Comment by nicolas-grekas** [comment]
> It seems that the firewall causes the session to start, and the response is then marked as private. Does it means I need to exclude all my esi actions from the firewall ?

I checked out your app to reproduce and indeed it cannot cache, because as you spotted, the firewall is used on fragments, which uses the session, which makes the response uncacheable.

Would there be any downside to disabling the security on `/_fragment` URLs by default in https://github.com/symfony/recipes/blob/master/symfony/security-bundle/3.3/config/packages/security.yaml?

**Comment by EmmanuelVella** [comment]
Thank you so much for taking time to test it. Yeah I already tried this solution, and it works, but it felt a bit hacky.. so I wanted to be sure that this behavior was normal.

So currently there is no other way to disable security on a controller (with no route) called like this `render_esi(controller('MyBundle:Controller:action')))` ?

**Comment by nicolas-grekas** [comment]
I don't know security well myself, I'd need someone else to answer this...

**Comment by EmmanuelVella** [comment]
Ok ;) Do you know someone who could help ?

**Comment by nicolas-grekas** [comment]
Let's ask on https://github.com/symfony/recipes/pull/424 :)

**Comment by EmmanuelVella** [comment]
👍

**Comment by EmmanuelVella** [comment]
@nicolas-grekas I continue [this discussion](https://github.com/symfony/symfony/pull/27817#issuecomment-402145427) here to not pollute your PR.

I'm sorry but I still don't get how to disable the firewall on controller called like this (with no route) : `render_esi(controller('MyBundle:Controller:action')))`, without the new `unauthenticated` mode.

Could you please be more explicit ?

**Comment by nicolas-grekas** [comment]
Exactly like done here: https://github.com/symfony/recipes/pull/424/files
This disabled security on ESI fragments, meaning non anonymous token will be created for you.

**Comment by EmmanuelVella** [comment]
Ok, so I will do this. Thank you very much for your help ! 👍
