### ISSUE TITLE
symfony messenger memory

### ISSUE THREAD

**Issue by konradja100** [symfony/symfony#28350]
Hi, i'm using symfony 4.1, messenger with RabbitMQ, and i have some problems with allocated memory - it keeps growing with every consumed message, slowing down whole proccess. 

![screenshot_6](https://user-images.githubusercontent.com/28842587/45015562-6d10e300-b022-11e8-84a9-cef25a51b8b6.png)

When i use memory_get_usage() function, it shows that on every message consumed something stay in memory:
![screenshot_7](https://user-images.githubusercontent.com/28842587/45015682-b6f9c900-b022-11e8-886a-7c76cc8d5e6f.png)

So i've tried to clear EntityMenager with this:

```
$this->em->clear();
```
but it has no effect, also I found a way to do this by setting sql logger to null:
```
$this->em->getConnection()->getConfiguration()->setSQLLogger(null);
```

but it helps releasing memory only by half. So anyone has struggled with this issue? Is this caused by doctrine, cache or something else?

**Comment by konradja100** [comment]
yes, on production performance is even worst.

**Comment by Koc** [comment]
@konradja100 try using https://github.com/LongRunning/LongRunning for releasing memory

**Comment by konradja100** [comment]
Any ideas how to use it in symfony 4.1? Service long_running.delegating_cleaner is private.

**Comment by konradja100** [comment]
Ok, so this problem must me related to symfony/messenger or symfony/amqp-pack which i'm using also. I've switched off my logic, and leave only consumming messages by messanger itself - and I get infinite memory leak. Used memory is increasing endless. This is my MessageHandler:

```
<?php

namespace App\MessageHandler;
use App\Message\TrackerEventMessage;

class TrackerEventHandler
{
    public function __construct()
    {
    }

    public function __invoke(TrackerEventMessage $message)
    {
        echo memory_get_usage().PHP_EOL;
    }
}
```

and my configuration:
```
framework:
    messenger:
        transports:
               event: 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASS)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%/%2f/event'

      routing:
           'App\Message\TrackerEventMessage': event

```

So there is no overriding or overloading any part of this two symfony packages, everything is set up by default configuration, and I get this issue, any ideas? I don't know what is kept in memory, or where/how to find it.

**Comment by konradja100** [comment]
I've created an empty project with this two packages, you can reproduce this issue:
https://github.com/konradja100/rabbit

So what i'm missing here? Messenger is not clearing messeges from memory?

**Comment by iltar** [comment]
Make sure there's not a monolog logger with an in_memory log/a logger that processes its contents on kernel shutdown (or CLI variant).

**Comment by konradja100** [comment]
Ok, so I play along with monolog, i've changed my configuration to non-buffering handler - "stream" as long as expected behaviour of finger_crossed is to store log entries in memory, i've also tried this configuration with setting buffer_size to limited value:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size:  30
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
```
and nothing has changed.
 
You can notice that in prod env profiler is disabled, so it shouldn't store anything in memory.

Running worker with --no-debug flag isn't working either.

**Comment by pierredup** [comment]
I opened #28420 to remove some extra overhead from the profiler and to discuss what can be optimised

**Comment by nicolas-grekas** [comment]
@konradja100 can you hint us about the number and the size of messages you're creating?

**Comment by sroze** [comment]
> I tested the patch in #28418 against your test project, and the memory usage does not increase when the profiler is disabled

Great. I've just merged the pull-request, so I believe we can close this issue 🎉. The increased memory consumption on development makes sense. Thanks again @pierredup.

**Comment by konradja100** [comment]
Hi guys, how to test this patch in existing project? as i asume this bugfix will be released in 4.1.5 right?

**Comment by konradja100** [comment]
So i've tested this patch against my test project and memory is not increasing - cool - but not only on prod enviroment, but also on dev. First question is if this is desirable behavior, and second issue is that in my project changes does not effect used memory - it keep growing.

Could be this affected by other packages?

**Comment by konradja100** [comment]
Also funny thing is that this bugfix decrease allocated memory by half - so this might be solution, but issue is still unsolved as long as it will lead to memory leak at least.

**Comment by trickreich** [comment]
I still have memory problems when sending messages via `SymfonyMessenger`.
Is this problem in the component?

```
bin/console sulu-sylius:sync-all --no-debug --env=prod
Sync products
     0/34529 [>---------------------------]   0%Memory usage: 68263936
     1/34529 [>---------------------------]   0%Memory usage: 68263936
     2/34529 [>---------------------------]   0%Memory usage: 68263936
     3/34529 [>---------------------------]   0%Memory usage: 68263936
     4/34529 [>---------------------------]   0%Memory usage: 68263936
     5/34529 [>---------------------------]   0%Memory usage: 68263936
     6/34529 [>---------------------------]   0%Memory usage: 68263936
     7/34529 [>---------------------------]   0%Memory usage: 68263936
     8/34529 [>---------------------------]   0%Memory usage: 68263936
     9/34529 [>---------------------------]   0%Memory usage: 68263936
    10/34529 [>---------------------------]   0%Memory usage: 68263936
    11/34529 [>---------------------------]   0%Memory usage: 68263936
    12/34529 [>---------------------------]   0%Memory usage: 68263936
    13/34529 [>---------------------------]   0%Memory usage: 68263936
    14/34529 [>---------------------------]   0%Memory usage: 68263936
    15/34529 [>---------------------------]   0%Memory usage: 68263936
    16/34529 [>---------------------------]   0%Memory usage: 68263936
    17/34529 [>---------------------------]   0%Memory usage: 68263936
    18/34529 [>---------------------------]   0%Memory usage: 68263936
    19/34529 [>---------------------------]   0%Memory usage: 68263936
    20/34529 [>---------------------------]   0%Memory usage: 68263936
    21/34529 [>---------------------------]   0%Memory usage: 68263936
    22/34529 [>---------------------------]   0%Memory usage: 68263936
    23/34529 [>---------------------------]   0%Memory usage: 68263936
    24/34529 [>---------------------------]   0%Memory usage: 68263936
    25/34529 [>---------------------------]   0%Memory usage: 68263936
    26/34529 [>---------------------------]   0%Memory usage: 68263936
    27/34529 [>---------------------------]   0%Memory usage: 68263936
    28/34529 [>---------------------------]   0%Memory usage: 68263936
    29/34529 [>---------------------------]   0%Memory usage: 68263936
    30/34529 [>---------------------------]   0%Memory usage: 68263936
    31/34529 [>---------------------------]   0%Memory usage: 68263936
    32/34529 [>---------------------------]   0%Memory usage: 68263936
    33/34529 [>---------------------------]   0%Memory usage: 68263936
    34/34529 [>---------------------------]   0%Memory usage: 68263936
    35/34529 [>---------------------------]   0%Memory usage: 68263936
    36/34529 [>---------------------------]   0%Memory usage: 68263936
    37/34529 [>---------------------------]   0%Memory usage: 68263936
    38/34529 [>---------------------------]   0%Memory usage: 68263936
    39/34529 [>---------------------------]   0%Memory usage: 68263936
    40/34529 [>---------------------------]   0%Memory usage: 68263936
    41/34529 [>---------------------------]   0%Memory usage: 68263936
    42/34529 [>---------------------------]   0%Memory usage: 68263936
    43/34529 [>---------------------------]   0%Memory usage: 68263936
    44/34529 [>---------------------------]   0%Memory usage: 68263936
    45/34529 [>---------------------------]   0%Memory usage: 68263936
    46/34529 [>---------------------------]   0%Memory usage: 68263936
    47/34529 [>---------------------------]   0%Memory usage: 68263936
    48/34529 [>---------------------------]   0%Memory usage: 68263936
    49/34529 [>---------------------------]   0%Memory usage: 68263936
    50/34529 [>---------------------------]   0%Memory usage: 68263936
    51/34529 [>---------------------------]   0%Memory usage: 68263936
    52/34529 [>---------------------------]   0%Memory usage: 68263936
    53/34529 [>---------------------------]   0%Memory usage: 68263936
    54/34529 [>---------------------------]   0%Memory usage: 68263936
    55/34529 [>---------------------------]   0%Memory usage: 68263936
    56/34529 [>---------------------------]   0%Memory usage: 68263936
    57/34529 [>---------------------------]   0%Memory usage: 68263936
    58/34529 [>---------------------------]   0%Memory usage: 68263936
    59/34529 [>---------------------------]   0%Memory usage: 68263936
    60/34529 [>---------------------------]   0%Memory usage: 68263936
    61/34529 [>---------------------------]   0%Memory usage: 68263936
    62/34529 [>---------------------------]   0%Memory usage: 68263936
    63/34529 [>---------------------------]   0%Memory usage: 68263936
    64/34529 [>---------------------------]   0%Memory usage: 68263936
    65/34529 [>---------------------------]   0%Memory usage: 68263936
    66/34529 [>---------------------------]   0%Memory usage: 68263936
    67/34529 [>---------------------------]   0%Memory usage: 68263936
    68/34529 [>---------------------------]   0%Memory usage: 68263936
    69/34529 [>---------------------------]   0%Memory usage: 68263936
    70/34529 [>---------------------------]   0%Memory usage: 68263936
    71/34529 [>---------------------------]   0%Memory usage: 68263936
    72/34529 [>---------------------------]   0%Memory usage: 68263936
    73/34529 [>---------------------------]   0%Memory usage: 68263936
    74/34529 [>---------------------------]   0%Memory usage: 68263936
    75/34529 [>---------------------------]   0%Memory usage: 68263936
    76/34529 [>---------------------------]   0%Memory usage: 68263936
    77/34529 [>---------------------------]   0%Memory usage: 68263936
    78/34529 [>---------------------------]   0%Memory usage: 68263936
    79/34529 [>---------------------------]   0%Memory usage: 70361088
    80/34529 [>---------------------------]   0%Memory usage: 70361088
    81/34529 [>---------------------------]   0%Memory usage: 70361088
    82/34529 [>---------------------------]   0%Memory usage: 70361088
    83/34529 [>---------------------------]   0%Memory usage: 70361088
    84/34529 [>---------------------------]   0%Memory usage: 70361088
    85/34529 [>---------------------------]   0%Memory usage: 70361088
    86/34529 [>---------------------------]   0%Memory usage: 70361088
    87/34529 [>---------------------------]   0%Memory usage: 70361088
    88/34529 [>---------------------------]   0%Memory usage: 70361088
    89/34529 [>---------------------------]   0%Memory usage: 70361088
    90/34529 [>---------------------------]   0%Memory usage: 70361088
    91/34529 [>---------------------------]   0%Memory usage: 70361088
    92/34529 [>---------------------------]   0%Memory usage: 70361088
    93/34529 [>---------------------------]   0%Memory usage: 70361088
    94/34529 [>---------------------------]   0%Memory usage: 70361088
    95/34529 [>---------------------------]   0%Memory usage: 70361088
    96/34529 [>---------------------------]   0%Memory usage: 70361088
    97/34529 [>---------------------------]   0%Memory usage: 70361088
    98/34529 [>---------------------------]   0%Memory usage: 70361088
    99/34529 [>---------------------------]   0%Memory usage: 70361088
   100/34529 [>---------------------------]   0%Memory usage: 70361088
   101/34529 [>---------------------------]   0%Memory usage: 70361088
   102/34529 [>---------------------------]   0%Memory usage: 70361088
   103/34529 [>---------------------------]   0%Memory usage: 70361088
   104/34529 [>---------------------------]   0%Memory usage: 70361088
   105/34529 [>---------------------------]   0%Memory usage: 70361088
   106/34529 [>---------------------------]   0%Memory usage: 70361088
   107/34529 [>---------------------------]   0%Memory usage: 70361088
   108/34529 [>---------------------------]   0%Memory usage: 70361088
   109/34529 [>---------------------------]   0%Memory usage: 70361088
   110/34529 [>---------------------------]   0%Memory usage: 70361088
   111/34529 [>---------------------------]   0%Memory usage: 70361088
   112/34529 [>---------------------------]   0%Memory usage: 70361088
   113/34529 [>---------------------------]   0%Memory usage: 70361088
   114/34529 [>---------------------------]   0%Memory usage: 70361088
   115/34529 [>---------------------------]   0%Memory usage: 70361088
   116/34529 [>---------------------------]   0%Memory usage: 70361088
   117/34529 [>---------------------------]   0%Memory usage: 70361088
   118/34529 [>---------------------------]   0%Memory usage: 70361088
   119/34529 [>---------------------------]   0%Memory usage: 70361088
   120/34529 [>---------------------------]   0%Memory usage: 70361088
   121/34529 [>---------------------------]   0%Memory usage: 70361088
   122/34529 [>---------------------------]   0%Memory usage: 70361088
   123/34529 [>---------------------------]   0%Memory usage: 70361088
   124/34529 [>---------------------------]   0%Memory usage: 70361088
   125/34529 [>---------------------------]   0%Memory usage: 70361088
   126/34529 [>---------------------------]   0%Memory usage: 70361088
   127/34529 [>---------------------------]   0%Memory usage: 70361088
   128/34529 [>---------------------------]   0%Memory usage: 70361088
   129/34529 [>---------------------------]   0%Memory usage: 70361088
   130/34529 [>---------------------------]   0%Memory usage: 70361088
   131/34529 [>---------------------------]   0%Memory usage: 70361088
   132/34529 [>---------------------------]   0%Memory usage: 70361088
   133/34529 [>---------------------------]   0%Memory usage: 70361088
   134/34529 [>---------------------------]   0%Memory usage: 70361088
   135/34529 [>---------------------------]   0%Memory usage: 70361088
   136/34529 [>---------------------------]   0%Memory usage: 70361088
   137/34529 [>---------------------------]   0%Memory usage: 70361088
   138/34529 [>---------------------------]   0%Memory usage: 70361088
   139/34529 [>---------------------------]   0%Memory usage: 70361088
   140/34529 [>---------------------------]   0%Memory usage: 70361088
   141/34529 [>---------------------------]   0%Memory usage: 72458240
   142/34529 [>---------------------------]   0%Memory usage: 72458240
   143/34529 [>---------------------------]   0%Memory usage: 72458240
   144/34529 [>---------------------------]   0%Memory usage: 72458240
   145/34529 [>---------------------------]   0%Memory usage: 72458240
   146/34529 [>---------------------------]   0%Memory usage: 72458240
   147/34529 [>---------------------------]   0%Memory usage: 72458240
   148/34529 [>---------------------------]   0%Memory usage: 72458240
   149/34529 [>---------------------------]   0%Memory usage: 72458240
   150/34529 [>---------------------------]   0%Memory usage: 72458240
   151/34529 [>---------------------------]   0%Memory usage: 72458240
   152/34529 [>---------------------------]   0%Memory usage: 72458240
   153/34529 [>---------------------------]   0%Memory usage: 72458240
   154/34529 [>---------------------------]   0%Memory usage: 72458240
   155/34529 [>---------------------------]   0%Memory usage: 72458240
   156/34529 [>---------------------------]   0%Memory usage: 72458240
```

**Comment by gander** [comment]
Did you try `composer install --no-dev`?
