### ISSUE TITLE
[Form] TransformationFailedException when submitting a ISO8601 date to a DateTimeType field

### ISSUE THREAD

**Issue by borodiliz** [symfony/symfony#28699]
**Symfony version affected**: 4.1.5

**Description**  
After upgrading from `4.1.4` to `4.1.5` I'm getting a `TransformationFailedException`  when submitting a `ISO8601` date to a `DateTimeType` field

**How to reproduce**  
Create form containing a `DateTimeType`
```php
            ->add(
                'schedule',
                DateTimeType::class,
                array('widget' => 'single_text')
```
Submit the following data to the previous field: `2018-10-03T10:00:00.000Z`

**Possible Solution**  
Downgrading 'symfony/form' to ' 4.1.4' solves the problem
 
**Additional context**  
```php
TransformationFailedException {#2535 ▼
  #message: "The date "2018-10-03T10:00:00.000Z" is not a valid date."
  #code: 0
  #file: "/var/www/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToHtml5LocalDateTimeTransformer.php"
  #line: 85
  trace: {▼
    /var/www/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToHtml5LocalDateTimeTransformer.php:85 {▶}
    /var/www/vendor/symfony/form/Form.php:1112 {▶}
    /var/www/vendor/symfony/form/Form.php:626 {▶}
    /var/www/vendor/symfony/form/Form.php:566 {▶}
    /var/www/src/Handler/MessageScheduleHandler.php:154 {▼
      › );
      › $form->submit($parameters, 'PATCH' !== $method);
      › if ($form->isSubmitted() && $form->isValid()) {
      arguments: {▶}
    }
    /var/www/src/Handler/MessageScheduleHandler.php:117 {▶}
    /var/www/src/Controller/MessageScheduleController.php:250 {▶}
    /var/www/vendor/symfony/http-kernel/HttpKernel.php:149 {▶}
    /var/www/vendor/symfony/http-kernel/HttpKernel.php:66 {▶}
    /var/www/vendor/symfony/http-kernel/Kernel.php:188 {▶}
    /var/www/public/index.php:37 {▶}
  }
}
```

**Comment by xabbuh** [comment]
When using the `single_text` widget, the expected format is neither ISO 8601 nor RFC 3339. We fixed that in #28372. You will either have to explicit configure the expected format manually or update the code that submits this data. I am closing here as this is the expected behaviour.

**Comment by xabbuh** [comment]
Can you explain how you ended up with this error? Was it in a test?

**Comment by xabbuh** [comment]
It seems like this may actually break some frontends that use JavaScript based datepicker libraries (see https://github.com/symfony/symfony/issues/28703#issuecomment-426715758). I am not yet sure how we should deal with and what the exact impact is here, so any information that may sound helpful is really appreciated. In the meantime I am reopening here.

**Comment by xabbuh** [comment]
By the way, the issue that the linked PR aimed to fix is #27233.

**Comment by fidraj** [comment]
Confirming this issue.

We're sending a date from our frontend using https://github.com/dbushell/Pikaday like this:

```php
estimated_delivery: “2018-10-04T00:00:00-04:00”
```

Now we're getting this error:
```php
estimatedDelivery: {errors: [“This value is not valid.“]}
```

The form is defined as:
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add(
        'estimatedDelivery',
        DateTimeType::class,
        [
            'widget' => 'single_text',
        ]
    );
}
```

Solved by downgrade from 3.4.16 to 3.4.15.

**Comment by fidraj** [comment]
The form field shows the date correctly. However the datepicker doesn't but it never did so it's hard to tell if there's any change in the behaviour.

**Comment by xabbuh** [comment]
Can you check if #28712 fixes the issue?

**Comment by fidraj** [comment]
Confirming, it does fix the issue.

**Comment by borodiliz** [comment]
Quite similar case here. We're sending dates from our `Angular` frontend using https://www.npmjs.com/package/ng2-datetime

I'm still having problems after applying #28712 . My date is in format 2018-10-03T10:00:00.000Z (it contains milliseconds). It seems that `ng2-datetime` uses the `toISOString()`  javascript function https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

Maybe this regex could help (not sure if the implementation is correct) : https://www.regextester.com/97766

Thanks for your quick reply and sorry for my delay

**Comment by xabbuh** [comment]
@magnetik So that will be fixed by #28712, right?

**Comment by magnetik** [comment]
yep

**Comment by xabbuh** [comment]
@borodiliz Thank you for the feedback. That should work with the changes from #28712 too.

**Comment by borodiliz** [comment]
Issue fixed! Thanks for your time
