### ISSUE TITLE
[Bug][BC break][Workflow] Workflow metadata has disappeared since symfony/framework-bundle 4.1.8

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#29427]
**Symfony version(s) affected**: `symfony/framework-bundle` 4.1.8+

**Description**
I'm working on a command that use `metadata` for adding style to workflow dumps.

The configuration is:

```yaml
framework:
    workflows:
        pull_request:
            # …
            transitions:
                submit:
                    from: start
                    to: travis
                    metadata:
                        title: transition submit title
                        style:
                            label: 'My custom label'
                            arrow_color: '#0088FF'
                            label_color: 'Red'
                # …
```

And I get metadata with `$this->workflowMetadata->getMetadata('style', $transition)`: https://github.com/alexislefebvre/SymfonyWorkflowStyleBundle/blob/ce5d5923cedd2a3b41e51386faf56a9888880739/src/Symfony/Component/Workflow/Dumper/PlantUmlDumper.php#L191

It worked one week ago but it is broken today: no data is returned.

I identified that it comes from `symfony/framework-bundle`, it breaks if I install `v4.1.8` or `v4.2.0`.

**How to reproduce**
Clone https://github.com/alexislefebvre/SymfonyWorkflowStyleBundle, install dependencies and run tests:

```
git clone git@github.com:alexislefebvre/SymfonyWorkflowStyleBundle.git
cd SymfonyWorkflowStyleBundle/
composer install -vvv --profile --no-progress
php ./vendor/bin/phpunit
```

Tests pass.

Now remove `conflict` from `composer.json`, update dependencies and run tests again: Tests will fail because data in `metadata` is not available, so the PUML lacks the expected style.

**Possible Solution**

The problem is probably in one of these commits: https://github.com/symfony/framework-bundle/compare/v4.1.7...v4.1.8

Only 2 commits were related to Workflow: https://github.com/symfony/framework-bundle/commit/0647c5aeb0f3ce9914b066967ef7a75f4039b3a0 ([PR](https://github.com/symfony/symfony/pull/29137)) and https://github.com/symfony/framework-bundle/commit/1c1f86be45ee553169bd0c928822de8b1b42b7b0 ([PR](https://github.com/symfony/symfony/pull/28769))

**Additional context**

We can see logs on Travis CI:

- job from 7 days ago: https://travis-ci.org/alexislefebvre/SymfonyWorkflowStyleBundle/jobs/459487618 →test passed
- job from today: https://travis-ci.org/alexislefebvre/SymfonyWorkflowStyleBundle/jobs/462429106 →test failed

The base code of my bundle has not been changed between these 2 jobs (¹), the only difference is that Symfony 4.1.8 and 4.2 have been released and these versions were installed today.

(¹) I only changed the configuration of failing jobs on Travis CI

**Comment by alexislefebvre** [comment]
I tested this configuration in https://github.com/alexislefebvre/symfony/pull/4 and the `style` node is not allowed by the XML validator, so maybe I was using an expected behaviour that allowed arbitrary nodes in the YAML configuration.

**Comment by alexislefebvre** [comment]
I added some tests of metadata in https://github.com/alexislefebvre/symfony/pull/4 and the configuration is exported successfully (except for XML but it's unrelated).

So it looks like the `metadata` configuration is exported successfully from the files, but it's not passed to the workflow component.

**Comment by lyrixx** [comment]
@alexislefebvre Thanks for reporting this issue. This is indeed a typo. I missed it when merging another PR. I fixed it in #29444

**Comment by alexislefebvre** [comment]
@lyrixx Awesome, thank you! I would never have spotted this error, I didn't see anything suspicious when looking at the changes.

**Comment by alexislefebvre** [comment]
I will close this issue after the next release of Symfony and once I'll have checked that the issue is fixed.

**Comment by nicolas-grekas** [comment]
Acutally we close when the fixing PR is merged - please open an other issue of the bug is still there after the release.
