### ISSUE TITLE
ValidatorException on Doctrine Proxy (Auto Validation Mapping?)

### ISSUE THREAD

**Issue by fabstei** [symfony/symfony#31715]
**Symfony version(s) affected**:
4.3 (Beta2 & RC1)

**Description**  
Handling a request with a form that has an assigned Entity seems to wrongly trigger a ValidatorException.

**How to reproduce** 
My apologies for the missing reproducer - I'm having issues creating it. since 4.3.0-RC1 is affected I thought sharing even without one could help.

```
        $entityManager = $this->getDoctrine()->getManager();
        $person = $entityManager->getRepository(Person::class)->findOneBy(['id' => $id]);

        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);
```
triggers
```
ValidatorException: Property "xyz" does not exist in class "Proxies\__CG__\App\Entity\Person"
```
in [PropertyMetadata.php#L39-L41](https://github.com/symfony/symfony/blob/v4.3.0-BETA2/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L39-L41)

The stacktrace is here: https://gist.github.com/fabstei/ee254c7945ebc79fd3fed75cf4de82db

**Possible Solution**  
None so far. After uncommenting [PropertyMetadata.php#L39-L41](https://github.com/symfony/symfony/blob/v4.3.0-BETA2/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L39-L41) everything works as expected, but it's obviously not a solution.

**Additional context**  
- Mac OS Mojave 10.14.5
- PHP 7.3.5

**Comment by ThomasTr** [comment]
Same for me, recently upgraded to 4.3.0, form with a EntityType, for now on, the properties of these entity must be public to avoid this exception?!?

**Comment by xabbuh** [comment]
Did you enable the new `auto_mapping` feature (see #27735) or does it also happen without doing so?

**Comment by pbowyer** [comment]
It happens without enabling `auto_mapping`. For my project it's been a straight switch of `4.2.*` to `4.3.*` in `composer.json`; only other changes are to clean up deprecations with the Workflow component.

**Comment by ThomasTr** [comment]
For me, auto_mapping was already enabled without any issues prior to 4.3.0

**Comment by pbowyer** [comment]
> Did you enable the new auto_mapping feature

I can't find any docs on how this new feature is enabled/disabled; the only `auto_mapping` I find is in `doctrine.yaml` which in my project is:
```
doctrine:
    orm:
        auto_mapping: true
```
This was auto-generated when first creating the project using Symfony 4.2.2.

**Comment by xabbuh** [comment]
I mean the new `framework.validation.auto_mapping` option (see https://github.com/symfony/symfony/blob/4.3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L850).

**Comment by pbowyer** [comment]
I have not set it, and it isn't present in the config files. 

Running `bin/console debug:config framework` gives:
```
framework:
    # ...
    validation:
        email_validation_mode: html5
        enabled: true
        enable_annotations: true
        static_method:
            - loadValidatorMetadata
        translation_domain: validators
        mapping:
            paths: {  }
        not_compromised_password:
            enabled: true
            endpoint: null
        auto_mapping: {  }
```

**Comment by xabbuh** [comment]
#31749 is a first steps which at least ensures that auto mapping is not enabled by default. Though that doesn't fix the core issue with Doctrine proxies.

**Comment by MortalFlesh** [comment]
Hello,

it seems I have this exception as well. But with embedded doctrine entity.

I have Embeddable entity `Foo` with fields `one` and `two`. And the entity `Bar`, which has `Foo` embeded like this `Embedded(class="Foo", columnPrefix=false)`. And I get the error of `Property "foo.one" does not exist in class "Bar"`.

I think it is because of autovalidating a length of column, since both `one` and `two` are defined like this
```php
// Foo
/**
 * @ORM\Column(type="string", length=100)
 *
 * @var string
 */
private $one;
```

**Comment by fabstei** [comment]
@MortalFlesh it seems that Nicolas Grekas is already on it - in the meantime try setting this in your framework config:

```
framework:
    validation:
        auto_mapping: {}
```

**Comment by guillaumesmo** [comment]
@fabstei @MortalFlesh I have the same issue with embedded entities in a SYmfony 4.3 migrations
Unfortunately, using `auto_mapping: {}` doesn't seem to help, DoctrineLoader is still called and the exception is thrown

**Comment by IMSDeveloper** [comment]
I'm also seeing this error in Symfony 4.3.0. The property it's complaining about is definitely in the entity. The property is defined as '@ORM\Column(type="string", length=100, nullable=true, unique=true)'

Same as above, settings the auto_mapping property does not resolve this. I'm also seeing a similar issue with inherited entities i.e. I have an entity class extending another - it's unable to access properties of the base class.

**Comment by ayalon** [comment]
I have the same issue with the following field definition:
```
    /**
     *
     * The id
     *
     * @var string
     *
     * @ORM\Column(name="my_id", type="string", length=60, nullable=true)
     */
    private $my_id;

```

**Comment by xabbuh** [comment]
Can one of you create an example application that allows to reproduce?

**Comment by pulsesalessolutions** [comment]
@guillaumesmo,

Thanks that seems to have worked for me;

framework.yaml

framework:
  validation:
    auto_mapping: {'App\\': {}}

**Comment by IMSDeveloper** [comment]
@pulsesalessolutions This works for me also!

**Comment by rjwebdev** [comment]
Facing same issue after submitting a form. Mapping on my entity:
```
    /**
     * @ORM\Column(type="string", length=100)
     */
    private $street;
```

Error I get after submitting the form:
`[2019-06-03 23:44:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\ValidatorException: "Property "street" does not exist in class "Proxies\__CG__\App\Entity\Core\Address"" at /vendor/symfony/validator/Mapping/PropertyMetadata.php line 40 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\ValidatorException(code: 0): Property \"street\" does not exist in class \"Proxies\\__CG__\\App\\Entity\\Core\\Address\" at /vendor/symfony/validator/Mapping/PropertyMetadata.php:40)"} []`

**Comment by Flinsch** [comment]
@guillaumesmo's solution works for me too:

`framework: validation: auto_mapping: {'App\\': {}}`

I have some Doctrine entities with inheritance and since 4.3, and in forms for derived entities, I got this "property does not exist" problem for properties of base classes, as already described by others. I don't know how and why, but `auto_mapping` set to `{'App\\': {}}` works. It seems that the documentation is quite behind the actual release, at least I can't find anything about this `auto_mapping` feature, as @pbowyer mentioned before. The documentation inconsistencies also apply for (all?) other aspects/features of 4.3: on the docs pages, the version is set to 4.3, but the content doesn't address the changes listed at [UPGRADE-4.3md](https://github.com/symfony/symfony/blob/4.3/UPGRADE-4.3.md).

**Comment by christian-kolb** [comment]
This also affects third party bundles like `gesdinet/jwt-refresh-token-bundle`: https://github.com/gesdinet/JWTRefreshTokenBundle/issues/151
They plan to wait until it's resolved in the related symfony component. Is this expectable?

**Comment by xabbuh** [comment]
Can you check if #31836 finally solves this issue?

**Comment by guillaumesmo** [comment]
@xabbuh that seems to have fixed the problem indeed

Thank you

**Comment by xabbuh** [comment]
@guillaumesmo Thank you very much for the feedback.

**Comment by teohhanhui** [comment]
I'm not sure that this issue is actually fixed. The problem in the first place was that Doctrine's proxy class was being used instead of the actual entity class. The related PRs don't seem to address that problem, but merely avoiding it.

**Comment by xabbuh** [comment]
@teohhanhui If I don't miss anything, the issue was that the `DoctrineLoader` tried to add constraints to the Doctrine proxy classes that had already been attached to the actual entity class before.

**Comment by teohhanhui** [comment]
Oh yeah, because it was registering `DoctrineLoader` with no regexp: https://github.com/doctrine/DoctrineBundle/blob/a8377d4b60b931a3ad28712aa80fe0b6e3b7c9db/DependencyInjection/DoctrineExtension.php#L799-L812

**Comment by xabbuh** [comment]
The fact that the feature was enabled by default was another bug fixed in #31749.

**Comment by teohhanhui** [comment]
@xabbuh I know, but what I was trying to say is that, the bug shouldn't exist according to my logic above, but it does. Which means that my understanding was wrong, which means that we didn't get to the root of the problem, and maybe the bug is still not fixed...

**Comment by xabbuh** [comment]
I think I do not really understand the issue then. Could you create a small example application that allows to reproduce this?
