### ISSUE TITLE
[DoctrineBridge] DoctrineLoader can't access embedded object properties

### ISSUE THREAD

**Issue by Korbeil** [symfony/symfony#31775]
**Symfony version(s) affected**: 4.3.0

**Description**  
I just upgraded my application to 4.3.0 and saw this bug.
We have a `UserAddress` entity:
```php
/**
 * @ORM\Table(name="user_address")
 */
class UserAddress
{
    /**
     * @var Address
     *
     * @ORM\Embedded(class="Address")
     */
    private $address;

    // ...
}
```
with an embedded object `Address`:
```php
/**
 * @ORM\Embeddable
 */
class Address
{
    /**
     * @var null|string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     */
    private $firstName;

    // ...
}
```

With new [Doctrine auto-validation feature](https://symfony.com/blog/new-in-symfony-4-3-automatic-validation), it tries to access `address.firstName` property, but in https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L39, we check if given property exists as it's given, so it can't work.

**Possible Solution**  
Use `symfony/property-accessor` ? Instead of reflection metadata which does not contains embedded objects metadata.

**Comment by NotDvaMain** [comment]
Same here.

My entity `Tag` have this property:
```
/**
* @ORM\Embedded(class="App\Doctrine\Embeddable\TagAdditional")
*
* @var TagAdditional|null
*/
protected $additional;
````

First property in embeddable generates `Symfony\Component\Validator\Exception\ValidatorException` exception with message `Property "additional.headerText" does not exist in class "App\Entity\Tag"`.

```
/**
* @ORM\Column(name="header_text", type="string", length=255, nullable=true)
*
* @Assert\Length(max="250")
*
* @var string|null
*/
protected $headerText;
```

Updated to Symfony 4.3 hour ago.
Problem can be temporarly fixed if we use `doctrine/common:v2.8.1` instead of latest version.

**Comment by dunglas** [comment]
Shouldn’t it be fixed in the Doctrine loader directly? Simply skipping Embedebbables in the parent class should be enough, and won’t prevent auto-validation to work because metadata are still stored in the child class (to be verified).

I don’t have a computer this weekend, but I’ll try to work on a fix on Monday.

**Comment by xabbuh** [comment]
I found the root cause. Working on a fix.

**Comment by xabbuh** [comment]
see #31811

**Comment by martiis** [comment]
With nested embedded objects it's still a problem.
f.e. embedded object in embedded object in entity.

**Comment by xabbuh** [comment]
@martiis Can you open a new issue and provide a small example application that allows to reproduce?

**Comment by martiis** [comment]
sure, but in about 1-2 hours, commuting :)
