### ISSUE TITLE
[HttpClient] CURLOPT_STDERR resource has gone away

### ISSUE THREAD

**Issue by ElGecko76** [symfony/symfony#31985]
**Symfony version(s) affected**: 4.3.1

**Description**  
I try to send GET request (there is the same problem with another method):

```
   protected const ENDPOINT_LISTS     = 'lists';

    /**
     * @var string
     */
    protected $apiKey;

    /**
     * @var string
     */
    protected $dataCenter;

    /**
     * @var HttpClient
     */
    protected $httpClient;

    /**
     * @var string
     */
    protected $password;

    /**
     * @var string
     */
    protected $user;

    public function __construct(string $apiKey, string $dataCenter, string $password, string $user)
    {
        $this->httpClient = HttpClient::create([
            'base_uri' => 'https://' . $dataCenter . '.api.mailchimp.com/3.0/',
            'timeout'  => 5,
            'headers'  => [
                'Authorization' => 'Basic ' . base64_encode($user . ':' . $password),
            ],
        ]);

        $this->apiKey     = $apiKey;
        $this->dataCenter = $dataCenter;
        $this->user       = $user;
        $this->password   = $password;
    }

    public function getLists(): ?array
    {
        $response = $this->httpClient->request(Request::METHOD_GET, self::ENDPOINT_LISTS);

        if ($response instanceof Response && $response->getStatusCode() === HttpFoundationResponse::HTTP_OK) {
            return $this->getContents($response);
        }

        return null;
    }

    protected function getContents(Response $response): ?array
    {
        return json_decode($response->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
    }
```

I get this error in the profiler:

`Uncaught PHP Exception ErrorException: "Warning: curl_multi_exec(): CURLOPT_STDERR resource has gone away, resetting to stderr" at /var/www/my_project/vendor/symfony/http-client/Response/CurlResponse.php line 260`

**Additional context**  
![Sans titre](https://user-images.githubusercontent.com/19478137/59229401-96c2f000-8bda-11e9-863a-c071ea7304c5.png)

![image](https://user-images.githubusercontent.com/19478137/59229591-181a8280-8bdb-11e9-9209-206bf8fc3b7c.png)

In the "replaces" section, I have both, alternate dependencies and replaced dependencies: https://packagist.org/packages/symfony/contracts

![image](https://user-images.githubusercontent.com/19478137/59253273-1ded8380-8c2e-11e9-9e0c-d9b12bab0aaf.png)

![image](https://user-images.githubusercontent.com/19478137/59253182-f39bc600-8c2d-11e9-947d-eb7defc94bae.png)

I'm using PHP version 7.3.6 FPM and I have Composer 1.8.5 version

See previous report : https://github.com/symfony/symfony/issues/31803

**Comment by derrabus** [comment]
The problem with the composer error is that you have both the old contracts package and the new split contracts packages installed. This is something that should be fixed, but I doubt that it causes the problem you're having with the HTTP client.

**Comment by derrabus** [comment]
symfony/panther#198 will most likely fix the composer error for you (cc @nicolas-grekas @dunglas).

**Comment by ElGecko76** [comment]
So, the problem is caused by:

> "symfony/test-pack": "*"

Which uses: 

> "symfony/panther": "*",

in composer.json

**Comment by dunglas** [comment]
I just tagged a new release containing Nicolas's patch.

**Comment by javiereguiluz** [comment]
@ElGecko76 totally unrelated to your error ... but in case you missed it, you can simplify the code of your HTTP client as follows:

```diff
-'headers'  => [
-    'Authorization' => 'Basic ' . base64_encode($user . ':' . $password),
-],
+'auth_basic' => [$user, $password],
```

**Comment by ElGecko76** [comment]
@dunglas Thank you ! :)

@javiereguiluz Thank you ! This simplification automatically encodes in base 64?

For this error, do you know how to correct it?

> Uncaught PHP Exception ErrorException: "Warning: curl_multi_exec(): CURLOPT_STDERR resource has gone away, resetting to stderr" at /var/www/my_project/vendor/symfony/http-client/Response/CurlResponse.php line 260

**Comment by javiereguiluz** [comment]
@ElGecko76 yes:

* first, it concatenates the array elements into a string separated by `:`  https://github.com/symfony/symfony/blob/d3055814ad9680e00f2fb00e291aafa986002ad9/src/Symfony/Component/HttpClient/HttpClientTrait.php#L82-L89
* then, it base64 encodes the result https://github.com/symfony/symfony/blob/d3055814ad9680e00f2fb00e291aafa986002ad9/src/Symfony/Component/HttpClient/HttpClientTrait.php#L106

**Comment by ElGecko76** [comment]
Thank you for correcting the first problem which is totally unrelated to my error.

I tried with dev-master and the error:

> Uncaught PHP Exception ErrorException: "Warning: curl_multi_exec(): CURLOPT_STDERR resource has gone away, resetting to stderr" at /var/www/my_project/vendor/symfony/http-client/Response/CurlResponse.php line 260

is still there

Do you know where this can come from? And is it possible to correct it?

**Comment by nicolas-grekas** [comment]
can you please try this patch.

```diff
--- a/Response/CurlResponse.php
+++ b/Response/CurlResponse.php
@@ -168,7 +168,8 @@ final class CurlResponse implements ResponseInterface
                 rewind($this->debugBuffer);
                 $info['debug'] = stream_get_contents($this->debugBuffer);
                 curl_setopt($this->handle, CURLOPT_VERBOSE, false);
-                fclose($this->debugBuffer);
+                rewind($this->debugBuffer);
+                ftruncate($this->debugBuffer, 0);
                 $this->debugBuffer = null;
                 $this->finalInfo = $info;
             }
```

**Comment by ElGecko76** [comment]
I tried and I have this error:

> [Wed Jun 12 13:42:13.562201 2019] [proxy_fcgi:error] [pid 19459] [client 10.0.1.10:53608] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\HttpClient\\Exception\\ClientException: HTTP/2 401  returned for "https://us20.api.mailchimp.com/3.0/lists". in /var/www/my_project/vendor/symfony/http-client/Response/ResponseTrait.php:232\nStack trace:\n#0 /var/www/my_project/vendor/symfony/http-client/Response/ResponseTrait.php(248): Symfony\\Component\\HttpClient\\Response\\CurlResponse->checkStatusCode()\n#1 /var/www/my_project/vendor/symfony/http-client/Response/CurlResponse.php(193): Symfony\\Component\\HttpClient\\Response\\CurlResponse->doDestruct()\n#2 [internal function]: Symfony\\Component\\HttpClient\\Response\\CurlResponse->__destruct()\n#3 {main}\n  thrown in /var/www/my_project/vendor/symfony/http-client/Response/ResponseTrait.php on line 232'

**Comment by nicolas-grekas** [comment]
So, it works, and you have an authorization issue :)

**Comment by ElGecko76** [comment]
The Web Debug Toolbar doesn't handle the error, the log is output in the Apache error log. I doesn't know if my development is good but isn't Symfony supposed to display an error in this context ?

**Comment by nicolas-grekas** [comment]
@ElGecko76 can you please try the new patch I added in #32011?
It won't fix the authorization error, but it should be a better fix for the one related to "resource has gone away".
About the error, it should be displayed yes, but destructors are tricky so maybe it is called too late in the process.
Why don't you check the response in your code?

**Comment by ElGecko76** [comment]
It happens before It reaches my `dd($response);`. That's why it's a real problem, because I don't have any Symfony output except a plain blank page due to the 500 error from Apache.

My code:

```
public function getLists(): ?array
{
    $response = $this->httpClient->request(Request::METHOD_GET, self::ENDPOINT_LISTS, $this->httpClientBaseConfig);

    dd($response);

    if ($response instanceof Response && $response->getStatusCode() === HttpFoundationResponse::HTTP_OK) {
        return $this->getContents($response);
    }

    return null;
}
```

**Comment by stof** [comment]
at the time you are dumping the response, the HTTP request may still be in progress (`HttpClient::request` is not blocking. Methods of the Response are blocking until the info they need is received).

@nicolas-grekas could it be that the destructor is checking the status code and throwing an exception at the time we are killing the process because of `die` ?

**Comment by ElGecko76** [comment]
If I take out `dd($response);`, I obtain this error: 

> Reading from the response stream reached the inactivity timeout.

**Comment by nicolas-grekas** [comment]
> the destructor is checking the status code and throwing an exception at the time we are killing the process because of die ?

yes, that's what happens, that's normal behavior here.

@ElGecko76 your code is strange:
`$response instanceof Response`: what is `Response`? There is no `Response` class in the component. There is nothing to check as the response is guaranteed to be a `ResponseInterface` instance.

What does $this->getContent() do? Why not use `return $response->getContent()`?
Also, you are silently ignoring all non-200 status codes. That makes your logic quite fragile.

**Comment by nicolas-grekas** [comment]
Oh, I forgot to add (it's mentioned in the doc).
To debug a response, the best is doing `dump($response->getInfo('debug'))`.
This should typically happen after the call to getStatusCode(), because as @stif explained, responses are lazy so that doing the dump earlier cannot be very useful.

Lastly, I don't know about the timeout - that's yours to debug (you know how now :) )

**Comment by nicolas-grekas** [comment]
> What does $this->getContent() do?

That's in your code above. You should remove the function and replace it with `return $response->toArray();`

**Comment by ElGecko76** [comment]
@nicolas-grekas 

`if ($response instanceof Response && $response->getStatusCode() === HttpFoundationResponse::HTTP_OK) 
{
        return $this->getContents($response);
    }`

That had I think an interest with Guzzle (if I'm not saying nonsense) but not with the HttpClient component, my bad, I should have read a little more this beautiful documentation ^^.

So, if I understand your explanations, I have no condition to check the HTTP return code and to verify that the request sends me a response?

Thank you very much for your explanation and for the fixes!

**Comment by nicolas-grekas** [comment]
You're welcome :)

> I have no condition to check the HTTP return code and to verify that the request sends me a response

Yes, this would work out of the box:

`return $this->httpClient->request(Request::METHOD_GET, self::ENDPOINT_LISTS, $this->httpClientBaseConfig)->toArray();`

If a non expected status code is return, this will throw an exception for you so you'll notice.
