### ISSUE TITLE
Possible undocumented BC break: Parameter count change in EventDispatcher::dispatch

### ISSUE THREAD

**Issue by finwe** [symfony/symfony#32042]
**Symfony version(s) affected**: 4.3.0

**Description**  
Coming here from https://github.com/symfony/symfony-docs/issues/11628: signature of EventDispatcher::dispatch changed and the change is not described properly in release notes or in documentation.

**How to reproduce**  
- Use `$this->eventDispatcher->dispatch('event-name', $event)` with `symfony/event-dispatcher` `4.2.x`
- Upgrade to `4.3.0`
- Method signature no longer fits as the parameters are switched and the second one is commented out

**Additional context**  
This happens even with full stack symfony framework. Juggling with `EventDispatherInterface`s from different namespaces offers only mixed results and I couldn't find a upgrade guide or a description in the documentation how to transition to `Contracts` namespace properly.

**Comment by javiereguiluz** [comment]
@finwe this change should be documented in the "Upgrade to Symfony 4.3" guide here: https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.3.md#eventdispatcher

Also, we published a blog post about this: https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

We're going to update the docs soon.

**Comment by finwe** [comment]
How is this not a BC break? Shoudn't this be targeted for 5.0? Current EventDispatcher accepts only a single parameter.

**Comment by stof** [comment]
PHP does not break when passing extra arguments. The interface in Contracts is also meant to have 2 params (and the Debug component will warn you if you implement it without the second argument).

The implementations still deal with the argument.

**Comment by finwe** [comment]
I'm still not following. When I pass two parameters, string of an event name and the event object, and the definition changes so that only the event name without the event details is accepted, how is this not a bc break?

**Comment by nicolas-grekas** [comment]
See the source:

https://github.com/symfony/symfony/blob/9f6cbaa6b976f60a0ad009c2828c5155506dba6c/src/Symfony/Component/EventDispatcher/EventDispatcher.php#L49-L53

**Comment by finwe** [comment]
I see, thanks. So it should be enough to create ignore rules for static analysers until 5.0 is out?

**Comment by nicolas-grekas** [comment]
@finwe correct. Or make static analysers understand the annotations we use, because they make sense in the generic case too.
