### ISSUE TITLE
index.php URI routing issue

### ISSUE THREAD

**Issue by jonasemde** [symfony/symfony#34101]
**Symfony version(s) affected**: 4.3.5

**Description**  
All routes are also available under /index.php/whatever. This causes massive SEO duplicate content issues and could lead to unexpected behavior.

On these pages all generated links get prefixed with "index.php/" too.

**How to reproduce**  
**Example 1:**
1. https://symfony.com/index.php/doc/current/index.html
Click on any link in the navigation. The "index.php/" is prefixed everywhere.  

2. https://symfony.com/doc/current/index.html
Everything without the "index.php/" prefix.

**Possible Solution**  
```php
if (preg_match('/^\/index\.php\//', $_SERVER['REQUEST_URI'])) {
    $url = str_replace('index.php/', '', $_SERVER['REQUEST_URI']);
    header("Location: $url", true, 301);
    exit;
}
```

**Comment by xabbuh** [comment]
Would you like to report this as an issue of symfony.com or do you see this as a general bug report? To me this looks like the web server configuration of symfony.com simply needs to be fixed.

/cc @javiereguiluz

**Comment by jonasemde** [comment]
In my opinion this is a general bug in the Symfony router. Those URIs should not be accessible. This is not an issue in symfony.com alone. All Laravel application based on the Symfony router are affected aswell.

**Comment by javiereguiluz** [comment]
Let me ping @tucksaun to know his opinion about this. Thanks!

**Comment by jvasseur** [comment]
I think this is more a problem of server configuration than something that should be solved at the router level.

For example the [recommended nginx configuration](https://symfony.com/doc/current/setup/web_server_configuration.html#nginx) doesn't have this problem because the server routes everything through `index.php` but never servers the `index.php` file itself.

**Comment by Tobion** [comment]
This is a known server configuration thing, see for the initial fix https://github.com/symfony/symfony-standard/pull/503
Maybe we could implement such a redirect into the symfony router itself. But it would get tricky as someone might actually need the base path, e.g. for certain deployments in subfolders like /subfolder/index.php

**Comment by xabbuh** [comment]
let's close here then

**Comment by apfelbox** [comment]
Also you need this `index.php/` base url feature, if you can't or don't want to set up proper url rewriting.

**Comment by mindaugasvcs** [comment]
Agreed, this is a Symfony Router bug.
Even though I have not defined routes such as /index.php and /index.php/anything
Symfony is happy to provide the home page and "anything" page.

And NO, it has nothing to do with server (Nginx) misconfiguration, the problem here is that the Router component sniffs every possible server variable instead of just one - $_SERVER['REQUEST_URI'];
$_SERVER['REQUEST_URI'] SHOULD BE the only source of truth when comparing routes.

Actually to fix this bug (Symfony v5) I have to hack Nginx config:
    location ~ ^/index\.php(/|$) {
        return 404;
    }

Is this intentional? :/

**Comment by apfelbox** [comment]
@mindaugasvcs I think you should be able to prevent access to index.php/… by setting the location as internal:

https://nginx.org/en/docs/http/ngx_http_core_module.html#internal

**Comment by mindaugasvcs** [comment]
> @mindaugasvcs I think you should be able to prevent access to index.php/… by setting the location as internal:
> 
> https://nginx.org/en/docs/http/ngx_http_core_module.html#internal

It's one of possible solutions.
The real problem now is serving Twig 404 error page directly via Nginx, in dev environment we have /_error/404 route but in prod env is not available.
Anyway we should not be doing this kind of workaround, the problem here is Symfony Router.

**Comment by apfelbox** [comment]
I would not agree that this is an issue in Symfony itself, as this should be fixed in the web server config, like mentioned above: https://github.com/symfony/symfony/issues/34101#issuecomment-545982874

IMO: Symfony works correctly here and the feature is indeed important.

**Comment by mindaugasvcs** [comment]
> I would not agree that this is an issue in Symfony itself, as this should be fixed in the web server confit, like mentioned above: [#34101 (comment)](https://github.com/symfony/symfony/issues/34101#issuecomment-545982874)
> 
> IMO: Symfony works correctly here and the feature is indeed important.

Can you elaborate as of reasons why this bug is needed?

**Comment by apfelbox** [comment]
There are cases where you have no rewriting in the web server available, and without that you wouldn‘t be able to visit any page in the project. The `index.php/path` setup works without any special config anywhere.
Sometimes you need that.

And for all other cases you should have default web server config that properly solves that.

**Comment by mindaugasvcs** [comment]
> There are cases where you have no rewriting in the web server available, and without that you wouldn‘t be able to visit any page in the project. The `index.php/path` setup works without any special config anywhere. Sometimes you need that.
> 
> And for all other cases you should have default web server config that properly solves that.

Still not clear, what cases? Examples?
Usually, in a shared hosting environment you get Apache server with access to .htaccess config file in a web directory where you can direct all traffic to non existing files to index.php (rewrites etc.).

BTW, shared hosting is not meant for Symfony projects anyway.
