### ISSUE TITLE
[Console] No prompt using symfony/cli

### ISSUE THREAD

**Issue by sabruss** [symfony/symfony#34535]
**Symfony version(s) affected**: 4.3.x and 5

**Description**  

`symfony.exe console make:entity Test` It say aborted
`php bin/console make:entity Test`  works normally

**How to reproduce** 
create new project symfony/skeleton
`composer req orm maker`
`symfony.exe console make:entity Test` 

**Additional context**  

using W10 v1909 and windows cmd

> symfony.exe console
![image](https://user-images.githubusercontent.com/17797150/69471727-dd7c5f00-0da2-11ea-8d4f-82ff7fc17b11.png)

>php bin/console
![image](https://user-images.githubusercontent.com/17797150/69471731-ed943e80-0da2-11ea-9000-f6c95cfa3b69.png)

**Comment by rached-bch** [comment]
Things to check at first : 

- Enable symfony.exe in computer firewall
- Install symfony under connected user directory
- Check if its possible to run server before attempting to create entity (if its not, check if the symfony executable is for current os)

**Comment by sabruss** [comment]
Okey so I just reinstalled the symfony.exe and now it works. Thanks

I did every update when it asked me.
I also cleared the .symfony generated on %userprofile%

Fixed !

**Comment by gundamftw** [comment]
> Things to check at first :
> 
> * Enable symfony.exe in computer firewall
> * Install symfony under connected user directory
> * Check if its possible to run server before attempting to create entity (if its not, check if the symfony executable is for current os)

Hi I'm having the same problem. What do you mean by installing "under connected user directory"? The default installation directory is c:\program files.

**Comment by rached-bch** [comment]
Hi, i meant the directory of current session user in windows. 

For example : **C:\Users\John\**

**Comment by gundamftw** [comment]
> Hi, i meant the directory of current session user in windows.
> 
> For example : C:\Users\John\

Hi I followed all those steps but I'm still getting the abort message

`$ symfony console make:entity Test

 created: src/Entity/Test.php
 created: src/Repository/TestRepository.php

 Entity generated! Now let's add some fields!
 You can always add more fields later manually or by re-running this command.

 New property name (press <return> to stop adding fields):
 >
            
  Aborted.  

make:entity [-a|--api-resource] [--regenerate] [--overwrite] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <comman
d> [<name>]

exit status 1
`

It created the entity files but it aborted right after the prompt for adding new property

**Comment by ld-web** [comment]
Hi, same here, usually I use `php bin/console make:entity`, and now I'm getting 'Aborted' error message.
So I tested with `symfony console make:entity` : same message.

I also tested with other commands which require an input (`make:unit-test`, `doctrine:fixtures:load`, `doctrine:migrations:migrate` where you have to press "Y" or "n" for instance), also "Aborted".

For now I just pass the `-q` (quiet) option to not be prompted to type "Y" or "n", but that's new.

**Comment by ucefidel** [comment]
> Hi, same here, usually I use `php bin/console make:entity`, and now I'm getting 'Aborted' error message.
> So I tested with `symfony console make:entity` : same message.
> 
> I also tested with other commands which require an input (`make:unit-test`, `doctrine:fixtures:load`, `doctrine:migrations:migrate` where you have to press "Y" or "n" for instance), also "Aborted".
> 
> For now I just pass the `-q` (quiet) option to not be prompted to type "Y" or "n", but that's weird.
> 
> EDIT :
> PHP 7.4.0
> Symfony 4.4.1
> Git bash (same 'Aborted' message with classical Windows cmd)

I have the same problem, i tried many solutions like you but its not working. Did anyone find the solution please ?

**Comment by gundamftw** [comment]
> Hi, same here, usually I use `php bin/console make:entity`, and now I'm getting 'Aborted' error message.
> So I tested with `symfony console make:entity` : same message.
> 
> I also tested with other commands which require an input (`make:unit-test`, `doctrine:fixtures:load`, `doctrine:migrations:migrate` where you have to press "Y" or "n" for instance), also "Aborted".
> 
> For now I just pass the `-q` (quiet) option to not be prompted to type "Y" or "n", but that's weird.
> 
> EDIT :
> PHP 7.4.0
> Symfony 4.4.1
> Git bash (same 'Aborted' message with classical Windows cmd)
Hi I found the fix. The problem was caused by PHP 7.4.0, you'll need the latest PHP 7.4 development build that has the fix (they call it snapshots)

https://windows.php.net/snapshots/

The download link is currently down, just give it few hours and it should be up again.

**Comment by ld-web** [comment]
Just tested it, it works ! Thanks @gundamftw 

Tested on PHP7.4.0, Revision: r505cc77 (December 09 2019, 20:51:21), VC15 x64 Non Thread Safe

**Comment by werslybardales** [comment]
> Solo lo probé, ¡funciona! Gracias @gundamftw
> 
> Probado en PHP7.4.0, Revisión: r505cc77 (09 de diciembre de 2019, 20:51:21), VC15 x64 Non Thread Safe

Thank you. It works well.

**Comment by tarakbz** [comment]
it was the php version , it work now
