### ISSUE TITLE
Mailer Transports to SMTP Cannot Establish Secure Connections

### ISSUE THREAD

**Issue by brandonsavage** [symfony/symfony#34846]
**Symfony version(s) affected**: 5.0.1

**Description**  
When using the Transport out of the box, the Transport is unable to establish a secure connection. This issue looks similar to https://github.com/symfony/symfony/issues/34064

I am using OpenSSL 1.1.1d and PHP 7.4. I've reproduced the issue on PHP 7.3 as well.

The exact error message I receive is:

```Connection could not be established with host "ssl://smtp.postmarkapp.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number```

**How to reproduce**  
```php
$transport = new PostmarkSmtpTransport($key);
$mailer = new Mailer($transport);
$mail = (new Email)->to('test@example.com')
->from('test@example.com')
->subject('Test Email')
->html('Test Email');
$mailer->send($mail);
```

**Comment by fabpot** [comment]
maybe fixed by #34760?

**Comment by brandonsavage** [comment]
I applied the patch in #34760 without success in resolving this bug.

**Comment by kbsanders** [comment]
I am experiencing this exact same issue using the following SMTP transport:

```php
$transport = new EsmtpTransport('smtp.office365.com',587,true);
```

The error received is:

`
Connection could not be established with host "ssl://smtp.office365.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
`

I am using Symfony version 5.0.1 and PHP version 7.3.11.
I am also using the localhost Symfony web server for development.

The patch mentioned above did not help to correct the issue.

**Comment by kbsanders** [comment]
**Update:**

I ran my code again, but this time with the TLS option set to `false` and the patch above applied and the transport actually succeeded.

```php
$transport = new EsmtpTransport('smtp.office365.com',587,false);
```

However, when the patch is not applied, and TLS = `false`, I receive the following error:

`Warning: fgets(): SSL: An existing connection was forcibly closed by the remote host. in C:\arwa\site-alruralwater\vendor\symfony\mailer\Transport\Smtp\Stream\AbstractStream.php (line 77) `

Does this working with TLS = `false` perhaps have something to do with TLS vs STARTTLS?

**Comment by toooni** [comment]
@kbsanders But is the mail actually being sent? I can confirm that the error persists even with #34760. Setting TLS to false does indeed not result in the mentioned error and everything seems fine at first. But no mail is sent (no incoming mail on gmail nor activity visible on postmark).

**Comment by kbsanders** [comment]
@toooni I believe it was working for me, but I ended up switching to Swift Mailer for the time being until Mailer matures a bit more. I could never get Mailer to work with TLS. Swift Mailer has no issues with TLS.

**Comment by fabpot** [comment]
To be clear, you should use `465, true` to use SSL to connect or `587, false` to connect withou SSL and upgrade via STARTTLS. Any other combination won't work. The code was buggy, fixing it here:

**Comment by cengizgoren** [comment]
> To be clear, you should use `465, true` to use SSL to connect or `587, false` to connect withou SSL and upgrade via STARTTLS. Any other combination won't work. The code was buggy, fixing it here:  @fabpot   you're a genius.        .. 

this solved my problem. i even told this solution to one.com    support  . thanks again

**Comment by bestvayne** [comment]
> To be clear, you should use `465, true` to use SSL to connect or `587, false` to connect without SSL and upgrade via STARTTLS. Any other combination won't work. The code was buggy, fixing it here:

yes, 465 is right , I use mailgun service in Laravel 7.X, the error is "Connection could not be established with host smtp.mailgun.org:stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number"

and I use 465 replace Laravel init 587, the mistake was solved.

**Comment by hanzallahmsd** [comment]
> To be clear, you should use `465, true` to use SSL to connect or `587, false` to connect withou SSL and upgrade via STARTTLS. Any other combination won't work. The code was buggy, fixing it here:

I am also getting the same error. Where I will put these values?

**Comment by hanzallahmsd** [comment]
My SMTP Settings look like this

MAIL_MAILER=smtp
MAIL_HOST=smtpout.secureserver.net
MAIL_PORT=587
MAIL_USERNAME=me@mysite.com
MAIL_PASSWORD=MyPassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=hanzallah@mysite.com
MAIL_FROM_NAME="${APP_NAME}"

**Comment by hanzallahmsd** [comment]
Pasting some part of the error.

[2022-08-27 08:05:13] local.ERROR: Connection could not be established with host "ssl://smtpout.secureserver.net:465": stream_socket_client(): Unable to connect to ssl://smtpout.secureserver.net:465 (Connection timed out) {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"ssl://smtpout.secureserver.net:465\": stream_socket_client(): Unable to connect to ssl://smtpout.secureserver.net:465 (Connection timed out) at /var/www/mysite.com/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)
[stacktrace]
#0 [internal function]: Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream->Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\{closure}()
#1 /var/www/mysite.com/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php(157): stream_socket_client()
#2 /var/www/mysite.com/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(253): Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream->initialize()
#3 /var/www/mysite.com/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(192): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->start()
#4 /var/www/mysite.com/vendor/symfony/mailer/Transport/AbstractTransport.php(68): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#5 /var/www/mysite.com/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#6 /var/www/mysite.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
#7 /var/www/mysite.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285): Illuminate\\Mail\\Mailer->sendSymfonyMessage()

**Comment by bitfactory-edo-freriks** [comment]
@hanzallahmsd did you try 

``` MAIL_ENCRYPTION=starttls ```

**Comment by maynor96** [comment]
> starttls

it worked for me!

**Comment by prodev711** [comment]
MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=587
MAIL_USERNAME=myuser
MAIL_PASSWORD=mypass
MAIL_ENCRYPTION=STARTTLS

When I set env values like this, there is no error. but email not send to target email.
