### ISSUE TITLE
After a fresh install, a cache:clear is required and it's not effective without a wget + sleep before.

### ISSUE THREAD

**Issue by MaharishiCanada** [symfony/symfony#35932]
**Symfony version(s) affected**: 5.0.x

**Description**  

After a fresh install of  `symfony/skeleton` + `annotations` + a minimal code that do a simple route, a cache:clear is required. Moreover, the cache:clear fails if we don't do a previous wget or the equivalent and then sleep a bit before clearing the cache. 

**How to reproduce**  

This occurs on Ubuntu 19.10.  I put this code in `.../www/bug_app_ressources/src/Controller/TestController.php`

```
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class TestController extends AbstractController
{
    /**
     * @Route("/test", name="test")
     */
    public function test()
    {
        return new Response(
            '<html><body>It\'s a test</body></html>'
        ); 
    }
}

```
and used this script to experiment:

```
cd /home/working/www
composer create-project symfony/skeleton bug_app
cd bug_app
composer require annotations
symfony server:ca:install
cp -p /home/working/www/bug_app_ressources/src/Controller/TestController.php ./src/Controller/
symfony serve -d 
# Issue: The app does not work unless we do a cache:clear.  
# Moreover, a wget followed by sleep is required for the cache:clear to be 
# effective.  Remove any of the three following commands to see that the 
# app will always fail. Depending on your environment, you might need to 
# increase the sleeping time to make it work.
wget https://localhost:8000/test
sleep .5
bin/console cache:clear -vvv
# After wget + sleep + cache:clear, depending on your environment, the next 
# wget to work might not occur immediately.
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
symfony server:stop

```
**Additional context**  

It's only bugging me when I write a script to install different environments from scratch to experiment with Symfony. The work around is already in the script that is given above.

**Comment by MaharishiCanada** [comment]
Issue disappeared after installing libnss3-tools.

**Comment by MaharishiCanada** [comment]
This issue also occurs and is worst with nginx.  It may be specific to Ubuntu, though.

**Comment by nicolas-grekas** [comment]
We had a look with @guillbdx, these lines might be at fault:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L71-L72

Despite what the comment says, the cache for routes is not refreshed when $currentDir === $cacheDir.

**Comment by MaharishiCanada** [comment]
To test this hypothesis, I added this line to the script:

```
sed -i 's/force cache generation/force cache generation\n\t$cacheDir .= "_changed";/g' vendor/symfony/framework-bundle/Routing/Router.php
```

It made no difference. I also changed `$currentDir` instead. It also made no difference. Also no difference when I changed both. In all these cases, the app works, but only when we clear the cache after a wget and a sleep.  

On the other hand, what worked is a simple `rm -R var/cache/dev` instead of

```
wget https://localhost:8000/test
sleep .5
bin/console cache:clear -vvv
```
I have a question. Why do we need to clear the cache after a fresh install? Is it the expected behavior?

**Comment by guillbdx** [comment]
Hi @MaharishiCanada There's no need to explicitely execute cache:clear command after composer create-project symfony/skeleton or after composer require annotations because it is done automatically at the end of these commands.

Furthermore, in debug mode, when a url is fetched (for example calling it from a browser, or calling it with wget), if the framework detects a new file, it will regenerate the cache as well. Issue here is that the routing cache was not properly warmed up. The PR should fix that.

**Comment by MaharishiCanada** [comment]
I still have the same issue with the patched code. Moreover, in the old fashioned way, I added an echo statement in the patched code and this echo statement is not executed until after I explicitly clear the cache  in the script.

**Comment by guillbdx** [comment]
Hi @MaharishiCanada How did you apply the patch? It's not released yet so `composer create-project` won't provide it. Do you copy the new version into the symfony vendor? Can you provide a new reproducer please ? Below is a code that should work fine. It applies the patch by copying the file `Router.php` (which contains the patch) into symfony vendor:
```
composer create-project symfony/skeleton bug_app
cp -f Router.php bug_app/vendor/symfony/framework-bundle/Routing/Router.php
cd bug_app
composer require annotations
symfony server:ca:install
cp -p ../TestController.php ./src/Controller/
symfony serve -d
```
After running this script, url /test should work fine, without requiring any cache clear.

**Comment by MaharishiCanada** [comment]
That's close to what I did and I took the Router.php file from https://raw.githubusercontent.com/symfony/symfony/5.0/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php. The difference is in the order of the statements. I copied Router.php just before I started the server, at the same time I copied the Controller.  Let me check if it makes a difference. I guess it will.
