### ISSUE TITLE
"Circular reference detected" when creating a second secret for the prod env

### ISSUE THREAD

**Issue by picks44** [symfony/symfony#37142]
**Symfony version(s) affected**: 5.1.0

**Description**  
Got a Circular reference error when adding a second secret for the prod env. No problems in dev or staging env...

```
Fatal error: Symfony\Component\DependencyInjection\Exception\ParameterCircularRe
ferenceException: Circular reference detected for parameter "env(base64:default:
:SYMFONY_DECRYPTION_SECRET)" ("env(base64:default::SYMFONY_DECRYPTION_SECRET)" >
 "env(default::SYMFONY_DECRYPTION_SECRET)" > "env(SYMFONY_DECRYPTION_SECRET)" >
"env(base64:default::SYMFONY_DECRYPTION_SECRET)"). in C:\laragon\www\DESmdc\vend
or\symfony\dependency-injection\Container.php:389
Stack trace:
#0 C:\laragon\www\DESmdc\vendor\symfony\string\LazyString.php(41): Symfony\Compo
nent\DependencyInjection\Container->getEnv('base64:default:...')
#1 C:\laragon\www\DESmdc\vendor\symfony\string\LazyString.php(103): Symfony\Comp
onent\String\LazyString::Symfony\Component\String\{closure}()
#2 C:\laragon\www\DESmdc\vendor\symfony\framework-bundle\Secrets\SodiumVault.php
(183): Symfony\Component\String\LazyString->__toString()
#3 C:\laragon\www\DESmdc\vendor\symfony\framework-bundle\Secrets\SodiumVault.php
(114): Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault->loadKeys()
 in C:\laragon\www\DESmdc\vendor\symfony\string\LazyString.php on line 116
```

**How to reproduce**  

- Migrated from 4.4 to 5.0 then 5.1.
- Created secrets in dev and staging env without any problem
- Removed them from the .env file
- Started created secrets for prod, first one OK
- Second one (tried with different keys) failed with the above error

**Comment by nicolas-grekas** [comment]
Can you please provide us with a simple reproducing app? Because I don't reproduce for now. Thanks.

**Comment by michaelotoole** [comment]
Im getting the same problem, but cannot reproduce it spinning up a new app, even with a project with exactly the same dependencies as the one with issues.

Exactly the same issue, one prod secret is fine, soon as the second is created the circular reference is detected.

**Comment by michaelotoole** [comment]
@nicolas-grekas Able to reproduce using the --full symfony project, but not the standard.
`symfony new project --full`
`bin/console secret:set --env=prod TEST`
`bin/console secret:set --env=prod TEST2`

**Comment by michaelotoole** [comment]
Narrowed the bug down to when the **symfony/monolog-bundle** is added as a dependency.

**Comment by picks44** [comment]
I posted about thsi on Symfony's Slack and other users also experiment this, so it doesn't seem to be an isolated problem.

**Comment by michaelotoole** [comment]
This has more information in #37281 

Seems as though the exception is thrown and caught, but not in php 7.3.

**Comment by picks44** [comment]
Using php 7.2 here

**Comment by jderusse** [comment]
because exception thrown in `__tostring` is handled and rethrown by custom handler that prevent reaching the `catch (ParameterCircularReferenceException $e)` in `EnvVarProcessor.php`.

This issue does not affect >= 7.4 which allows throwing exception in `__tostring` method.

**Comment by picks44** [comment]
Hi there, any plans to fix this in a near future? I guess there still are a lot of people using php 7.2 like myself!

**Comment by nicolas-grekas** [comment]
Thanks for the hints about __toString + exceptions. Fixed in #37464.

**Comment by picks44** [comment]
Hi @nicolas-grekas, I see this is merged in SF3;4, what about SF 4 and 5 ?

**Comment by nicolas-grekas** [comment]
It's already merged in all branches, have a look.

**Comment by bastien70** [comment]
Hello @nicolas-grekas , I'm on Symfony 5.1, with PHP 7.3, my recipes are up to date, and yet the problem persists, with the same error code

**Comment by nicolas-grekas** [comment]
It's not tagged yet, maybe that's why. You'll need to use 5.1.3 when released.

**Comment by bastien70** [comment]
Great ! Do you know when the update will be released?
