### ISSUE TITLE
[PropertyAccess] Can't access static property $lazyPropertiesNames on Doctrine proxies

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#37334]
**Symfony version(s) affected**: 5.1.2, and previous versions.

**Description**  

I'm having an issue with the PropertyAccessor component (while using the Serializer component) on an entity managed by Doctrine: `Accessing static property Proxies\__CG__\App\Entity\User::$lazyPropertiesNames as non static`

![Capture d’écran de 2020-06-18 12-27-48](https://user-images.githubusercontent.com/2103975/85013852-92be9c00-b165-11ea-8c68-f9f794c2af51.png)

I don't know if it comes from recent Doctrine updates or from Symfony itself, but some people got the issue on `schmittjoh/serializer`, see https://github.com/schmittjoh/serializer/issues/1209.

I've tried their workaround (downgrade `doctrime/orm` from 2.7.3 to 2.7.2) but this does not work.

Here is my `composer show` if it can helps:

```text
cboden/ratchet                      v0.4.2  PHP WebSocket library
doctrine/annotations                1.10.3  Docblock Annotations Parser
doctrine/cache                      1.10.1  PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongo...
doctrine/collections                1.6.5   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     2.13.3  PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better...
doctrine/data-fixtures              1.4.3   Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       2.10.2  Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            2.1.0   Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle 3.0.1   Symfony DoctrineMigrationsBundle
doctrine/event-manager              1.1.0   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                  1.4.3   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural fo...
doctrine/instantiator               1.3.1   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 3.0.0   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your da...
doctrine/orm                        v2.7.3  Object-Relational-Mapper for PHP
doctrine/persistence                1.3.7   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 1.2.1   The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functionality on...
doctrine/sql-formatter              1.1.0   a PHP SQL highlighting library
egulias/email-validator             2.1.18  A library for validating emails against several RFCs
evenement/evenement                 v3.0.1  Événement is a very simple event dispatching library for PHP
firebase/php-jwt                    v5.2.0  A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
fzaninotto/faker                    v1.9.1  Faker is a PHP library that generates fake data for you.
guzzlehttp/psr7                     1.6.1   PSR-7 message implementation that also provides common utility methods
hautelook/alice-bundle              2.7.2   Symfony bundle to manage fixtures with Alice and Faker.
lcobucci/jwt                        3.3.2   A simple library to work with JSON Web Token and JSON Web Signature
monolog/monolog                     2.1.0   Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                   1.9.5   Create deep copies (clones) of your objects
nelmio/alice                        3.7.1   Expressive fixtures generator
nikic/php-parser                    v4.5.0  A PHP parser written in PHP
ocramius/package-versions           1.5.1   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.2.3   A library providing utilities to generate, instantiate and generally operate with Object Proxies
phpdocumentor/reflection-common     2.1.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   5.1.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded i...
phpdocumentor/type-resolver         1.1.0   A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                1.0.0   Standard interfaces for event handling.
psr/http-message                    1.0.1   Common interface for HTTP messages
psr/link                            1.0.0   Common interfaces for HTTP links
psr/log                             1.1.3   Common interface for logging libraries
ralouphie/getallheaders             3.0.3   A polyfill for getallheaders.
ratchet/rfc6455                     v0.2.6  RFC6455 WebSocket protocol handler
react/cache                         v1.0.0  Async, Promise-based cache interface for ReactPHP
react/dns                           v1.2.0  Async DNS resolver for ReactPHP
react/event-loop                    v1.1.1  ReactPHP's core reactor event loop that libraries can use for evented I/O.
react/promise                       v2.8.0  A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer                 v1.5.1  A trivial implementation of timeouts for Promises, built on top of ReactPHP.
react/socket                        v1.4.0  Async, streaming plaintext TCP/IP and secure TLS socket server and client connections for ReactPHP
react/stream                        v1.1.1  Event-driven readable and writable streams for non-blocking I/O in ReactPHP
sebastian/comparator                4.0.2   Provides the functionality to compare PHP values for equality
sebastian/diff                      4.0.1   Diff implementation
sebastian/exporter                  4.0.1   Provides the functionality to export PHP variables for visualization
sebastian/recursion-context         4.0.1   Provides functionality to recursively process PHP variables
sensio/framework-extra-bundle       v5.5.6  This bundle provides a way to configure your controllers with annotations
symfony/asset                       v5.1.2  Symfony Asset Component
symfony/browser-kit                 v5.1.2  Symfony BrowserKit Component
symfony/cache                       v5.1.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts             v2.1.2  Generic abstractions related to caching
symfony/config                      v5.1.2  Symfony Config Component
symfony/console                     v5.1.2  Symfony Console Component
symfony/css-selector                v5.1.2  Symfony CssSelector Component
symfony/debug-bundle                v5.1.2  Symfony DebugBundle
symfony/debug-pack                  v1.0.8  A debug pack for Symfony projects
symfony/dependency-injection        v5.1.2  Symfony DependencyInjection Component
symfony/deprecation-contracts       v2.1.2  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge             v5.1.2  Symfony Doctrine Bridge
symfony/dom-crawler                 v5.1.2  Symfony DomCrawler Component
symfony/dotenv                      v5.1.2  Registers environment variables from a .env file
symfony/error-handler               v5.1.2  Symfony ErrorHandler Component
symfony/event-dispatcher            v5.1.2  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v2.1.2  Generic abstractions related to dispatching event
symfony/expression-language         v5.1.2  Symfony ExpressionLanguage Component
symfony/filesystem                  v5.1.2  Symfony Filesystem Component
symfony/finder                      v5.1.2  Symfony Finder Component
symfony/flex                        v1.8.4  Composer plugin for Symfony
symfony/form                        v5.1.2  Symfony Form Component
symfony/framework-bundle            v5.1.2  Symfony FrameworkBundle
symfony/http-client                 v5.1.2  Symfony HttpClient component
symfony/http-client-contracts       v2.1.2  Generic abstractions related to HTTP clients
symfony/http-foundation             v5.1.2  Symfony HttpFoundation Component
symfony/http-kernel                 v5.1.2  Symfony HttpKernel Component
symfony/inflector                   v5.1.2  Symfony Inflector Component
symfony/intl                        v5.1.2  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                      v5.1.2  Symfony Mailer Component
symfony/maker-bundle                v1.19.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate ...
symfony/mime                        v5.1.2  A library to manipulate MIME messages
symfony/monolog-bridge              v5.1.2  Symfony Monolog Bridge
symfony/monolog-bundle              v3.5.0  Symfony MonologBundle
symfony/notifier                    v5.1.2  A library to notify messages
symfony/options-resolver            v5.1.2  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge              v5.1.2  Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme      v1.17.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu           v1.17.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn           v1.17.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer    v1.17.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           v1.17.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73              v1.17.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80              v1.17.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                     v5.1.2  Symfony Process Component
symfony/profiler-pack               v1.0.4  A pack for the Symfony web profiler
symfony/property-access             v5.1.2  Symfony PropertyAccess Component
symfony/property-info               v5.1.2  Symfony Property Info Component
symfony/routing                     v5.1.2  Symfony Routing Component
symfony/security-bundle             v5.1.2  Symfony SecurityBundle
symfony/security-core               v5.1.2  Symfony Security Component - Core Library
symfony/security-csrf               v5.1.2  Symfony Security Component - CSRF Library
symfony/security-guard              v5.1.2  Symfony Security Component - Guard
symfony/security-http               v5.1.2  Symfony Security Component - HTTP Integration
symfony/serializer                  v5.1.2  Symfony Serializer Component
symfony/serializer-pack             v1.0.3  A pack for the Symfony serializer
symfony/service-contracts           v2.1.2  Generic abstractions related to writing services
symfony/stopwatch                   v5.1.2  Symfony Stopwatch Component
symfony/string                      v5.1.2  Symfony String component
symfony/test-pack                   v1.0.6  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                 v5.1.2  Symfony Translation Component
symfony/translation-contracts       v2.1.2  Generic abstractions related to translation
symfony/twig-bridge                 v5.1.2  Symfony Twig Bridge
symfony/twig-bundle                 v5.1.2  Symfony TwigBundle
symfony/twig-pack                   v1.0.0  A Twig pack for Symfony projects
symfony/validator                   v5.1.2  Symfony Validator Component
symfony/var-dumper                  v5.1.2  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v5.1.2  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                    v5.1.2  Symfony WebLink Component
symfony/web-profiler-bundle         v5.1.2  Symfony WebProfilerBundle
symfony/webpack-encore-bundle       v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                        v5.1.2  Symfony Yaml Component
theofidry/alice-data-fixtures       v1.1.2  Nelmio alice extension to persist the loaded fixtures.
twig/extra-bundle                   v3.0.3  A Symfony bundle for extra Twig extensions
twig/twig                           v3.0.3  Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.9.0   Assertions to validate method input/output with nice error messages.
zendframework/zend-code             3.4.1   Extensions to the PHP Reflection API, static code scanning, and code generation
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application
```

**How to reproduce**  

Unfortunately I can't send a reproducer right now, I'm in a big rush until saturday night.

However @jannmylj posted a reproducer (https://github.com/schmittjoh/serializer/issues/1209#issuecomment-637445190), you may be able to reproducible the issue with the code adapted for the Serializer component.

**Possible Solution**  

I've opened a PR to support static properties, see #37335. 

I'm not sure this is the real solution, maybe Doctrine-related properties should be ignored by the `Serializer` component... I don't know at all :confused: 

**Additional context**  

No.

**Comment by fabpot** [comment]
https://github.com/schmittjoh/serializer/pull/1210 fixed it by updating the code to use the newest Doctrine classes. I think we did the same recently on Symfony, can someone tell me if the problem is now fixed?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Geekimo** [comment]
Hello,
I've just ran into this issue with Symfony 5.2
I tried to serialize an Entity which had a Doctrine proxy as of one of his properties.
`> composer show`
```
clue/stream-filter                    v1.5.0    A simple and modern approach to stream filtering in PHP
composer/package-versions-deprecated  1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
doctrine/annotations                  1.11.1    Docblock Annotations Parser
doctrine/cache                        1.10.2    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                  1.6.7     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                       3.1.0     PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, proxies and much more.
doctrine/data-fixtures                1.4.4     Data Fixtures for all Doctrine Object Managers
doctrine/dbal                         2.12.1    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle              2.2.2     Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle     3.4.0     Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle   3.0.2     Symfony DoctrineMigrationsBundle
doctrine/event-manager                1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                    2.0.3     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                 1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                   3.0.2     PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. ...
doctrine/orm                          2.8.1     Object-Relational-Mapper for PHP
doctrine/persistence                  2.1.0     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter                1.1.1     a PHP SQL highlighting library
egulias/email-validator               2.1.25    A library for validating emails against several RFCs
excelwebzone/recaptcha-bundle         v1.5.25   This bundle provides easy reCAPTCHA form field integration
ezyang/htmlpurifier                   v4.13.0   Standards compliant HTML filter written in PHP
friendsofphp/proxy-manager-lts        v1.0.1    Adding support for a wider range of PHP versions to ocramius/proxy-manager
friendsofsymfony/jsrouting-bundle     2.7.0     A pretty nice way to expose your Symfony2 routing to client applications.
fzaninotto/faker                      v1.9.2    Faker is a PHP library that generates fake data for you.
giggsey/libphonenumber-for-php        8.12.15   PHP Port of Google's libphonenumber
giggsey/locale                        1.9       Locale functions required by libphonenumber-for-php
google/recaptcha                      1.2.4     Client library for reCAPTCHA, a free service that protects websites from spam and abuse.
guzzlehttp/psr7                       1.7.0     PSR-7 message implementation that also provides common utility methods
imagine/imagine                       1.2.4     Image processing for PHP 5.3
laminas/laminas-code                  4.0.0     Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager          3.3.0     Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge  1.1.1     Alias legacy ZF class names to Laminas Project equivalents.
liip/imagine-bundle                   2.4.0     This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
maennchen/zipstream-php               2.1.0     ZipStream is a library for dynamically streaming dynamic zip files from PHP without writing to the disk at all on the server.
markbaker/complex                     2.0.0     PHP Class for working with complex numbers
markbaker/matrix                      2.0.0     PHP Class for working with matrices
monolog/monolog                       2.2.0     Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                     1.10.2    Create deep copies (clones) of your objects
myclabs/php-enum                      1.7.7     PHP Enum implementation
nikic/php-parser                      v4.10.4   A PHP parser written in PHP
nikolaposa/version                    3.2.0     Value Object that represents a SemVer-compliant version number.
odolbeau/phone-number-bundle          v3.2.1    Integrates libphonenumber into your Symfony application
php-http/discovery                    1.13.0    Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                      2.2.0     HTTPlug, the HTTP client abstraction for PHP
php-http/message                      1.10.0    HTTP Message related tools
php-http/message-factory              v1.0.2    Factory interfaces for PSR-7 HTTP Message
php-http/promise                      1.1.0     Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common       2.2.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     5.2.2     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           1.4.0     A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoffice/phpspreadsheet              1.16.1    PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
psr/cache                             1.0.1     Common interface for caching libraries
psr/container                         1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                  1.0.0     Standard interfaces for event handling.
psr/http-client                       1.0.1     Common interface for HTTP clients
psr/http-factory                      1.0.1     Common interfaces for PSR-7 HTTP message factories
psr/http-message                      1.0.1     Common interface for HTTP messages
psr/link                              1.0.0     Common interfaces for HTTP links
psr/log                               1.1.3     Common interface for logging libraries
psr/simple-cache                      1.0.1     Common interfaces for simple caching
ralouphie/getallheaders               3.0.3     A polyfill for getallheaders.
sensio/framework-extra-bundle         v5.6.1    This bundle provides a way to configure your controllers with annotations
shivas/versioning-bundle              3.2.3     Symfony3|4 application versioning, simple console command to manage version (with providers e.g. git tag) of your application using Semantic Versioning 2.0.0 recommendations
stripe/stripe-php                     v7.67.0   Stripe PHP Library
symfony-bundles/json-request-bundle   v3.1.1    Symfony JsonRequest Bundle
symfony/asset                         v5.2.1    Symfony Asset Component
symfony/browser-kit                   v5.2.1    Symfony BrowserKit Component
symfony/cache                         v5.2.1    Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts               v2.2.0    Generic abstractions related to caching
symfony/config                        v5.2.1    Symfony Config Component
symfony/console                       v5.2.1    Symfony Console Component
symfony/css-selector                  v5.2.1    Symfony CssSelector Component
symfony/debug-bundle                  v5.2.1    Symfony DebugBundle
symfony/debug-pack                    v1.0.9    A debug pack for Symfony projects
symfony/dependency-injection          v5.2.1    Symfony DependencyInjection Component
symfony/deprecation-contracts         v2.2.0    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge               v5.2.1    Symfony Doctrine Bridge
symfony/dom-crawler                   v5.2.1    Symfony DomCrawler Component
symfony/dotenv                        v5.2.1    Registers environment variables from a .env file
symfony/error-handler                 v5.2.1    Symfony ErrorHandler Component
symfony/event-dispatcher              v5.2.1    Symfony EventDispatcher Component
symfony/event-dispatcher-contracts    v2.2.0    Generic abstractions related to dispatching event
symfony/expression-language           v5.2.1    Symfony ExpressionLanguage Component
symfony/filesystem                    v5.2.1    Symfony Filesystem Component
symfony/finder                        v5.2.1    Symfony Finder Component
symfony/flex                          v1.11.0   Composer plugin for Symfony
symfony/form                          v5.2.1    Symfony Form Component
symfony/framework-bundle              v5.2.1    Symfony FrameworkBundle
symfony/http-client                   v5.2.1    Symfony HttpClient component
symfony/http-client-contracts         v2.3.1    Generic abstractions related to HTTP clients
symfony/http-foundation               v5.2.1    Symfony HttpFoundation Component
symfony/http-kernel                   v5.2.1    Symfony HttpKernel Component
symfony/intl                          v5.2.1    A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                        v5.2.1    Symfony Mailer Component
symfony/maker-bundle                  v1.26.1   Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                          v5.2.1    A library to manipulate MIME messages
symfony/monolog-bridge                v5.2.1    Symfony Monolog Bridge
symfony/monolog-bundle                v3.6.0    Symfony MonologBundle
symfony/notifier                      v5.2.1    A library to notify messages
symfony/options-resolver              v5.2.1    Symfony OptionsResolver Component
symfony/orm-pack                      v2.1.0    A pack for the Doctrine ORM
symfony/phpunit-bridge                v5.2.1    Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme        v1.20.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu             v1.20.0   Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn             v1.20.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer      v1.20.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring             v1.20.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73                v1.20.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                v1.20.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                       v5.2.1    Symfony Process Component
symfony/profiler-pack                 v1.0.5    A pack for the Symfony web profiler
symfony/property-access               v5.2.1    Symfony PropertyAccess Component
symfony/property-info                 v5.2.1    Symfony Property Info Component
symfony/proxy-manager-bridge          v5.2.1    Symfony ProxyManager Bridge
symfony/routing                       v5.2.1    Symfony Routing Component
symfony/security-bundle               v5.2.1    Symfony SecurityBundle
symfony/security-core                 v5.2.1    Symfony Security Component - Core Library
symfony/security-csrf                 v5.2.1    Symfony Security Component - CSRF Library
symfony/security-guard                v5.2.1    Symfony Security Component - Guard
symfony/security-http                 v5.2.1    Symfony Security Component - HTTP Integration
symfony/serializer                    v5.2.1    Symfony Serializer Component
symfony/serializer-pack               v1.0.4    A pack for the Symfony serializer
symfony/service-contracts             v2.2.0    Generic abstractions related to writing services
symfony/stopwatch                     v5.2.1    Symfony Stopwatch Component
symfony/string                        v5.2.1    Symfony String component
symfony/templating                    v5.2.1    Symfony Templating Component
symfony/test-pack                     v1.0.7    A pack for functional and end-to-end testing within a Symfony app
symfony/translation                   v5.2.1    Symfony Translation Component
symfony/translation-contracts         v2.3.0    Generic abstractions related to translation
symfony/twig-bridge                   v5.2.1    Symfony Twig Bridge
symfony/twig-bundle                   v5.2.1    Symfony TwigBundle
symfony/twig-pack                     v1.0.1    A Twig pack for Symfony projects
symfony/validator                     v5.2.1    Symfony Validator Component
symfony/var-dumper                    v5.2.1    Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                  v5.2.1    A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                      v5.2.1    Symfony WebLink Component
symfony/web-profiler-bundle           v5.2.1    Symfony WebProfilerBundle
symfony/webpack-encore-bundle         v1.8.0    Integration with your Symfony app & Webpack Encore!
symfony/workflow                      v5.2.1    Symfony Workflow Component
symfony/yaml                          v5.2.1    Symfony Yaml Component
thecodingmachine/gotenberg-php-client 6.2.0     A client for sending files to a Gotenberg API
thecodingmachine/safe                 v1.3.3    PHP core functions that throw exceptions instead of returning FALSE on error
twig/extra-bundle                     v3.1.1    A Symfony bundle for extra Twig extensions
twig/intl-extra                       v3.1.1    A Twig extension for Intl
twig/twig                             v3.1.1    Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                      1.9.1     Assertions to validate method input/output with nice error messages.
willdurand/jsonp-callback-validator   v1.1.0    JSONP callback validator.
```
Here's the dump of the entity where we can see the proxy.
![image](https://user-images.githubusercontent.com/543693/103425231-4989e300-4bb1-11eb-83b2-31e99ce670ee.png)

If you need more informations don't hesitate to ask.

**Comment by Kocal** [comment]
@Geekimo if you need a workaround you can create a custom normalizer for your User entity

**Comment by Geekimo** [comment]
@Kocal I've thinked about that, but this behavious may not be limited to this particular entity ?
Proxied entities are not resolved due to the use of the property accessor I think ? I wonder how we can manage that...

**Comment by Geekimo** [comment]
I just added a few properties to the ignored_attributes, and now it works.
![image](https://user-images.githubusercontent.com/543693/103426940-80fe8c80-4bbd-11eb-84e1-3c4ee18d0a72.png)

**Comment by pcholewa** [comment]
> I just added a few properties to the ignored_attributes, and now it works.
> ![image](https://user-images.githubusercontent.com/543693/103426940-80fe8c80-4bbd-11eb-84e1-3c4ee18d0a72.png)

Please tell me, where exacly You added that?

**Comment by Geekimo** [comment]
This is part of the context that you can pass to a serializer.

**Comment by pcholewa** [comment]
Can I add that to global config serializer?

**Comment by Geekimo** [comment]
I don't know.

**Comment by mvaljento** [comment]
> Can I add that to global config serializer?

This is how I do it. I have a separate Serializer class, which takes care of the ignored attributes:

`
class MySerializer {

	protected const IGNORED_ATTRIBUTES = [
		'password',
		'userhash',
		'token',
		'tokenExpires',
		'reminderToken',
		'reminderExpires',
		'__cloner__',
		'__initializer__',
		'__isInitialized__',
		'lazyPropertiesNames',
		'lazyPropertiesDefaults',
		'transitions',
	];

	public function normalize($obj) {
		$serializer = new Serializer([new DateTimeNormalizer(), new ObjectNormalizer()]);
		return $serializer->normalize($obj, null, [
			'circular_reference_handler' => function ($object) {
				return $object->getId();
			},
			'ignored_attributes' => self::IGNORED_ATTRIBUTES
		]);
	}

}
`

And I use it in my Controllers like so:

`
public function idAction($id, InvoiceService $service, MySerializer $serializer) {
		return $serializer->normalize($service->getById($id));
	}
`

**Comment by fl0cke** [comment]
I just got this error in a fresh Symfony project. Seems like a pretty big deal to me if i can't use the serializer with regular entities anymore?!

**Comment by Kocal** [comment]
The problem can be solved by creating normalizers for your entities.

**Comment by fl0cke** [comment]
There are many ways to work around this problem, but i don't think it is the intended behavior of the serializer, or is it? If not, the issue should be re-opened.

**Comment by VincentChalnot** [comment]
Problem is still here with Sf 5.2 using the standard symfony/serializer. Creating custom normalizers for each entity doesn't sounds like a fix to me.

```
[...]
doctrine/annotations                  1.12.1     MIT           
doctrine/cache                        1.10.2     MIT           
doctrine/collections                  1.6.7      MIT           
doctrine/common                       3.1.2      MIT           
doctrine/dbal                         2.13.0     MIT           
doctrine/deprecations                 v0.5.3     MIT           
doctrine/doctrine-bundle              2.3.1      MIT           
doctrine/doctrine-migrations-bundle   3.1.1      MIT           
doctrine/event-manager                1.1.1      MIT           
doctrine/inflector                    2.0.3      MIT           
doctrine/instantiator                 1.4.0      MIT           
doctrine/lexer                        1.2.1      MIT           
doctrine/migrations                   3.1.1      MIT           
doctrine/orm                          2.8.4      MIT           
doctrine/persistence                  2.1.0      MIT           
doctrine/sql-formatter                1.1.1      MIT
[...]
symfony/serializer                    v5.2.4     MIT
[...]
```

**Comment by nikserg** [comment]
Upvoting here, still got this annoying problem.

**Comment by AntonioCS** [comment]
I've just been hit by this issue on a project running Symfony 5.2
```
Notice: Accessing static property Proxies\__CG__\App\Entity\Brand::$lazyPropertiesNames as non static
```

Relevant data from `composer show`:
```
doctrine/annotations                 1.13.1             Docblock Annotations Parser
doctrine/cache                       2.0.3              PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.7              PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.1.2              PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection suppo...
doctrine/data-fixtures               1.5.0              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        2.13.x-dev 2f286f4 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                v0.5.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle             2.4.2              Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle    3.4.0              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  3.1.1              Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1              The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.3              PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.1.3              PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and...
doctrine/orm                         2.9.2              Object-Relational-Mapper for PHP
doctrine/persistence                 2.2.1              The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter   
....
symfony/serializer                   v5.2.10   
```

**Comment by xabbuh** [comment]
We still need an example application that allows to reproduce this issue.

**Comment by AntonioCS** [comment]
@xabbuh Unfortunately I'm working on proprietary code so I can't share the whole application but the class where I'm seeing that is:

```
/**
 * @ORM\Entity(repositoryClass=BrandRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Brand
{
    use HasEntityStandardFields;
    use HasClient;
    use HasIsSynced;
    use HasUuid;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Ignore
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameCanonical;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNameCanonical(): ?string
    {
        return $this->nameCanonical;
    }

    public function setNameCanonical(string $nameCanonical): self
    {
        $this->nameCanonical = $nameCanonical;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function canonicalNameSetup(): void
    {
        $canonicalName = str_replace(
                            ['.', ' '],
                            '.',
                            strtolower($this->getNameCanonical() ?? $this->getName())
        );

        $this->setNameCanonical($canonicalName);
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}
```

the traits are:

```
trait HasClient
{
    /**
     * @ORM\ManyToOne(targetEntity=Client::class)
     */
    private ?Client $client = null;

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}
```

```
trait HasEntityStandardFields
{
    /**
     * @var DateTime $createdAt
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    protected $createdAt;

    /**
     * @var DateTime $updatedAt
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     */
    protected $updatedAt;

    /**
     * @var bool $isDeleted
     *
     * @ORM\Column(name="is_deleted", type="boolean", nullable=false)
     */
    protected $isDeleted = false;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');

        $this->setUpdatedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }

    public function getCreatedAt() :?DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt() :?DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }
}
```

```
trait HasIsSynced
{
    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isSynced = false;

    public function getIsSynced(): bool
    {
        return $this->isSynced;
    }

    public function setIsSynced(bool $isSynced): self
    {
        $this->isSynced = $isSynced;

        return $this;
    }
}
```

**Comment by AntonioCS** [comment]
Well.. I'm not sure this is related directly with this class.. 
I am serializing a bunch of classes.
Basically getting all `doctrine` entities (using: `$meta = $this->entityManager->getMetadataFactory()->getAllMetadata();`) 
and then filtering the ones I want (based on association and certain fields).
I've just changed the code to JUST return the `Brand` class and the serializer had no issue with it....
Can this be some sort of accumulation of previous values in the `PropertyAccessor` class??

**Comment by xabbuh** [comment]
Well, without being able to reproduce it will not really be possible to fix the issue.

**Comment by AntonioCS** [comment]
Well... it's not like it's only coming from me.... but yeah... great....

**Comment by VincentChalnot** [comment]
I had this issue not so long ago, I will try to reproduce it if I can.

**Comment by xabbuh** [comment]
@AntonioCS PR welcome from anyone experiencing the issue if you have an idea how to fix this.

**Comment by AntonioCS** [comment]
@xabbuh What I've determined so far is that only doctrine proxy classes cause the issue. That is why when I returned only the `Brand` class the issues didn't occur, because doctrine gave me the real entity and not a proxy

**Comment by AntonioCS** [comment]
Well.. I fixed my stuff by using `createQueryBuilder`.
I basically did this:

```
...
//this is running in a foreach where I query multiple entities, hence the $e
....
 $queryBuilder = $this->entityManager->createQueryBuilder();
            $select = ['u'];
            $queryBuilder
                 ->from($e, 'u')
....
             ;

            $this->getAssociations($queryBuilder, $e, $select, 'u');
            $queryBuilder->select($select);
            $result = $queryBuilder->getQuery()->getResult();
....
    private function getAssociations(QueryBuilder $qb, string $classPath, array& $select, string $alias) : void
    {
        $md = $this->entityManager->getClassMetadata($classPath);
        $assoc = $md->getAssociationNames();

        foreach ($assoc as $a) {
            if ($a === 'parent')
                continue;

            if (!in_array($a, $select, true)) {
                $select[] = $a;
                $qb->join("$alias.$a", $a);
                $this->getAssociations($qb, $md->getAssociationTargetClass($a), $select, $a);
            }
        }
    }
```
`getAssociations` basically created a joins for all the associations and that forced doctrine to load everything.

The problem is still there in the serializer but I get what I need.

**Comment by okyselov** [comment]
My workaround for Symfony 5.
Kernel.php

```    
protected function build(ContainerBuilder $container)
    {
        parent::build($container);
        $container->addCompilerPass(new class implements CompilerPassInterface {
            public function process(ContainerBuilder $container)
            {
                $container->getDefinition('serializer.normalizer.object')->setArgument(6, [
                    AbstractNormalizer::IGNORED_ATTRIBUTES => ['__initializer__', '__cloner__', '__isInitialized__', 'lazyPropertiesNames', 'lazyPropertiesDefaults'],
                ]);
            }
        });
    }
```

**Comment by nicolas-grekas** [comment]
Please open issues if there is something to fix.

**Comment by AntonioCS** [comment]
@nicolas-grekas there is something to fix, as you saw from @okyselov fix, there is something going wrong with the serializer.
I've never delved into the compiler pass stuff but it seems that is what is required to fix it at the source
