### ISSUE TITLE
All kinds of weird bugs in Symfony with PHP 8

### ISSUE THREAD

**Issue by pavrip** [symfony/symfony#39582]
Just updated a new version of Symfony Server.

When I did symfony serve / symfony server:start

I am getting all kinds of weird bugs from the low level framework code which should not be happening and I should not be digging into the framework code as it could mess things up.

1) Compile Error: Cannot declare interface Stringable, because the name is already in use
in vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php (line 7)
I changed the name temporarily to Stringables but this is not a proper fix. When I did this I got another bug with Doctrine:

2) Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php (line 91)

I have changed the name of the Stringable interface for now but im not sure if this has a side effect.
As far as bug 2 goes I tried to change the method signature by adding the arguments but then it was incompatible with the same method in another interface:

Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) must be compatible with Doctrine\DBAL\Driver\Connection::query()

I apologise I am not very experienced with GitHub, I am not sure what code so the same problem can be reproduced, at the moment, as this is lower level framework code and nothing I have touched, it cant be anything to do with me and is a framework issue.
Im not sure what to do

**Comment by pavrip** [comment]
Just started using PHP 8 for the first time, and there are a host of problems with the underline framework.
Im not even able to download a new symfony project

**Comment by wouterj** [comment]
Hi!

The errors indicate that you did not run `composer update` at the same PHP version as you run the server. Doctrine DBAL 2.x does not support PHP 8 (and is thus not installable on PHP 8), while Doctrine DBAL 3.x **does** support PHP 8 and has fixed this signature error (2). So it seems like you're using Dbal 2.x. The first error has been fixed in symfony/polyfill-php80 version 1.19.0  (1.21 is the latest version).

Please run `composer update` on PHP 8 (be aware that not all packages in the Symfony ecosystem are currently supporting PHP 8, so you may not be able to migrate your project to PHP 8 yet, depending on which other packages you use).

For now, I'm closing this issue as the mentioned issues in here are already fixed. Please let me know if you have other problems and please note that you can community support on e.g. Slack or StackOverflow (see https://symfony.com/support for all available support options).

**Comment by pavrip** [comment]
Cant do symfony new project name --full also not working

**Comment by pavrip** [comment]
running composer update did not fix the problem.
I am not running DBAL 3X. 
Because I am getting the following error:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/doctrine-migrations-bundle 3.0.1 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - doctrine/doctrine-migrations-bundle 3.0.0 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - doctrine/doctrine-migrations-bundle 3.0.1 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - Installation request for doctrine/doctrine-migrations-bundle ^3.0 -> satisfiable by doctrine/doctrine-migrations-bundle[3.0.0, 3.0.1].

**Comment by maxhelias** [comment]
Because doctrine/doctrine-migrations-bundle doesn't support PHP 8 yet. Please wait for support and then do your migration

**Comment by pavrip** [comment]
So until then how can I continue to work with the project I am building?
Do I have to go back down to PHP7.4?
Because I have a deadline for the 24th and if I cant use this then I cant continue because the whole framework has crashed.

**Comment by pavrip** [comment]
Even the other updates for the Stringable interface did not work

**Comment by maxhelias** [comment]
With such a short date, it is better to avoid experiments and go back to 7.4.

**Comment by pavrip** [comment]
Thank you for your email. In my dev environment I already have 8.0
I removed the migrations bundle and then did composer update, it worked.
Now my choice is to either use php 8 without migrations but I am not sure if there will be any side effects.

Otherwise I will probably find a way to use 7.4 just for this project

**Comment by derrabus** [comment]
> Doctrine DBAL 2.x does not support PHP 8 (and is thus not installable on PHP 8)

Correction: Doctrine DBAL supports PHP 8 since version 2.12.

**Comment by derrabus** [comment]
> Cant do symfony new project name --full also not working

This is mainly due to external dependencies (Doctrine Migration and ProxyManager IIRC). We can't do much about it, but I'm sure that those projects will sort out their compatibility issues soon.

**Comment by pavrip** [comment]
Great

I don’t really need doctrine migrations,

If I don’t really need the proxy dependency I should be able to go ahead
with php8 right?

**Comment by derrabus** [comment]
Yes.

**Comment by pavrip** [comment]
Hi

I cant even remove doctrine/doctrine-migrations-bundle

I get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/persistence 2.0.0 requires php ^7.1 -> your PHP version
(8.0.0) does not satisfy that requirement.
    - doctrine/persistence 2.0.0 requires php ^7.1 -> your PHP version
(8.0.0) does not satisfy that requirement.
    - Installation request for doctrine/persistence (locked at 2.0.0) ->
satisfiable by doctrine/persistence[2.0.0].


Removal failed, reverting ./composer.json to its original content.

My whole project cant even go ahead because of a dependency I don't even
need.

Seems like the only option is to go back to 7.4 or get the skeleton
framework again.

Regards
Peshotan

**Comment by maxhelias** [comment]
If you have this error, it is because you are depend to doctrine. I have the impression that you are not in control of your dependencies...
Use `composer why doctrine/persistence` to know more about it

**Comment by chalasr** [comment]
Friendly reminder: Please, use our [support channels](https://symfony.com/support).

**Comment by pavrip** [comment]
Thanks I looked at it. Its starting to become a bit more clear now.
I initially downloaded a --full framework for my project,
Now PHP8 has automatically become the default. I only have one version
running.

I want to use the new PHP8, I dont want to be stuck on an old version.
All I really need is the DBAL and the ORM.
I dont need all the other jazz.
Maybe its best I start a new project and only work with the DBAL AND ORM?

Please do let me know what you think

Thank you for getting back to me its truly appreciated.

Best
Peshotan

**Comment by xabbuh** [comment]
I am sorry, but  we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
