### ISSUE TITLE
[Preloading] Hard time when using it for the first time in prod

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#47136]
### Symfony version(s) affected

6.1 & 5.4

### Description

We set up preloading last month in my company and experienced difficulties due to 2 opinionated choices in Symfony that may not be made on purpose.
We love Symfony as it is very helpful but the framework made us lose valuable time on this one so I'm reporting it.

The main issue was coming from this package that I fixed with this PR: https://github.com/assoconnect/validator-bundle/commit/7f93ee676a996e1bf0163ca84b8ecb1eca78d3dd
=> The package returns a directory instead of a file in the preloading list.

This leads to a `require [folder path here]` in the `App_Kernel*Container.preload.php` file which fails.

# First issue with `config/preload.php`
The first difficulty comes from the Symfony file `config/preload.php` that is actually only "active" for the `prod` env by default (https://github.com/symfony/recipes/blob/main/symfony/framework-bundle/6.2/config/preload.php)
* Some context: we defined a `staging` env which is very close to our `prod` env but with different secret values stored using https://symfony.com/doc/current/configuration/secrets.html
* We set up our staging env following https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading

=> Our QA team executed a lot of tests to prevent any regression but they weren't actually testing our new preloading setup because `config/preload.php` only works with the `prod` env

* 1st KO: As far as I know, this isn't stated anywhere in the Symfony doc
* 2nd KO: Symfony has a lot of magic that makes it incredibly easy to pick the right env (with a single `.env.local` file for instance) and this magic behavior is consistent across all the Symfony components & tools but not in this `config/preload.php` file which is truly misleading (it may sound stupid once you figure out how it works with OPCache but we learned it the hard way).

# Second issue with `App_Kernel*Container.preload.php`
Once we found out that our PHP-FPM service wasn't starting because of preloading issues, we tried to investigate the issue.
But running `php config/preload.php` locally won't actually show anything because of this early return at the beginning of the `App_Kernel*Container.preload.php` file
```
if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}
```
* 1st KO: You have to start a real PHP-FPM service to check if it's working or not which is not very dev friendly
* 2nd KO: You can't run a test suite out of the box with preloading enabled in some `*.ini` file to run the regression tests as close as possible as a true prod env (even if won't impact perfs)

### How to reproduce

Setup and deploy to prod a project with https://github.com/assoconnect/validator-bundle version 2.16.2 or before

### Possible Solution

Some suggestions here may be out of scope because I'm no expert of PHP preloading
* Ask people to use `var/cache/prod/App_KernelProdContainer.preload.php` instead of `config/preload.php` as it shows that the file actually depends on the Symfony `APP_ENV` & `APP_DEBUG` setup, or explain in the doc that the `config/preload.php` file is by default for `APP_ENV=prod` & `APP_DEBUG=0` and should be adapted for other envs or custom setups
* Remove the early return in the generated `App_Kernel*Container.preload.php` files, or add a comment to explain why it's here
* Check that files returned by https://github.com/symfony/http-kernel/blob/6.1/CacheWarmer/WarmableInterface.php#L26 actually exist when compiling the cache

**Comment by nicolas-grekas** [comment]
> Ask people to use var/cache/prod/App_KernelProdContainer.preload.php instead of config/preload.php as it shows that the file actually depends on the Symfony APP_ENV & APP_DEBUG setup, or explain in the doc that the config/preload.php file is by default for APP_ENV=prod & APP_DEBUG=0 and should be adapted for other envs or custom setups

The recipe ships `config/preload.php` in order to make it easy to deploy preloading with generic configuration on the host (always the same file to configure.)
Doc PR welcome to improve it of course!

> Remove the early return in the generated App_Kernel*Container.preload.php files, or add a comment to explain why it's here

Looks like we can do it, PR welcome, on 6.2 since this is not a bug fix.

> Check that files returned by [https://github.com/symfony/http-kernel/blob/6.1/CacheWarmer/WarmableInterface.php#L26](https://github.com/symfony/http-kernel/blob/6.1/CacheWarmer/WarmableInterface.php?rgh-link-date=2022-07-31T21%3A00%3A14Z#L26) actually exist when compiling the cache

This deserves a bugfix on 5.4, with an exception when failing to respect the contract I guess. PR welcome also :)

**Comment by nicolas-grekas** [comment]
> we defined a staging env which is very close to our prod env but with different secret values

I missed this part. No need for another env, prod mode is fine for staging: the vault can be configured with the `APP_RUNTIME_ENV` env var.

> Remove the early return in the generated App_Kernel*Container.preload.php files,

Looking at the git history, this has been added on purpose, see https://github.com/symfony/symfony/issues/37152#issuecomment-640717569
This is hard to explain in just one sentence so better not add a comment IMHO. PR welcome if you disagree :)

> Check that files ]actually exist when compiling the cache

Done in #48941, for 6.3 as that's a new behavior.

**Comment by sylfabre** [comment]
Thank you @nicolas-grekas for your answers

# `APP_RUNTIME_ENV`
* I understand that `APP_RUNTIME_ENV=xxx` is the same as using `--env=xxx` 
* But I don't understand how I can use the same `prod` env with different values for my secrets 🤔

=> Could you please elaborate on this one

# Early return
I understand that this early return prevents Composer from crashing.
But it also prevents testing that the autoloading file is actually working.
I can't find a better solution 👌

**Comment by nicolas-grekas** [comment]
Check https://symfony.com/doc/current/configuration/secrets.html for APP_RUNTIME_ENV

**Comment by sylfabre** [comment]
@nicolas-grekas I did but still can't figure how to use a single `prod` env with two different sets of values for my secrets.

I have at some point to use these two commands to define different values for each secret:
```
APP_RUNTIME_ENV=prod php bin/console secrets:set DATABASE_PASSWORD // for prod
APP_RUNTIME_ENV=staging php bin/console secrets:set DATABASE_PASSWORD // for staging
```

So I'm still using two different Symfony envs, right?

**Comment by nicolas-grekas** [comment]
Those are using the same Symfony env, but target a different vault.
See the var/cache folder: one single prod folder, but many config/secrets/ones
