### ISSUE TITLE
Redis v6 clear() bug when using lazy:true

### ISSUE THREAD

**Issue by JoniJnm** [symfony/symfony#51679]
### Symfony version(s) affected

6.3.0

### Description

Redis doesn't clear the namespace when using lazy=true (on redis connection or symfony container service)

### How to reproduce

```php
$redisConnection = \Symfony\Component\Cache\Adapter\RedisAdapter::createConnection(
    'redis:?host[my-host]',
    [
        'lazy' => true
    ]
);

$redisAdapter = new \Symfony\Component\Cache\Adapter\RedisAdapter($redisConnection, 'testing');
$redis = new \Symfony\Component\Cache\Psr16Cache($redisAdapter);

$redis->set('my-key', 'my-value');
$redis->clear();
$value = $redis->get('my-key');
// here, $value is "my-value". With lazy=false $value is null
```

### Possible Solution

I don't know if this is a bug in redis but symfony can fix it chaning the `RedisProxy::scan` function:

```php
public function scan(&$iterator, $pattern = null, $count = 0, $type = null): array|false
{
    $this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)();

    if (\func_num_args() > 3) {
        return $this->lazyObjectState->realInstance->scan($iterator, $pattern, $count, $type, ...\array_slice(\func_get_args(), 4));
    } else {
        return $this->lazyObjectState->realInstance->scan($iterator, $pattern, $count);
    }
}
```

Note: this works only for lazy=true on redis conection but the error still exists for lazy=true on symfony container service

### Additional Context

```php
$version = phpversion("redis"); // 6.0.0
```

The `RedisTrait::doClear` function scan all the keys in the namespace:

https://github.com/symfony/symfony/blob/4ba165a7e2c1a9bcdca69393e7fef8f25a66f8ea/src/Symfony/Component/Cache/Traits/RedisTrait.php#L471

When using `lazy: true` parameter (in symfony container service or redis connection), the RedisProxy propagates all the function arguments to the `redis::scan` function:

https://github.com/symfony/symfony/blob/4ba165a7e2c1a9bcdca69393e7fef8f25a66f8ea/src/Symfony/Component/Cache/Traits/Redis6Proxy.php#L891

The problem is: redis doesn't return keys if we send $type=null as parameter

Seems to be related with: https://github.com/phpredis/phpredis/issues/2362

**Comment by JoniJnm** [comment]
Seems to be related with: https://github.com/phpredis/phpredis/issues/2362

**Comment by nicolas-grekas** [comment]
Can you please submit a bug report to phpredis? Looks like this should be fixed there.

**Comment by JoniJnm** [comment]
I think this PR fixes the problem: https://github.com/phpredis/phpredis/pull/2363#issuecomment-1725805475

They merged it to develop branch but I don't know when they will release a new version. You can close this issue if you want.

**Comment by JoniJnm** [comment]
Ouh, you are the author of the fix xD

Do you know when pecl will release a new version with your changes?

**Comment by yakobe** [comment]
Hello awesome symfony people. I also seem to be having a problem with the cache and phpredis v6. I am using the `RedisTagAwareAdapter` and the `$cache->clear()` method does not clear the cache. 

However I can still invalidate specific tags with `$cache->invalidateTags(['tag-name'])`. I have tried the newly released `redis-6.0.1` but it still happens. Rolling back to `redis-5.3.7` fixes the problem. Unfortunately I don't know where to even start looking 😬. Is there anything i can do to help or clarify the problem?

**Comment by OskarStark** [comment]
As this bug is fixed upstream, lets close here.

@yakobe please open a new issue, so that we don't lost track on this, thanks
